Description of cdual_fixtask
cdual_fixtask
PURPOSE
Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
SYNOPSIS
function cdual_fixtask(subjID,exp_mode,acq,displayfile,stimulusfile,gamma_table,overwrite_flg,force_proceed_flag)
DESCRIPTION
 Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
 function cdual_fixtask(subjID,exp_mode,acq,:displayfile,:stimulusfile,:gamma_table,:overwrite_flg,:force_proceed_flag)
 (: is optional)
 - This function generates and presents color/luminance-defined checkerboard stimulus
   (dual stimuli: wedge + annulus) to measure cortical retinotopy and to delineate
   retinotopic borders using the standard phase-encoded or pRF (population receptive
   field) analysis techniques.
   references: 1. Population receptive field estimates in human visual cortex.
                  Dumoulin, S.O. and Wandell, B.A. (2008). Neuroimage, 39(2), 647-660.
               2. Borders of multiple visual areas in humans revealed by functional magnetic resonance imaging.
                  Sereno MI, Dale AM, Reppas JB, Kwong KK, Belliveau JW, Brady TJ, Rosen BR, Tootell RB. (1995).
                  Science 268(5212), 889-893.
               3. fMRI of human visual cortex.
                  Engel SA, Rumelhart DE, Wandell BA, Lee AT, Glover GH, Chichilnisky EJ, Shadlen MN. (1994).
                  Nature, 369(6481), 525.
               4. Visual field maps in human cortex.
                  Wandell BA, Dumoulin SO, Brewer AA. (2007). Neuron, 56(2), 366-383.
 - This script shoud be used with MATLAB Psychtoolbox version 3 or above.
 - Luminance detection task: the central fixation point (default: white)
   randomly turns to gray. An observer has to press the button if s/he
   detects this luminance change. Response keys are defined in displayfile.
 [note]
 Behavioral task of (function_name)_fixtask is to detect changes of luminance
 of the central fixation point, while the task in (function_name) is to detect
 changes of luminance of one of the patches in the checkerboard stimuli.
 Here, the central fixation task is more easy to sustain the stable fixation
 on the center of the screen and may be suitable for naive/non-expert
 participants with minimizing unwilling eye movements. However, some studies
 have reported that attention to the target stimulus (checker-patch luminance
 change detection task) is required to get reliable retinotopic representations
 in higher-order visual areas.
 Created    : "2018-12-20 14:26:03 ban"
 Last Update: "2021-06-07 17:28:35 ban"
 [input variables]
 sujID         : ID of subject, string, such as 's01'
                 you also need to create a directory ./subjects/(subj) and put displayfile and stimulusfile there.
                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
                 !!! if 'debug' (case insensitive) is included          !!!
                 !!! in subjID string, this program runs as DEBUG mode; !!!
                 !!! stimulus images are saved as *.png format at       !!!
                 !!! ~/Retinotopy/Presentation/images                   !!!
                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
 exp_mode      : experiment mode that you want to run, one of
  - ccwexp : a checkerboard wedge rotating counter-clockwisely + an expanding annulus
  - cwexp  : a checkerboard wedge rotating clockwisely + an expanding annulus
  - ccwcont: a checkerboard wedge rotating counter-clockwisely + a contracting annulus
  - cwcont : a checkerboard wedge rotating clockwisely + a contracting annulus
 acq           : acquisition number (design file number),
                 an integer, such as 1, 2, 3, ...
 displayfile   : (optional) display condition file,
                 *.m file, such as 'RetDepth_display_fmri.m'
                 the file should be located in ./subjects/(subj)/
 stimulusfile  : (optional) stimulus condition file,
                 *.m file, such as 'RetDepth_stimulus_exp1.m'
                 the file should be located in ./subjects/(subj)/
 gamma_table   : (optional) table(s) of gamma-corrected video input values (Color LookupTable).
                 256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
                 or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
                 The *.mat should include a variable named "gamma_table" consists of a 256x3xN matrix.
                 if you use multiple (more than 1) displays and set a 256x3x1 gamma-table, the same
                 table will be applied to all displays. if the number of displays and gamma tables
                 are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
                 gamma_table will be applied to the second and third displays.
                 if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
 overwrite_flg : (optional) whether overwriting pre-existing result file. if 1, the previous result
                 file with the same acquisition number will be overwritten by the previous one.
                 if 0, the existing file will be backed-up by adding a prefix '_old' at the tail
                 of the file. 0 by default.
 force_proceed_flag : (optional) whether proceeding stimulus presentatin without waiting for
                 the experimenter response (e.g. presesing the ENTER key) or a trigger.
                 if 1, the stimulus presentation will be automatically carried on.
 !!! NOTICE !!!!
 displayfile & stimulusfile should be located at
 ./subjects/(subjID)/
 as ./subjects/(subjID)/*_display_fmri.m
    ./subjects/(subjID)/*_stimuli.m
 [output variables]
 no output matlab variable.
 [output files]
 1. result file
    stored ./subjects/(subjID)/results/(date)
    as ./subjects/(subjID)/results/(date)/(subjID)_cdual_fixtask_(exp_mode)_results_run_(run_num).mat
 [example]
 >> cdual_fixtask('HB','ccwexp',1,'ret_display.m','ret_checker_stimulus_exp1.m')
 [About displayfile]
 The contents of the displayfile are as below.
 (The file includs 6 lines of headers and following display parameters)
 (an example of the displayfile)
 % ************************************************************
 % This is the display configuration file for the retinotopy stimuli
 % Programmed by Hiroshi Ban Nov 01 2013
 % ************************************************************
 % display mode, one of "mono", "dual", "dualcross", "dualparallel", "cross", "parallel", "redgreen", "greenred",
 % "redblue", "bluered", "shutter", "topbottom", "bottomtop", "interleavedline", "interleavedcolumn", "propixxmono", "propixxstereo"
 dparam.ExpMode='mono';
 dparam.scrID=1; % screen ID, generally 0 for a single display setup, 1 for dual display setup
 % a method to start stimulus presentation
 % 0:ENTER/SPACE, 1:Left-mouse button, 2:the first MR trigger pulse (CiNet),
 % 3:waiting for a MR trigger pulse (BUIC) -- checking onset of pin #11 of the parallel port,
 % or 4:custom key trigger (wait for a key input that you specify as tgt_key).
 dparam.start_method=2;
 % a pseudo trigger key from the MR scanner when it starts, valid only when dparam.start_method=4;
 dparam.custom_trigger='t';
 % keyboard settings
 dparam.Key1=51; % key 1 (left)
 dparam.Key2=52; % key 2 (right)
 % screen settings
 %%% whether displaying the stimuli in full-screen mode or
 %%% as is (the precise resolution), 'true' or 'false' (true)
 dparam.fullscr=false;
 %%% the resolution of the screen height
 dparam.ScrHeight=1200;
 %% the resolution of the screen width
 dparam.ScrWidth=1920;
 % whether forcing to use specific frame rate, if 0, the frame rate wil bw computed in the ImagesShowPTB function.
 % if non zero, the value is used as the screen frame rate.
 dparam.force_frame_rate=60;
 % whther skipping the PTB's vertical-sync signal test. if 1, the sync test is skipped
 dparam.skip_sync_test=0;
 [About stimulusfile]
 The contents of the stimulusfile are as below.
 (The file includs 6 lines of headers and following stimulus parameters)
 (an example of the stimulusfile)
 % ************************************************************
 % This is the stimulus parameter file for the dual (wedge + annulus) retinotopy stimulus
 % Programmed by Hiroshi Ban Jan 25 2019
 % ************************************************************
 % "sparam" means "stimulus generation parameters"
 %%% stimulus parameters
 sparam.pol_nwedges     = 4;     % number of wedge subdivisions along polar angle
 sparam.pol_nrings      = 8;     % number of ring subdivisions along eccentricity angle
 sparam.pol_width       = 48;    % wedge width in deg along polar angle
 sparam.pol_phase       = 0;     % phase shift in deg
 sparam.pol_rotangle    = 12;    % rotation angle in deg
 sparam.pol_startangle  = -sparam.pol_width/2-90; % presentation start angle in deg, from right-horizontal meridian, ccw
 sparam.ecc_nwedges     = 4;     % number of wedge subdivisions along polar angle
 sparam.ecc_nrings      = 2;     % number of ring subdivisions along eccentricity angle
 sparam.ecc_width       = sparam.pol_width/2;
 sparam.ecc_phase       = 0;     % phase shift in deg
 sparam.ecc_rotangle    = sparam.pol_rotangle;
 sparam.ecc_startangle  = -sparam.ecc_width/2-90;  % presentation start angle in deg, from right-horizontal meridian, ccw (actually this value is not used for the eccentricity stimuli (exp and cont))
 sparam.maxRad      = 6.0;  % maximum radius of  annulus (degrees)
 sparam.minRad      = 0;    % minumum
 sparam.colors      = [ 128, 128, 128; % number of colors for compensating flickering checkerboard
                        255,   0,   0; % the first row is background
                          0, 255,   0; % the second to end are patch colors
                        255, 255,   0;
                          0,   0, 255;
                        255,   0, 255;
                          0, 255, 255;
                        255, 255, 255;
                          0,   0,   0;
                        255, 128,   0;
                        128,   0, 255;];
 %%% duration in msec for each cycle & repetitions
 % ===========================================================================================================================================
 % IMPORTANT NOTE: sparam.pol_cycle_duration x sparam.pol_numRepeats should be the same with sparam.ecc_cycle_duration x sparam.ecc_numRepeats
 % ===========================================================================================================================================
 sparam.pol_cycle_duration=60000; % msec
 sparam.pol_rest_duration =0; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
 sparam.pol_numRepeats=6;
 sparam.ecc_cycle_duration=40000; % msec
 sparam.ecc_rest_duration =8000; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
 sparam.ecc_numRepeats=9;
 %%% set number of frames to flip the screen
 % Here, I set the number as large as I can to minimize vertical cynching error.
 % the final 2 is for 2 times repetitions of flicker
 % Set 1 if you want to flip the display at each vertical sync, but not recommended as it uses much CPU power
 sparam.waitframes = Screen('FrameRate',0)*(sparam.cycle_duration/1000) / (360/sparam.rotangle) / ( (size(sparam.colors,1)-1)*2 );
 % sparam.waitframes = 1;
 %%% fixation period in msec before/after presenting the target stimuli, integer
 % must set a value more than 1 TR for initializing the frame counting.
 sparam.initial_fixation_time=[4000,4000];
 %%% fixation size & color
 sparam.fixtype=1; % 1: circular, 2: rectangular, 3: concentric fixation point
 sparam.fixsize=12; % radius in pixels
 sparam.fixcolor=[255,255,255];
 %%% background color
 sparam.bgcolor=sparam.colors(1,:); %[0,0,0];
 %%% background-patch colors (RGB)
 sparam.bgtype=1; % 1: a simple background with sparam.bgcolor (then, the parameters belows are not used), 2: a background with grid guides
 sparam.patch_size=[30,30]; % background patch size, [height,width] in pixels
 sparam.patch_num=[20,40];  % the number of background patches along vertical and horizontal axis
 sparam.patch_color1=[255,255,255];
 sparam.patch_color2=[0,0,0];
 %%% for converting degree to pixels
 run(fullfile(fileparts(mfilename('fullpath')),'sizeparams'));
 %sparam.pix_per_cm=57.1429;
 %sparam.vdist=65;
 [HOWTO create stimulus files]
 1. All of the stimuli are created in this script in real-time
    with MATLAB scripts & functions.
    see ../Generation & ../Common directries.
 2. Stimulus parameters are defined in the display & stimulus file.
 [reference]
 for stmulus generation, see ../Generation & ../Common directories.
CROSS-REFERENCE INFORMATION
This function calls:
BackUpObsoleteFiles Backups already-existing file(s) in the target directory by adding some file-prefix.
CheckPTBversion Checks the version of the currently running Psychtoolbox.
CreateBackgroundImage Creates background image that can be used as a background of your stimulus displays.
CreateFixationImgCircular Creates a circular fixation image for a monocular display setting.
CreateFixationImgConcentrateMono Creates a circular fixation image for a monocular display setting.
CreateFixationImgMono Creates a cross-shaped fixation image for a monocular display setting.
DisplayMessage2 Displays message on the center of each of multiple PTB windows.
DrawTextureWithCLUT Draws a texture with Color LookupTable you specified (modified version of Screen('DrawTexture')).
GammaLoadPTB Loads and sets display gamma-table(s) using PTB Screen() function.
GammaResetPTB Resets display gamma with PTB Screen() function.
InitializePTBDisplays Initializes PTB screen(s) for monocular/binocular presentations using PsychImaging() function.
InitializeRandomSeed Initializes MATLAB internal state of a random seed.
ValidateStructureFields Validates the input structure and set the default values to the missing field(s)
eventlogger
isstructmember Checks whether the target struct contains a filed you specified as a member.
responselogger
DrawTextureWithCLUT Draws a texture with Color LookupTable you specified (modified version of Screen('DrawTexture')).
ecc_GenerateCheckerBoard1D Generates checkerboard patterns (annulus-based subdivision) with an individual ID number on each patch.
pol_GenerateCheckerBoard1D Generates checkerboard patterns (polar angle-based subdivision) with an individual ID number on each patch.
This function is called by:
SOURCE CODE
function cdual_fixtask(subjID,exp_mode,acq,displayfile,stimulusfile,gamma_table,overwrite_flg,force_proceed_flag)
% Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
% function cdual_fixtask(subjID,exp_mode,acq,:displayfile,:stimulusfile,:gamma_table,:overwrite_flg,:force_proceed_flag)
% (: is optional)
%
% - This function generates and presents color/luminance-defined checkerboard stimulus
%   (dual stimuli: wedge + annulus) to measure cortical retinotopy and to delineate
%   retinotopic borders using the standard phase-encoded or pRF (population receptive
%   field) analysis techniques.
%
%   references: 1. Population receptive field estimates in human visual cortex.
%                  Dumoulin, S.O. and Wandell, B.A. (2008). Neuroimage, 39(2), 647-660.
%               2. Borders of multiple visual areas in humans revealed by functional magnetic resonance imaging.
%                  Sereno MI, Dale AM, Reppas JB, Kwong KK, Belliveau JW, Brady TJ, Rosen BR, Tootell RB. (1995).
%                  Science 268(5212), 889-893.
%               3. fMRI of human visual cortex.
%                  Engel SA, Rumelhart DE, Wandell BA, Lee AT, Glover GH, Chichilnisky EJ, Shadlen MN. (1994).
%                  Nature, 369(6481), 525.
%               4. Visual field maps in human cortex.
%                  Wandell BA, Dumoulin SO, Brewer AA. (2007). Neuron, 56(2), 366-383.
%
% - This script shoud be used with MATLAB Psychtoolbox version 3 or above.
%
% - Luminance detection task: the central fixation point (default: white)
%   randomly turns to gray. An observer has to press the button if s/he
%   detects this luminance change. Response keys are defined in displayfile.
%
% [note]
% Behavioral task of (function_name)_fixtask is to detect changes of luminance
% of the central fixation point, while the task in (function_name) is to detect
% changes of luminance of one of the patches in the checkerboard stimuli.
% Here, the central fixation task is more easy to sustain the stable fixation
% on the center of the screen and may be suitable for naive/non-expert
% participants with minimizing unwilling eye movements. However, some studies
% have reported that attention to the target stimulus (checker-patch luminance
% change detection task) is required to get reliable retinotopic representations
% in higher-order visual areas.
%
%
% Created    : "2018-12-20 14:26:03 ban"
% Last Update: "2021-06-07 17:28:35 ban"
%
%
%
% [input variables]
% sujID         : ID of subject, string, such as 's01'
%                 you also need to create a directory ./subjects/(subj) and put displayfile and stimulusfile there.
%                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
%                 !!! if 'debug' (case insensitive) is included          !!!
%                 !!! in subjID string, this program runs as DEBUG mode; !!!
%                 !!! stimulus images are saved as *.png format at       !!!
%                 !!! ~/Retinotopy/Presentation/images                   !!!
%                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
%
% exp_mode      : experiment mode that you want to run, one of
%  - ccwexp : a checkerboard wedge rotating counter-clockwisely + an expanding annulus
%  - cwexp  : a checkerboard wedge rotating clockwisely + an expanding annulus
%  - ccwcont: a checkerboard wedge rotating counter-clockwisely + a contracting annulus
%  - cwcont : a checkerboard wedge rotating clockwisely + a contracting annulus
% acq           : acquisition number (design file number),
%                 an integer, such as 1, 2, 3, ...
% displayfile   : (optional) display condition file,
%                 *.m file, such as 'RetDepth_display_fmri.m'
%                 the file should be located in ./subjects/(subj)/
% stimulusfile  : (optional) stimulus condition file,
%                 *.m file, such as 'RetDepth_stimulus_exp1.m'
%                 the file should be located in ./subjects/(subj)/
% gamma_table   : (optional) table(s) of gamma-corrected video input values (Color LookupTable).
%                 256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
%                 or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
%                 The *.mat should include a variable named "gamma_table" consists of a 256x3xN matrix.
%                 if you use multiple (more than 1) displays and set a 256x3x1 gamma-table, the same
%                 table will be applied to all displays. if the number of displays and gamma tables
%                 are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
%                 gamma_table will be applied to the second and third displays.
%                 if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
% overwrite_flg : (optional) whether overwriting pre-existing result file. if 1, the previous result
%                 file with the same acquisition number will be overwritten by the previous one.
%                 if 0, the existing file will be backed-up by adding a prefix '_old' at the tail
%                 of the file. 0 by default.
% force_proceed_flag : (optional) whether proceeding stimulus presentatin without waiting for
%                 the experimenter response (e.g. presesing the ENTER key) or a trigger.
%                 if 1, the stimulus presentation will be automatically carried on.
%
% !!! NOTICE !!!!
% displayfile & stimulusfile should be located at
% ./subjects/(subjID)/
% as ./subjects/(subjID)/*_display_fmri.m
%    ./subjects/(subjID)/*_stimuli.m
%
%
% [output variables]
% no output matlab variable.
%
%
% [output files]
% 1. result file
%    stored ./subjects/(subjID)/results/(date)
%    as ./subjects/(subjID)/results/(date)/(subjID)_cdual_fixtask_(exp_mode)_results_run_(run_num).mat
%
%
% [example]
% >> cdual_fixtask('HB','ccwexp',1,'ret_display.m','ret_checker_stimulus_exp1.m')
%
% [About displayfile]
% The contents of the displayfile are as below.
% (The file includs 6 lines of headers and following display parameters)
%
% (an example of the displayfile)
%
% % ************************************************************
% % This is the display configuration file for the retinotopy stimuli
% % Programmed by Hiroshi Ban Nov 01 2013
% % ************************************************************
%
% % display mode, one of "mono", "dual", "dualcross", "dualparallel", "cross", "parallel", "redgreen", "greenred",
% % "redblue", "bluered", "shutter", "topbottom", "bottomtop", "interleavedline", "interleavedcolumn", "propixxmono", "propixxstereo"
% dparam.ExpMode='mono';
%
% dparam.scrID=1; % screen ID, generally 0 for a single display setup, 1 for dual display setup
%
% % a method to start stimulus presentation
% % 0:ENTER/SPACE, 1:Left-mouse button, 2:the first MR trigger pulse (CiNet),
% % 3:waiting for a MR trigger pulse (BUIC) -- checking onset of pin #11 of the parallel port,
% % or 4:custom key trigger (wait for a key input that you specify as tgt_key).
% dparam.start_method=2;
%
% % a pseudo trigger key from the MR scanner when it starts, valid only when dparam.start_method=4;
% dparam.custom_trigger='t';
%
% % keyboard settings
% dparam.Key1=51; % key 1 (left)
% dparam.Key2=52; % key 2 (right)
%
% % screen settings
%
% %%% whether displaying the stimuli in full-screen mode or
% %%% as is (the precise resolution), 'true' or 'false' (true)
% dparam.fullscr=false;
%
% %%% the resolution of the screen height
% dparam.ScrHeight=1200;
%
% %% the resolution of the screen width
% dparam.ScrWidth=1920;
%
% % whether forcing to use specific frame rate, if 0, the frame rate wil bw computed in the ImagesShowPTB function.
% % if non zero, the value is used as the screen frame rate.
% dparam.force_frame_rate=60;
%
% % whther skipping the PTB's vertical-sync signal test. if 1, the sync test is skipped
% dparam.skip_sync_test=0;
%
%
% [About stimulusfile]
% The contents of the stimulusfile are as below.
% (The file includs 6 lines of headers and following stimulus parameters)
%
% (an example of the stimulusfile)
%
% % ************************************************************
% % This is the stimulus parameter file for the dual (wedge + annulus) retinotopy stimulus
% % Programmed by Hiroshi Ban Jan 25 2019
% % ************************************************************
%
% % "sparam" means "stimulus generation parameters"
%
% %%% stimulus parameters
% sparam.pol_nwedges     = 4;     % number of wedge subdivisions along polar angle
% sparam.pol_nrings      = 8;     % number of ring subdivisions along eccentricity angle
% sparam.pol_width       = 48;    % wedge width in deg along polar angle
% sparam.pol_phase       = 0;     % phase shift in deg
% sparam.pol_rotangle    = 12;    % rotation angle in deg
% sparam.pol_startangle  = -sparam.pol_width/2-90; % presentation start angle in deg, from right-horizontal meridian, ccw
%
% sparam.ecc_nwedges     = 4;     % number of wedge subdivisions along polar angle
% sparam.ecc_nrings      = 2;     % number of ring subdivisions along eccentricity angle
% sparam.ecc_width       = sparam.pol_width/2;
% sparam.ecc_phase       = 0;     % phase shift in deg
% sparam.ecc_rotangle    = sparam.pol_rotangle;
% sparam.ecc_startangle  = -sparam.ecc_width/2-90;  % presentation start angle in deg, from right-horizontal meridian, ccw (actually this value is not used for the eccentricity stimuli (exp and cont))
%
% sparam.maxRad      = 6.0;  % maximum radius of  annulus (degrees)
% sparam.minRad      = 0;    % minumum
%
% sparam.colors      = [ 128, 128, 128; % number of colors for compensating flickering checkerboard
%                        255,   0,   0; % the first row is background
%                          0, 255,   0; % the second to end are patch colors
%                        255, 255,   0;
%                          0,   0, 255;
%                        255,   0, 255;
%                          0, 255, 255;
%                        255, 255, 255;
%                          0,   0,   0;
%                        255, 128,   0;
%                        128,   0, 255;];
%
% %%% duration in msec for each cycle & repetitions
% % ===========================================================================================================================================
% % IMPORTANT NOTE: sparam.pol_cycle_duration x sparam.pol_numRepeats should be the same with sparam.ecc_cycle_duration x sparam.ecc_numRepeats
% % ===========================================================================================================================================
%
% sparam.pol_cycle_duration=60000; % msec
% sparam.pol_rest_duration =0; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
% sparam.pol_numRepeats=6;
%
% sparam.ecc_cycle_duration=40000; % msec
% sparam.ecc_rest_duration =8000; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
% sparam.ecc_numRepeats=9;
%
% %%% set number of frames to flip the screen
% % Here, I set the number as large as I can to minimize vertical cynching error.
% % the final 2 is for 2 times repetitions of flicker
% % Set 1 if you want to flip the display at each vertical sync, but not recommended as it uses much CPU power
% sparam.waitframes = Screen('FrameRate',0)*(sparam.cycle_duration/1000) / (360/sparam.rotangle) / ((size(sparam.colors,1)-1)*2);
% % sparam.waitframes = 1;
%
% %%% fixation period in msec before/after presenting the target stimuli, integer
% % must set a value more than 1 TR for initializing the frame counting.
% sparam.initial_fixation_time=[4000,4000];
%
% %%% fixation size & color
% sparam.fixtype=1; % 1: circular, 2: rectangular, 3: concentric fixation point
% sparam.fixsize=12; % radius in pixels
% sparam.fixcolor=[255,255,255];
%
% %%% background color
% sparam.bgcolor=sparam.colors(1,:); %[0,0,0];
%
% %%% background-patch colors (RGB)
% sparam.bgtype=1; % 1: a simple background with sparam.bgcolor (then, the parameters belows are not used), 2: a background with grid guides
% sparam.patch_size=[30,30]; % background patch size, [height,width] in pixels
% sparam.patch_num=[20,40];  % the number of background patches along vertical and horizontal axis
% sparam.patch_color1=[255,255,255];
% sparam.patch_color2=[0,0,0];
%
% %%% for converting degree to pixels
% run(fullfile(fileparts(mfilename('fullpath')),'sizeparams'));
% %sparam.pix_per_cm=57.1429;
% %sparam.vdist=65;
%
%
% [HOWTO create stimulus files]
% 1. All of the stimuli are created in this script in real-time
%    with MATLAB scripts & functions.
%    see ../Generation & ../Common directries.
% 2. Stimulus parameters are defined in the display & stimulus file.
%
%
% [reference]
% for stmulus generation, see ../Generation & ../Common directories.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Check the input variables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear global; clear mex;
if nargin<3, help(mfilename()); return; end
if nargin<4 || isempty(displayfile), displayfile=[]; end
if nargin<5 || isempty(stimulusfile), stimulusfile=[]; end
if nargin<6 || isempty(gamma_table), gamma_table=[]; end
if nargin<7 || isempty(overwrite_flg), overwrite_flg=1; end
if nargin<8 || isempty(force_proceed_flag), force_proceed_flag=0; end
% check the aqcuisition number
if acq<1, error('Acquistion number must be integer and greater than zero'); end
% check the experiment mode (stimulus type)
if ~strcmpi(exp_mode,'ccwexp') && ~strcmpi(exp_mode,'cwexp') && ~strcmpi(exp_mode,'ccwcont') && ~strcmpi(exp_mode,'cwcont')
  error('exp_mode should be one of "ccwexp", "cwexp", "ccwcont", and "cwcont". check the input variable.');
end
rootDir=fileparts(mfilename('fullpath'));
% check the subject directory
if ~exist(fullfile(rootDir,'subjects',subjID),'dir'), error('can not find subj directory. check the input variable.'); end
% check the display/stimulus files
if ~isempty(displayfile)
  if ~strcmpi(displayfile(end-1:end),'.m'), displayfile=[displayfile,'.m']; end
  if ~exist(fullfile(rootDir,'subjects',subjID,displayfile),'file'), error('displayfile not found. check the input variable.'); end
end
if ~isempty(stimulusfile)
  if ~strcmpi(stimulusfile(end-1:end),'.m'), stimulusfile=[stimulusfile,'.m']; end
  if ~exist(fullfile(rootDir,'subjects',subjID,stimulusfile),'file'), error('stimulusfile not found. check the input variable.'); end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Add path to the subfunctions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% add paths to the subfunctions
addpath(genpath(fullfile(rootDir,'..','Common')));
addpath(fullfile(rootDir,'..','Generation'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% For log file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% get date
today=datestr(now,'yymmdd');
% result directry & file
resultDir=fullfile(rootDir,'subjects',num2str(subjID),'results',today);
if ~exist(resultDir,'dir'), mkdir(resultDir); end
% record the output window
logfname=fullfile(resultDir,[num2str(subjID),'_cdual_fixtask_',exp_mode,'_results_run_',num2str(acq,'%02d'),'.log']);
diary(logfname);
warning off; %#ok warning('off','MATLAB:dispatcher:InexactCaseMatch');
%%%%% try & catch %%%%%
try
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Check the PTB version
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PTB_OK=CheckPTBversion(3); % check wether the PTB version is 3
if ~PTB_OK, error('Wrong version of Psychtoolbox is running. %s requires PTB ver.3',mfilename()); end
% debug level, black screen during calibration
Screen('Preference', 'VisualDebuglevel', 3);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setup random seed
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
InitializeRandomSeed();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Reset display Gamma-function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(gamma_table)
  gamma_table=repmat(linspace(0.0,1.0,256),3,1); %#ok
  GammaResetPTB(1.0);
else
  GammaLoadPTB(gamma_table);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Validate dparam (displayfile) and sparam (stimulusfile) structures
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% organize dparam
dparam=struct(); % initialize
if ~isempty(displayfile), run(fullfile(rootDir,'subjects',subjID,displayfile)); end % load specific dparam parameters configured for each of the participants
dparam=ValidateStructureFields(dparam,... % validate fields and set the default values to missing field(s)
         'ExpMode','mono',...
         'scrID',1,...
         'start_method',0,...
         'custom_trigger','t',...
         'Key1',51,...
         'Key2',52,...
         'fullscr',false,...
         'ScrHeight',1200,...
         'ScrWidth',1920,...
         'force_frame_rate',60,...
         'skip_sync_test',0);
% organize sparam
sparam=struct(); % initialize
sparam.mode=exp_mode;
if ~isempty(stimulusfile), run(fullfile(rootDir,'subjects',subjID,stimulusfile)); end % load specific sparam parameters configured for each of the participants
sparam=ValidateStructureFields(sparam,... % validate fields and set the default values to missing field(s)
         'pol_nwedges',4,...
         'pol_nrings',4,...
         'pol_width',48,...
         'pol_phase',0,...
         'pol_rotangle',12,...
         'pol_startangle',-48/2-90,...
         'ecc_nwedges',4,...
         'ecc_nrings',2,...
         'ecc_width',48,...
         'ecc_phase',0,...
         'ecc_rotangle',12,...
         'ecc_startangle',-48/2-90,...
         'maxRad',8,...
         'minRad',0,...
         'colors',[ 128, 128, 128;
                    255,   0,   0;
                      0, 255,   0;
                    255, 255,   0;
                      0,   0, 255;
                    255,   0, 255;
                      0, 255, 255;
                    255, 255, 255;
                      0,   0,   0;
                    255, 128,   0;
                    128,   0, 255],...
         'pol_cycle_duration',60000,...
         'pol_rest_duration',0,...
         'pol_numRepeats',6,...
         'ecc_cycle_duration',40000,...
         'ecc_rest_duration',8000,...
         'ecc_numRepeats',9,...
         'waitframes',6,... % Screen('FrameRate',0)*(sparam.cycle_duration/1000) / (360/sparam.rotangle) / ( (size(sparam.colors,1)-1)*2 );
         'initial_fixation_time',[4000,4000],...
         'fixtype',1,...
         'fixsize',12,...
         'fixcolor',[255,255,255],...
         'bgcolor',[128,128,128],... % sparam.colors(1,:);
         'bgtype',1,...
         'patch_size',[30,30],...
         'patch_num',[20,40],...
         'patch_color1',[255,255,255],...
         'patch_color2',[0,0,0],...
         'pix_per_cm',57.1429,...
         'vdist',65);
% change unit from msec to sec.
sparam.initial_fixation_time=sparam.initial_fixation_time./1000; %#ok
% change unit from msec to sec.
sparam.pol_cycle_duration = sparam.pol_cycle_duration./1000;
sparam.pol_rest_duration  = sparam.pol_rest_duration./1000;
sparam.ecc_cycle_duration = sparam.ecc_cycle_duration./1000;
sparam.ecc_rest_duration  = sparam.ecc_rest_duration./1000;
% set the other parameters
dparam.RunScript = mfilename();
sparam.RunScript = mfilename();
%% check varidity of parameters
fprintf('checking validity of stimulus generation/presentation parameters...');
if sparam.pol_cycle_duration*sparam.pol_numRepeats~=sparam.ecc_cycle_duration*sparam.ecc_numRepeats
  error('sparam.pol_cycle_duration x sparam.pol_numRepeats should be the same with sparam.ecc_cycle_duration x sparam.ecc_numRepeats. check the input variables.');
end
if mod(360,sparam.pol_rotangle), error('mod(360,sparam.pol_rotangle) should be 0. check the input variables.'); end
if mod(360,sparam.ecc_rotangle), error('mod(360,sparam.ecc_rotangle) should be 0. check the input variables.'); end
if mod(sparam.pol_width,sparam.pol_rotangle), error('mod(sparam.pol_width,sparam.pol_rotangle) should be 0. check the input variables.'); end
if mod(sparam.ecc_width,sparam.ecc_rotangle), error('mod(sparam.ecc_width,sparam.ecc_rotangle) should be 0. check the input variables.'); end
fprintf('done.\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying the presentation parameters you set
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('The Presentation Parameters are as below.\n\n');
fprintf('************************************************\n');
fprintf('****** Script, Subject, Acquistion Number ******\n');
fprintf('Date & Time            : %s\n',strcat([datestr(now,'yymmdd'),' ',datestr(now,'HH:mm:ss')]));
fprintf('Running Script Name    : %s\n',mfilename());
fprintf('Subject ID             : %s\n',subjID);
fprintf('Acquisition Number     : %d\n',acq);
fprintf('********* Run Type, Display Image Type *********\n');
fprintf('Display Mode           : %s\n',dparam.ExpMode);
fprintf('use Full Screen Mode   : %d\n',dparam.fullscr);
fprintf('Start Method           : %d\n',dparam.start_method);
if dparam.start_method==4
  fprintf('Custom Trigger         : %d\n',dparam.custom_trigger);
end
fprintf('*************** Screen Settings ****************\n');
fprintf('Screen Height          : %d\n',dparam.ScrHeight);
fprintf('Screen Width           : %d\n',dparam.ScrWidth);
fprintf('*********** Stimulation Periods etc. ***********\n');
fprintf('Fixation Time(sec)     : %d & %d\n',sparam.initial_fixation_time(1),sparam.initial_fixation_time(2));
fprintf('[POL] Cycle Duration(sec) : %d\n',sparam.pol_cycle_duration);
fprintf('      Rest  Duration(sec) : %d\n',sparam.pol_rest_duration);
fprintf('      Repetitions(cycles) : %d\n',sparam.pol_numRepeats);
fprintf('[ECC] Cycle Duration(sec) : %d\n',sparam.ecc_cycle_duration);
fprintf('      Rest  Duration(sec) : %d\n',sparam.ecc_rest_duration);
fprintf('      Repetitions(cycles) : %d\n',sparam.ecc_numRepeats);
fprintf('Frame Flip(per VerSync): %d\n',sparam.waitframes);
fprintf('Total Time (sec)       : %d\n',sum(sparam.initial_fixation_time)+sparam.pol_numRepeats*sparam.pol_cycle_duration);
fprintf('**************** Stimulus Type *****************\n');
fprintf('Experiment Mode        : %s\n',sparam.mode);
fprintf('************ Response key settings *************\n');
fprintf('Reponse Key #1         : %d = %s\n',dparam.Key1,KbName(dparam.Key1));
fprintf('Reponse Key #2         : %d = %s\n',dparam.Key2,KbName(dparam.Key2));
fprintf('************************************************\n\n');
fprintf('Please carefully check before proceeding.\n\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialize response & event logger objects
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialize MATLAB objects for event and response logs
event=eventlogger();
resps=responselogger([dparam.Key1,dparam.Key2]);
resps.initialize(event); % initialize responselogger
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Wait for user reponse to start
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~force_proceed_flag
  [user_answer,resps]=resps.wait_to_proceed();
  if ~user_answer, diary off; return; end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialization of Left & Right screens for binocular presenting/viewing mode
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dparam.skip_sync_test, Screen('Preference','SkipSyncTests',1); end
[winPtr,winRect,nScr,dparam.fps,dparam.ifi,initDisplay_OK]=InitializePTBDisplays(dparam.ExpMode,sparam.bgcolor,0,[],dparam.scrID);
if ~initDisplay_OK, error('Display initialization error. Please check your exp_run parameter.'); end
HideCursor();
if isstructmember(dparam,'force_frame_rate')
  if dparam.force_frame_rate
    dparam.fps=dparam.force_frame_rate;
    dparam.ifi=1/dparam.fps;
  end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setting the PTB runnning priority to MAX
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% set the priority of this script to MAX
priorityLevel=MaxPriority(winPtr,'WaitBlanking');
Priority(priorityLevel);
% conserve VRAM memory: Workaround for flawed hardware and drivers
% 32 == kPsychDontShareContextRessources: Do not share ressources between
% different onscreen windows. Usually you want PTB to share all ressources
% like offscreen windows, textures and GLSL shaders among all open onscreen
% windows. If that causes trouble for some weird reason, you can prevent
% automatic sharing with this flag.
%Screen('Preference','ConserveVRAM',32);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setting the PTB OpenGL functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Enable OpenGL mode of Psychtoolbox: This is crucially needed for clut animation
InitializeMatlabOpenGL();
% This script calls Psychtoolbox commands available only in OpenGL-based
% versions of the Psychtoolbox. (So far, the OS X Psychtoolbox is the
% only OpenGL-base Psychtoolbox.)  The Psychtoolbox command AssertPsychOpenGL will issue
% an error message if someone tries to execute this script on a computer without
% an OpenGL Psychtoolbox
AssertOpenGL();
% set OpenGL blend functions
Screen('BlendFunction', winPtr, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing MATLAB OpenGL shader API
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% just call DrawTextureWithCLUT with window pointer alone
DrawTextureWithCLUT(winPtr);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying 'Initializing...'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% displaying texts on the center of the screen
DisplayMessage2('Initializing...',sparam.bgcolor,winPtr,nScr,'Arial',36);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing variables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% unit conversion
% cm per pix
sparam.cm_per_pix=1/sparam.pix_per_cm;
% pixles per degree
sparam.pix_per_deg=round(1/(180*atan(sparam.cm_per_pix/sparam.vdist)/pi));
% deg to radian
% do not convert!
% sparam.width, sparam.phase, sparam.startangle, sparam.rotangle are used in deg formats
% number of checkerboard color
sparam.ncolors=(size(sparam.colors,1)-1)/2;
% sec to number of frames
nframe_fixation=round(sparam.initial_fixation_time.*dparam.fps./sparam.waitframes);
sparam.pol_npositions=360/sparam.pol_rotangle;
sparam.ecc_npositions=sparam.pol_npositions*(sparam.ecc_cycle_duration-sparam.ecc_rest_duration)/(sparam.pol_cycle_duration-sparam.pol_rest_duration);
nframe_stim=round((sparam.pol_cycle_duration-sparam.pol_rest_duration)*dparam.fps/(360/sparam.pol_rotangle)/sparam.waitframes);
nframe_flicker=round(nframe_stim/sparam.ncolors/4);
nframe_task=round(18/sparam.waitframes); % just arbitral, you can change as you like
%% initialize chackerboard parameters
% adjust size ratio considering full-screen effect
if dparam.fullscr
  % here, use width information alone, assuming that the pixel is square
  ratio_wid=( winRect(3)-winRect(1) )/dparam.ScrWidth;
  %ratio_hei=( winRect(4)-winRect(2) )/dparam.ScrHeight;
  % min/max radius of annulus
  rmin=sparam.minRad*ratio_wid; % !!! degree, not pixel or cm !!!
  rmax=sparam.maxRad*ratio_wid;
else
  rmin=sparam.minRad;
  rmax=sparam.maxRad;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Generating checkerboard patterns
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% [note]
% After this processing, each checkerboard image has checker elements with values as shown below
% 0 = background
% 1 = checker ID 1
% 2 = checker ID 2
% 3 = checker ID 3
% .....
% sparam.npatches = checker ID
% Each patch ID will be associated with a CLUT color of the same ID
%%% a wedge for polar representation
startangles=zeros(sparam.pol_npositions,1);
for nn=1:1:sparam.pol_npositions, startangles(nn)=sparam.pol_startangle+(nn-1)*sparam.pol_rotangle; end
[pol_checkerboardID,pol_checkerboard]=pol_GenerateCheckerBoard1D(rmin,rmax,sparam.pol_width,startangles,sparam.pix_per_deg,...
                                                                       sparam.pol_nwedges,sparam.pol_nrings,sparam.pol_phase);
%%% an annulus for eccentricity representation
eccedge=(rmax-rmin)/(sparam.ecc_npositions-1);
eccwidth=eccedge*(sparam.ecc_width/sparam.ecc_rotangle);
% get annuli's min/max lims
ecclims=zeros(sparam.ecc_npositions,3);
for nn=1:1:sparam.ecc_npositions %1:1:sparam.npositions
  minlim=rmin+(nn-1)*eccedge-eccwidth/2;
  if minlim<rmin, minlim=rmin; end
  maxlim=rmin+(nn-1)*eccedge+eccwidth/2;
  if maxlim>rmax, maxlim=rmax; end
  ecclims(nn,:)=[minlim,maxlim,eccwidth];
end
[ecc_checkerboardID,ecc_checkerboard]=ecc_GenerateCheckerBoard1D(ecclims,360,sparam.ecc_startangle,sparam.pix_per_deg,...
                                      round(360*sparam.ecc_nwedges/sparam.ecc_width),sparam.ecc_nrings,sparam.ecc_phase);
%% flip all data for ccw/cont
if ~isempty(strfind(sparam.mode,'ccw'))
  tmp_checkerboardID=cell(sparam.pol_npositions,1);
  for nn=1:1:sparam.pol_npositions, tmp_checkerboardID{nn}=pol_checkerboardID{sparam.pol_npositions-(nn-1)}; end
  pol_checkerboardID=tmp_checkerboardID;
  clear tmp_checkerboardID;
  tmp_checkerboard=cell(sparam.pol_npositions,1);
  for nn=1:1:sparam.pol_npositions, tmp_checkerboard{nn}=pol_checkerboard{sparam.pol_npositions-(nn-1)}; end
  pol_checkerboard=tmp_checkerboard;
  clear tmp_checkerboard;
end
if ~isempty(strfind(sparam.mode,'cont'))
  tmp_checkerboardID=cell(sparam.ecc_npositions,1);
  for nn=1:1:sparam.ecc_npositions, tmp_checkerboardID{nn}=ecc_checkerboardID{sparam.ecc_npositions-(nn-1)}; end
  ecc_checkerboardID=tmp_checkerboardID;
  clear tmp_checkerboardID;
  tmp_checkerboard=cell(sparam.ecc_npositions,1);
  for nn=1:1:sparam.ecc_npositions, tmp_checkerboard{nn}=ecc_checkerboard{sparam.ecc_npositions-(nn-1)}; end
  ecc_checkerboard=tmp_checkerboard;
  clear tmp_checkerboard;
end
%%% generate the combined checkerboard patterns
commduration=lcm(sparam.pol_cycle_duration,sparam.ecc_cycle_duration); % the least common multiple duration at which the stimulus rotation turns to the beginning.
if commduration<sparam.pol_cycle_duration*sparam.pol_numRepeats
  pol_subrepeats=ceil(commduration/sparam.pol_cycle_duration);
  ecc_subrepeats=ceil(commduration/sparam.ecc_cycle_duration);
else
  fprintf('WARNING: It is recommended to adjust the sparam parameters so that lcm(sparam.pol_cycle_duration,sparam.ecc_cycle_duration) is less than sparam.pol_cycle_duration*sparam.pol_numRepeats\n');
  pol_subrepeats=sparam.pol_numRepeats;
  ecc_subrepeats=sparam.ecc_numRepeats;
end
% put the rest period for polar patterns
nrest=sparam.pol_npositions/(sparam.pol_cycle_duration-sparam.pol_rest_duration)*sparam.pol_rest_duration;
if nrest>0
  if ~isempty(strfind(sparam.mode,'ccw'))
    pol_checkerboard=[pol_checkerboard;repmat({zeros(size(pol_checkerboard{1}))},nrest,1)];
    pol_checkerboardID=[pol_checkerboardID;repmat({zeros(size(pol_checkerboardID{1}))},nrest,1)];
  else % if ~isempty(strfind(sparam.mode,'cw'))
    pol_checkerboard=[repmat({zeros(size(pol_checkerboard{1}))},nrest,1);pol_checkerboard];
    pol_checkerboardID=[repmat({zeros(size(pol_checkerboardID{1}))},nrest,1);pol_checkerboardID];
  end
end
% put the rest period for eccentricity patterns
nrest=sparam.ecc_npositions/(sparam.ecc_cycle_duration-sparam.ecc_rest_duration)*sparam.ecc_rest_duration;
if nrest>0
  if ~isempty(strfind(sparam.mode,'cont'))
    ecc_checkerboard=[repmat({zeros(size(ecc_checkerboard{1}))},nrest,1);ecc_checkerboard];
    ecc_checkerboardID=[repmat({zeros(size(ecc_checkerboardID{1}))},nrest,1);ecc_checkerboardID];
  else % if ~isempty(strfind(sparam.mode,'ecc'))
    ecc_checkerboard=[ecc_checkerboard;repmat({zeros(size(ecc_checkerboard{1}))},nrest,1)];
    ecc_checkerboardID=[ecc_checkerboardID;repmat({zeros(size(ecc_checkerboardID{1}))},nrest,1)];
  end
end
% multiply the patterns for the pol_subrepeats
pol_checkerboard=repmat(pol_checkerboard,pol_subrepeats,1);
pol_checkerboardID=repmat(pol_checkerboardID,pol_subrepeats,1);
% initialize the final checkerboard by eccentricity patterns
checkerboard=repmat(ecc_checkerboard,ecc_subrepeats,1);
checkerboardID=repmat(ecc_checkerboardID,ecc_subrepeats,1);
% get the maximum ID of the ecc_checkerboardID
maxID=1;
for nn=1:1:length(ecc_checkerboardID)
  if maxID<max(ecc_checkerboardID{nn}(:))
    maxID=max(ecc_checkerboardID{nn}(:));
  end
end
% overwrite the polar patterns
for nn=1:1:length(pol_checkerboard)
  checkerboard{nn}(pol_checkerboard{nn}~=0)=pol_checkerboard{nn}(pol_checkerboard{nn}~=0);
  checkerboardID{nn}(pol_checkerboardID{nn}~=0)=pol_checkerboardID{nn}(pol_checkerboardID{nn}~=0)+maxID; % +maxID is required to avoid overlapping of the IDs
end
clear pol_checkerboard pol_checkerboardID ecc_checkerboard ecc_checkerboardID;
% generate the final checkerboard patterns
subrepeats=ceil(sparam.pol_numRepeats/pol_subrepeats);
checkerboard=repmat(checkerboard,[subrepeats,1]);
checkerboardID=repmat(checkerboardID,[subrepeats,1]);
% cut the patterns that exceeds the whole stimulus presentation trials
if length(checkerboard) > sparam.pol_cycle_duration*sparam.pol_numRepeats/(sparam.pol_cycle_duration/sparam.pol_npositions)
  checkerboard=checkerboard(1:sparam.pol_cycle_duration*sparam.pol_numRepeats/(sparam.pol_cycle_duration/sparam.pol_npositions));
end
%% Make Checkerboard textures
checkertexture=cell(length(checkerboard),1);
for nn=1:1:length(checkerboard)
  checkertexture{nn}=Screen('MakeTexture',winPtr,checkerboard{nn});
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing Color Lookup-Table (CLUT)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% [note]
% all checker color/luminance flickering is realized by just flipping CLUT generated here
% to save memory and CPU power
CLUT=cell(sparam.ncolors,2); % 2 is for compensating patterns
% generate base CLUT
for cc=1:1:sparam.ncolors
  for pp=1:1:2 % compensating checkers
    % initialize, DrawTextureWithCLUT requires [256x4] color lookup table even when we do not use whole 256 colors
    % though DrawTextureWithCLUT does not support alpha transparency up to now...
    CLUT{cc,pp}=zeros(256,4);
    CLUT{cc,pp}(:,4)=1; % default alpha is 1 (no transparent)
    CLUT{cc,pp}(1,:)=[sparam.colors(1,:),0]; % background LUT, default alpha is 0 (invisible);
    if ~mod(pp,2)
      CLUT{cc,pp}(2,1:3)=sparam.colors(2*cc,:);
      CLUT{cc,pp}(3,1:3)=sparam.colors(2*cc+1,:);
    else
      CLUT{cc,pp}(2,1:3)=sparam.colors(2*cc+1,:);
      CLUT{cc,pp}(3,1:3)=sparam.colors(2*cc,:);
    end
  end % for pp=1:1:2 % compensating checkers
end % for cc=1:1:sparam.ncolors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Debug codes
%%%% saving the stimulus images as *.png format files and enter the debug (keyboard) mode
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %%%%%% DEBUG codes start here
% note: debug stimuli have no jitters of binocular disparity
if strfind(upper(subjID),'DEBUG')
  % just to get stimulus figures
  Screen('CloseAll');
  save_dir=fullfile(resultDir,'images_cdual_fixtask');
  if ~exist(save_dir,'dir'), mkdir(save_dir); end
  figure; hold off;
  for nn=1:1:length(checkerboard)
    imagesc(checkerboard{nn}+1,[1,numel(unique(checkerboard{nn}))]);
    axis off; axis equal;
    for cc=1:1:sparam.ncolors
      for pp=1:1:2 % compensating checkers
        colormap(CLUT{cc,pp}(1:3,1:3)./255);
        drawnow;
        pause(0.05);
        imwrite(checkerboard{nn}+1,CLUT{cc,pp}(1:3,1:3)./255,fullfile(save_dir,sprintf('retinotopy_%s_pos_%02d_lut_%02d_%02d.png',sparam.mode,nn,cc,pp)),'png'); % +1 is required as the image index is assumed to be started from 1.
      end
    end
  end
  close all;
  save(fullfile(save_dir,sprintf('stimulus_%s.mat',sparam.mode)),'checkerboard','sparam','dparam','CLUT');
  keyboard;
end % if strfind(upper(subjID),'DEBUG')
% %%%%%% DEBUG code ends here
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Generating fixation detection task parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% set task variables
% flag to decide whether presenting fixation task
totalframes=max(sum(nframe_fixation),1)+length(checkerboard)*nframe_stim;
num_tasks=ceil(totalframes/nframe_task);
task_flg=ones(1,num_tasks);
for nn=2:1:num_tasks
  if task_flg(nn-1)==2
    task_flg(nn)=1;
  else
    if mod(randi(4,1),4)==0 % this is arbitral, but I put these lines just to reduce the number of tasks
      task_flg(nn)=round(rand(1,1))+1;
    else
      task_flg(nn)=1;
    end
  end
end
task_flg=repmat(task_flg,nframe_task,1);
task_flg=task_flg(:);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing checkerboard color management parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% checkerboard color id
color_id=1;
% checkerboard compensating color id
compensate_id=1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Creating background images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if sparam.bgtype==1 % a simple background with sparam.bgcolor
  bgimg{1}=repmat(reshape(sparam.colors(1,:),[1,1,3]),[dparam.ScrHeight,dparam.ScrWidth]);
elseif sparam.bgtype==2 % a background with grid guides
  % calculate the central aperture size of the background image
  edgeY=mod(dparam.ScrHeight,sparam.patch_num(1)); % delete the exceeded region
  p_height=round((dparam.ScrHeight-edgeY)/sparam.patch_num(1)); % height in pix of patch_height + interval-Y
  edgeX=mod(dparam.ScrWidth,sparam.patch_num(2)); % delete exceeded region
  p_width=round((dparam.ScrWidth-edgeX)/sparam.patch_num(2)); % width in pix of patch_width + interval-X
  if dparam.fullscr
    aperture_size=[2*( p_height*ceil( size(checkerboard{1},1)/2*( (winRect(4)-winRect(2))/dparam.ScrHeight ) /p_height ) ),...
                   2*( p_width*ceil( size(checkerboard{1},2)/2*( (winRect(3)-winRect(1))/dparam.ScrWidth ) /p_width ) )];
  else
    aperture_size=[2*( p_height*ceil(size(checkerboard{1},1)/2/p_height) ),...
                   2*( p_width*ceil(size(checkerboard{1},2)/2/p_width) )];
  end
  bgimg=CreateBackgroundImage([dparam.ScrHeight,dparam.ScrWidth],aperture_size,sparam.patch_size,sparam.bgcolor,sparam.patch_color1,sparam.patch_color2,sparam.fixcolor,sparam.patch_num,0,0,0);
else
  error('sparam.bgtype should be 1 or 2. check the input variable.');
end
background=Screen('MakeTexture',winPtr,bgimg{1});
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Creating the central fixation, cross images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create fixation cross images.
% Firstly larger fixations are generated, then they are antialiased. This is required to present a beautiful circle
if sparam.fixtype==1 % circular fixation
  fixW=CreateFixationImgCircular(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*sparam.fixsize,0,0);
  fixD=CreateFixationImgCircular(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*sparam.fixsize,0,0);
elseif sparam.fixtype==2 % rectangular fixation
  fixW=CreateFixationImgMono(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*2,4*ceil(0.4*sparam.fixsize),0,0);
  fixD=CreateFixationImgMono(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*2,4*ceil(0.4*sparam.fixsize),0,0);
elseif sparam.fixtype==3 % concentric fixation
  fixW=CreateFixationImgConcentrateMono(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*[2,ceil(0.8*sparam.fixsize)],0,0,0);
  fixD=CreateFixationImgConcentrateMono(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*[2,ceil(0.8*sparam.fixsize)],0,0,0);
else
  error('sparam.fixtype should be one of 1,2, and 3. check the input variable.');
end
fixW=imresize(fixW,0.25);
fixD=imresize(fixD,0.25);
fix=cell(2,1); % 1 is for default fixation, 2 is for darker fixation (luminance detection task)
fix{1}=Screen('MakeTexture',winPtr,fixW);
fix{2}=Screen('MakeTexture',winPtr,fixD);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Prepare blue lines for stereo image flip sync with VPixx PROPixx
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% There seems to be a blueline generation bug on some OpenGL systems.
% SetStereoBlueLineSyncParameters(winPtr, winRect(4)) corrects the
% bug on some systems, but breaks on other systems.
% We'll just disable automatic blueline, and manually draw our own bluelines!
if strcmpi(dparam.ExpMode,'propixxstereo')
  SetStereoBlueLineSyncParameters(winPtr, winRect(4)+10);
  blueRectOn(1,:)=[0, winRect(4)-1, winRect(3)/4, winRect(4)];
  blueRectOn(2,:)=[0, winRect(4)-1, winRect(3)*3/4, winRect(4)];
  blueRectOff(1,:)=[winRect(3)/4, winRect(4)-1, winRect(3), winRect(4)];
  blueRectOff(2,:)=[winRect(3)*3/4, winRect(4)-1, winRect(3), winRect(4)];
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Image size adjusting to match the current display resolutions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dparam.fullscr
  ratio_wid= ( winRect(3)-winRect(1) )/dparam.ScrWidth;
  ratio_hei= ( winRect(4)-winRect(2) )/dparam.ScrHeight;
  bgSize   = [size(bgimg{1},2)*ratio_wid, size(bgimg{1},1)*ratio_hei];
  stimSize = [size(checkerboard{1},2)*ratio_wid, size(checkerboard{1},1)*ratio_hei];
  fixSize  = [2*sparam.fixsize*ratio_wid, 2*sparam.fixsize*ratio_hei];
else
  bgSize   = [dparam.ScrWidth, dparam.ScrHeight];
  stimSize = [size(checkerboard{1},2), size(checkerboard{1},1)];
  fixSize  = [2*sparam.fixsize, 2*sparam.fixsize];
end
% for some display modes in which one screen is splitted into two binocular displays
if strcmpi(dparam.ExpMode,'cross') || strcmpi(dparam.ExpMode,'parallel') || ...
   strcmpi(dparam.ExpMode,'topbottom') || strcmpi(dparam.ExpMode,'bottomtop')
  bgSize=bgSize./2;
  stimSize=stimSize./2;
  fixSize=fixSize./2;
end
bgRect  = [0, 0, bgSize]; % used to display background images;
stimRect= [0, 0, stimSize];
fixRect = [0, 0, fixSize]; % used to display the central fixation point
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialize functions and variables for trial loop
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialize variables that we will use during the experiment (faster)
cur_frames=0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying 'Ready to Start'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% displaying texts on the center of the screen
DisplayMessage2('Ready to Start',sparam.bgcolor,winPtr,nScr,'Arial',36);
ttime=GetSecs(); while (GetSecs()-ttime < 0.5), end  % run up the clock.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Flip the display(s) to the background image(s)
%%%% and inform the ready of stimulus presentation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1000 % change the screen and wait for the trigger or pressing the start button
1001 for nn=1:1:nScr
1002   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1003   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1004   Screen('DrawTexture',winPtr,fix{2},[],CenterRect(fixRect,winRect));
1005
1006   % blue line for stereo sync
1007   if strcmpi(dparam.ExpMode,'propixxstereo')
1008     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1009     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1010   end
1011 end
1012 Screen('DrawingFinished',winPtr);
1013 Screen('Flip', winPtr,[],[],[],1);
1014
1015 % prepare the next frame for the initial fixation period
1016 for nn=1:1:nScr
1017   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1018   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1019   Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect)); % fix{1} is valis as no task in the first period
1020
1021   % blue line for stereo sync
1022   if strcmpi(dparam.ExpMode,'propixxstereo')
1023     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1024     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1025   end
1026 end
1027 Screen('DrawingFinished',winPtr);
1028
1029
1030 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1031 %%%% Wait for the first trigger pulse from fMRI scanner or start with button pressing
1032 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1033
1034 % add time stamp (this also works to load add_event method in memory in advance of the actual displays)
1035 fprintf('\nWaiting for the start...\n');
1036 event=event.add_event('Experiment Start',strcat([datestr(now,'yymmdd'),' ',datestr(now,'HH:mm:ss')]),NaN);
1037
1038 % waiting for stimulus presentation
1039 resps.wait_stimulus_presentation(dparam.start_method,dparam.custom_trigger);
1040 %PlaySound(1);
1041 fprintf('\nExperiment running...\n');
1042
1043
1044 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1045 %%%% Initial Fixation Period
1046 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1047
1048 vbl=Screen('Flip',winPtr,[],[],[],1); % the first flip
1049 [event,the_experiment_start]=event.set_reference_time(vbl);
1050 event=event.add_event('Initial Fixation',[]);
1051 fprintf('\nfixation\n\n');
1052 cur_frames=cur_frames+1;
1053
1054 % wait for the initial fixation
1055 for ff=1:1:nframe_fixation(1)
1056   for nn=1:1:nScr
1057     Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1058     Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1059     Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect));
1060
1061     % blue line for stereo sync
1062     if strcmpi(dparam.ExpMode,'propixxstereo')
1063       Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1064       Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1065     end
1066   end
1067   Screen('DrawingFinished',winPtr);
1068   while GetSecs()<vbl+(ff*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1069   Screen('Flip',winPtr,[],[],[],1);
1070
1071   % update task
1072   cur_frames=cur_frames+1;
1073   if task_flg(cur_frames-1)==2 && task_flg(cur_frames-2)==1, event=event.add_event('Luminance Task',[]); end
1074 end
1075
1076
1077 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1078 %%%% The Trial Loop
1079 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1080
1081 for cc=1:1:length(checkerboard)
1082
1083   %% stimulus presentation loop
1084   for ff=1:1:nframe_stim
1085
1086     %% display the current frame
1087     for nn=1:1:nScr
1088       Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1089       Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect)); % background
1090       DrawTextureWithCLUT(winPtr,checkertexture{cc},CLUT{color_id,compensate_id},[],CenterRect(stimRect,winRect)); % checkerboard
1091       Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect)); % the central fixation oval
1092
1093       % blue line for stereo sync
1094       if strcmpi(dparam.ExpMode,'propixxstereo')
1095         Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1096         Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1097       end
1098     end
1099
1100     % flip the window
1101     Screen('DrawingFinished',winPtr);
1102     while GetSecs()<vbl+sparam.initial_fixation_time(1)+(((cc-1)*nframe_stim+(ff-1))*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1103     Screen('Flip',winPtr,[],[],[],1);
1104
1105     if ff==1
1106       event=event.add_event(sprintf('Trial: %d',cc),[]);
1107       if cc==1, fprintf('Trial: '); end
1108       if mod(cc,20)~=0 && cc~=length(checkerboard), fprintf(sprintf('%03d, ',cc)); end
1109       if mod(cc,20)==0 || cc==length(checkerboard), fprintf('%03d\n       ',cc); end
1110     end
1111
1112     % update task
1113     cur_frames=cur_frames+1;
1114     if task_flg(cur_frames)==2 && task_flg(cur_frames-1)==1, event=event.add_event('Luminance Task',[]); end
1115
1116     %% exit from the loop if the final frame is displayed
1117     if ff==nframe_stim && cc==length(checkerboard), continue; end
1118
1119     %% update IDs
1120
1121     % flickering checkerboard
1122     if ~mod(ff,nframe_flicker) % color reversal
1123       compensate_id=mod(compensate_id,2)+1;
1124     end
1125
1126     if ~mod(ff,2*nframe_flicker) % color change
1127       color_id=color_id+1;
1128       if color_id>sparam.ncolors, color_id=1; end
1129     end
1130   end % for ff=1:1:nframe_stim
1131 end % for cc=1:1:length(checkerboard)
1132
1133
1134 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1135 %%%% Final Fixation
1136 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1137
1138 for nn=1:1:nScr
1139   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1140   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1141   Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect));
1142
1143   % blue line for stereo sync
1144   if strcmpi(dparam.ExpMode,'propixxstereo')
1145     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1146     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1147   end
1148 end
1149 Screen('DrawingFinished',winPtr);
1150 while GetSecs()<vbl+sparam.initial_fixation_time(1)+sparam.pol_numRepeats*sparam.pol_cycle_duration-0.5*dparam.ifi, [resps,event]=resps.check_responses(event); end
1151 Screen('Flip',winPtr,[],[],[],1);
1152 %cur_frames=cur_frames+1;
1153 event=event.add_event('Final Fixation',[]);
1154 fprintf('\nfixation\n');
1155
1156 % wait for the initial fixation
1157 for ff=1:1:nframe_fixation(2)
1158   for nn=1:1:nScr
1159     Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1160     Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1161     Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect));
1162
1163     % blue line for stereo sync
1164     if strcmpi(dparam.ExpMode,'propixxstereo')
1165       Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1166       Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1167     end
1168   end
1169   Screen('DrawingFinished',winPtr);
1170   while GetSecs()<vbl+sparam.initial_fixation_time(1)+sparam.pol_numRepeats*sparam.pol_cycle_duration+(ff*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1171   Screen('Flip',winPtr,[],[],[],1);
1172
1173   % update task
1174   cur_frames=cur_frames+1;
1175   if task_flg(cur_frames-1)==2 && task_flg(cur_frames-2)==1, event=event.add_event('Luminance Task',[]); end
1176 end
1177
1178 % the final clock up
1179 while GetSecs()-the_experiment_start<sum(sparam.initial_fixation_time)+sparam.pol_numRepeats*sparam.pol_cycle_duration
1180   [resps,event]=resps.check_responses(event);
1181 end
1182
1183
1184 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1185 %%%% Experiment & scanner end here
1186 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1187
1188 experimentDuration=GetSecs()-the_experiment_start;
1189 event=event.add_event('End',[]);
1190 fprintf('\n');
1191 fprintf('Experiment Completed: %.2f/%.2f secs\n',experimentDuration,...
1192         sum(sparam.initial_fixation_time)+sparam.pol_numRepeats*sparam.pol_cycle_duration);
1193 fprintf('\n');
1194
1195
1196 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1197 %%%% Cleaning up MATLAB OpenGL shader API
1198 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1199
1200 % just call DrawTextureWithCLUT without any input argument
1201 DrawTextureWithCLUT();
1202
1203
1204 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1205 %%%% Cleaning up the PTB screen
1206 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1207
1208 Screen('CloseAll');
1209
1210 % closing datapixx
1211 if strcmpi(dparam.ExpMode,'propixxmono') || strcmpi(dparam.ExpMode,'propixxstereo')
1212   if Datapixx('IsViewpixx3D')
1213     Datapixx('DisableVideoLcd3D60Hz');
1214     Datapixx('RegWr');
1215   end
1216   Datapixx('Close');
1217 end
1218
1219 ShowCursor();
1220 Priority(0);
1221 GammaResetPTB(1.0);
1222
1223
1224 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1225 %%%% Write data into file for post analysis
1226 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1227
1228 % saving the results
1229 fprintf('saving data...');
1230
1231 % save data
1232 savefname=fullfile(resultDir,[num2str(subjID),'_cdual_fixtask_',sparam.mode,'_results_run_',num2str(acq,'%02d'),'.mat']);
1233
1234 % backup the old file(s)
1235 if ~overwrite_flg
1236   BackUpObsoleteFiles(fullfile('subjects',num2str(subjID),'results',today),...
1237                       [num2str(subjID),'_cdual_fixtask_',sparam.mode,'_results_run_',num2str(acq,'%02d'),'.mat'],'_old');
1238 end
1239
1240 eval(sprintf('save %s subjID acq sparam dparam event gamma_table;',savefname));
1241 fprintf('done.\n');
1242
1243 % calculate & display task performance
1244 fprintf('calculating task accuracy...\n');
1245 correct_event=cell(2,1); for ii=1:1:2, correct_event{ii}=sprintf('key%d',ii); end
1246 [task.numTasks,task.numHits,task.numErrors,task.numResponses,task.RT]=event.calc_accuracy(correct_event);
1247 event=event.get_event(); % convert an event logger object to a cell data structure
1248 eval(sprintf('save -append %s event task;',savefname));
1249 fprintf('done.\n');
1250
1251
1252 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1253 %%%% Removing path to the subfunctions, and finalizing the script
1254 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1255
1256 rmpath(genpath(fullfile(rootDir,'..','Common')));
1257 rmpath(fullfile(rootDir,'..','Generation'));
1258 clear all; clear mex; clear global;
1259 diary off;
1260
1261
1262 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1263 %%%% tell the experimenter that the measurements are completed
1264 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1265
1266 try
1267   for ii=1:1:3, Snd('Play',sin(2*pi*0.2*(0:900)),8000); end
1268 catch
1269   % do nothing
1270 end
1271
1272
1273 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1274 %%%% Catch the errors
1275 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1276
1277 catch lasterror
1278   % this "catch" section executes in case of an error in the "try" section
1279   % above.  Importantly, it closes the onscreen window if its open.
1280   Screen('CloseAll');
1281
1282   if exist('dparam','var')
1283     if isstructmember(dparam,'ExpMode')
1284       if strcmpi(dparam.ExpMode,'propixxmono') || strcmpi(dparam.ExpMode,'propixxstereo')
1285         if Datapixx('IsViewpixx3D')
1286           Datapixx('DisableVideoLcd3D60Hz');
1287           Datapixx('RegWr');
1288         end
1289         Datapixx('Close');
1290       end
1291     end
1292   end
1293
1294   ShowCursor();
1295   Priority(0);
1296   GammaResetPTB(1.0);
1297   tmp=lasterror; %#ok
1298   %if exist('event','var'), event=event.get_event(); end %#ok % just for debugging
1299   diary off;
1300   fprintf(['\nError detected and the program was terminated.\n',...
1301            'To check error(s), please type ''tmp''.\n',...
1302            'Please save the current variables now if you need.\n',...
1303            'Then, quit by ''dbquit''\n']);
1304   keyboard;
1305   rmpath(genpath(fullfile(rootDir,'..','Common')));
1306   rmpath(fullfile(rootDir,'..','Generation'));
1307   clear all; clear mex; clear global;
1308   return
1309 end % try..catch
1310
1311
1312 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1313 %%%%% That's it - we're done
1314 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1315 return;
1316 % end % function cdual_fixtask