Description of cmultifocal
cmultifocal
PURPOSE
Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
SYNOPSIS
function cmultifocal(subjID,exp_mode,acq,displayfile,stimulusfile,gamma_table,overwrite_flg,force_proceed_flag)
DESCRIPTION
 Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
 function cmultifocal(subjID,exp_mode,acq,:displayfile,:stimulusfile,:gamma_table,:overwrite_flg,:force_proceed_flag)
 (: is optional)
 - This function generates and presents color/luminance-defined multi-focal checkerboard
   stimulus for indentifying retinotopic visual areas and their visual field representations
   based on the standard multi-focal retinotopy analysis.
   reference: Multifocal fMRI mapping of visual cortical areas.
              Vanni, S., Henriksson, L., James, A.C. (2005). Neuroimage, 27(1), 95-105.
 - This script shoud be used with MATLAB Psychtoolbox version 3 or above.
 - Luminance detection task: one of the checks of the checkerboard pattern
   randomly turns to darker. An observer has to press the button if s/he
   detects this luminance change. Response keys are defined in displayfile.
 [note]
 Behavioral task of (function_name)_fixtask is to detect changes of luminance
 of the central fixation point, while the task in (function_name) is to detect
 changes of luminance of one of the patches in the checkerboard stimuli.
 Here, the central fixation task is more easy to sustain the stable fixation
 on the center of the screen and may be suitable for naive/non-expert
 participants with minimizing unwilling eye movements. However, some studies
 have reported that attention to the target stimulus (checker-patch luminance
 change detection task) is required to get reliable retinotopic representations
 in higher-order visual areas.
 [*** IMPORTANT NOTE ***]
 The multi-focal checkerboard patterns are randomly generated based on mseq() function.
 To analyze the fMRI/MEG time series for specific patterns, please load result files,
 ./subjects/(subjID)/results/(date)/(subjID)_cmultifocal_results_run_(run_num).mat.
 In these files, "sparam.design", "checkerboard" and "checkerboardID" variables are stored,
 which are exactly the checkerboard patterns used in the sessions.
 By putting the variables into the gen_multifocal_windows() function, you can generate
 the stimulus windows across time
 Or by using sparam.deisgn, you can generate stimulus presentation protocol for GLM analysis.
 Created    : "2018-11-29 12:13:43 ban"
 Last Update: "2021-06-07 17:22:40 ban"
 [input variables]
 sujID         : ID of subject, string, such as 's01'
                 you also need to create a directory ./subjects/(subj) and put displayfile and stimulusfile there.
                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
                 !!! if 'debug' (case insensitive) is included          !!!
                 !!! in subjID string, this program runs as DEBUG mode; !!!
                 !!! stimulus images are saved as *.png format at       !!!
                 !!! ~/Retinotopy/Presentation/images                   !!!
                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
 exp_mode      : experiment mode acceptable in this script is only "multifocal"
 acq           : acquisition number (design file number),
                 an integer, such as 1, 2, 3, ...
 displayfile   : (optional) display condition file,
                 *.m file, such as 'RetDepth_display_fmri.m'
                 the file should be located in ./subjects/(subj)/
 stimulusfile  : (optional) stimulus condition file,
                 *.m file, such as 'RetDepth_stimulus_exp1.m'
                 the file should be located in ./subjects/(subj)/
 gamma_table   : (optional) table(s) of gamma-corrected video input values (Color LookupTable).
                 256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
                 or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
                 The *.mat should include a variable named "gamma_table" consists of a 256x3xN matrix.
                 if you use multiple (more than 1) displays and set a 256x3x1 gamma-table, the same
                 table will be applied to all displays. if the number of displays and gamma tables
                 are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
                 gamma_table will be applied to the second and third displays.
                 if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
 overwrite_flg : (optional) whether overwriting pre-existing result file. if 1, the previous result
                 file with the same acquisition number will be overwritten by the previous one.
                 if 0, the existing file will be backed-up by adding a prefix '_old' at the tail
                 of the file. 0 by default.
 force_proceed_flag : (optional) whether proceeding stimulus presentatin without waiting for
                 the experimenter response (e.g. presesing the ENTER key) or a trigger.
                 if 1, the stimulus presentation will be automatically carried on.
 !!! NOTICE !!!!
 displayfile & stimulusfile should be located at
 ./subjects/(subjID)/
 as ./subjects/(subjID)/*_display_fmri.m
    ./subjects/(subjID)/*_stimuli.m
 [output variables]
 no output matlab variable.
 [output files]
 1. result file
    stored ./subjects/(subjID)/results/(date)
    as ./subjects/(subjID)/results/(date)/(subjID)_cmultifocal_results_run_(run_num).mat
 [example]
 >> cmultifocal('HB','ccw',1,'ret_display.m','ret_checker_stimulus_exp1.m')
 [About displayfile]
 The contents of the displayfile are as below.
 (The file includs 6 lines of headers and following display parameters)
 (an example of the displayfile)
 % ************************************************************
 % This is the display configuration file for the retinotopy stimuli
 % Programmed by Hiroshi Ban Nov 01 2013
 % ************************************************************
 % display mode, one of "mono", "dual", "dualcross", "dualparallel", "cross", "parallel", "redgreen", "greenred",
 % "redblue", "bluered", "shutter", "topbottom", "bottomtop", "interleavedline", "interleavedcolumn", "propixxmono", "propixxstereo"
 dparam.ExpMode='mono';
 dparam.scrID=1; % screen ID, generally 0 for a single display setup, 1 for dual display setup
 % a method to start stimulus presentation
 % 0:ENTER/SPACE, 1:Left-mouse button, 2:the first MR trigger pulse (CiNet),
 % 3:waiting for a MR trigger pulse (BUIC) -- checking onset of pin #11 of the parallel port,
 % or 4:custom key trigger (wait for a key input that you specify as tgt_key).
 dparam.start_method=2;
 % a pseudo trigger key from the MR scanner when it starts, valid only when dparam.start_method=4;
 dparam.custom_trigger='t';
 % keyboard settings
 dparam.Key1=51; % key 1 (left)
 dparam.Key2=52; % key 2 (right)
 % screen settings
 %%% whether displaying the stimuli in full-screen mode or
 %%% as is (the precise resolution), 'true' or 'false' (true)
 dparam.fullscr=false;
 %%% the resolution of the screen height
 dparam.ScrHeight=1200;
 %% the resolution of the screen width
 dparam.ScrWidth=1920;
 % whether forcing to use specific frame rate, if 0, the frame rate wil bw computed in the ImagesShowPTB function.
 % if non zero, the value is used as the screen frame rate.
 dparam.force_frame_rate=60;
 % whther skipping the PTB's vertical-sync signal test. if 1, the sync test is skipped
 dparam.skip_sync_test=0;
 [About stimulusfile]
 The contents of the stimulusfile are as below.
 (The file includs 6 lines of headers and following stimulus parameters)
 (an example of the stimulusfile)
 % ************************************************************
 % This is the stimulus parameter file for the multifocal retinotopy stimulus
 % Programmed by Hiroshi Ban Nov 29 2018
 % ************************************************************
 %%% stimulus parameters
 sparam.nwedges     = 36;   % number of wedge subdivisions along polar angle
 sparam.nrings      = 9;    % number of ring subdivisions along eccentricity angle
 sparam.width       = 360;  % wedge width in deg along polar angle
 sparam.ndivsP      = 12;   % number of visual field subdivisions along polar angle
 sparam.ndivsE      = 3;    % number of visual field subdivisions along eccentricity
 sparam.phase       = 0;    % phase shift in deg
 sparam.startangle  = 0;    % presentation start angle in deg, from right-horizontal meridian, ccw
 sparam.maxRad      = 6.0;  % maximum radius of  annulus (degrees)
 sparam.minRad      = 0;    % minumum
 sparam.dimratio    = 0.4; % luminance dim ratio for the checker-pattern change detection task
 sparam.colors      = [ 128, 128, 128; % number of colors for compensating flickering checkerboard
                        255,   0,   0; % the first row is background
                          0, 255,   0; % the second to end are patch colors
                        255, 255,   0;
                          0,   0, 255;
                        255,   0, 255;
                          0, 255, 255;
                        255, 255, 255;
                          0,   0,   0;
                        255, 128,   0;
                        128,   0, 255;];
 %%% generate stimulus presentation design
 % generating 0/1 sequence using m-sequence generation algorithm
 % ms=mseq(baseVal,powerVal,shift,whichSeq,balance_flag,user_taps).
 % here, shift and whichSeq should be set if you want to use a specific stimulus presentation order.
 % if these values are not set, shift=1 and whichSeq=ceil(rand(1)*length(tap)) are used as defult,
 % which means the different m-sequences are generated each time when the mseq() function is called.
 % or if you want to provide a specific stimulus presentation order, please set sparam.design as a
 % fixed matrix as below (sparam.design should be [ndivsE*ndivsP,numel(mseq(2,8))]).
 %
 % % sparam.design=[
 %     0,1,1,0,1,1,1,1,0,1,...;
 %     1,1,0,0,0,0,0,0,1,1,...;
 %     1,1,0,1,1,1,1,0,1,1,...];
 tmp_design=mseq(2,8,1,1); % to provide a specific stimulation order, the third and fourth variables are explicitly given.
 tmp_shift=[1:sparam.ndivsP*sparam.ndivsE];
 shift=zeros(numel(tmp_shift),1);
 shift_counter=1;
 while ~isempty(tmp_shift)
   if mod(shift_counter,2)
     shift(shift_counter)=tmp_shift(1);
     tmp_shift(1)=[];
   else
     shift(shift_counter)=tmp_shift(floor(numel(tmp_shift/2)));
     tmp_shift(floor(numel(tmp_shift/2)))=[];
   end
   shift_counter=shift_counter+1;
 end
 sparam.design=zeros(numel(shift),numel(tmp_design));
 for mmmm=1:1:numel(shift), sparam.design(mmmm,:)=tmp_design([shift(mmmm):end,1:shift(mmmm)-1]); end
 clear tmp_design tmp_shift shift shift_counter mmmm;
 %%% duration in msec for each trial
 sparam.trial_duration=2000; % msec
 sparam.rest_duration=0;
 sparam.numTrials=size(sparam.design,2);
 %%% set number of frames to flip the screen
 % Here, I set the number as large as I can to minimize vertical cynching error.
 % the final 2 is for 2 times repetitions of flicker
 % Set 1 if you want to flip the display at each vertical sync, but not recommended as it uses much CPU power
 %sparam.waitframes = Screen('FrameRate',0)*((sparam.trial_duration-sparam.rest_duration)/1000) / ( (size(sparam.colors,1)-1)*2 );
 sparam.waitframes = 60*((sparam.trial_duration-sparam.rest_duration)/1000) / ( (size(sparam.colors,1)-1)*2 );
 %sparam.waitframes = 1;
 %%% fixation period in msec before/after presenting the target stimuli, integer
 % must set a value more than 1 TR for initializing the frame counting.
 sparam.initial_fixation_time=[4000,4000];
 %%% fixation size & color
 sparam.fixtype=1; % 1: circular, 2: rectangular, 3: concentric fixation point
 sparam.fixsize=4; % radius in pixels
 sparam.fixcolor=[255,255,255];
 %%% background color
 sparam.bgcolor=sparam.colors(1,:); %[0,0,0];
 %%% background-patch colors (RGB)
 sparam.bgtype=1; % 1: a simple background with sparam.bgcolor (then, the parameters belows are not used), 2: a background with grid guides
 sparam.patch_size=[30,30]; % background patch size, [height,width] in pixels
 sparam.patch_num=[20,40];  % the number of background patches along vertical and horizontal axis
 sparam.patch_color1=[255,255,255];
 sparam.patch_color2=[0,0,0];
 %%% for converting degree to pixels
 run(fullfile(fileparts(mfilename('fullpath')),'sizeparams'));
 %sparam.pix_per_cm=57.1429;
 %sparam.vdist=65;
 [HOWTO create stimulus files]
 1. All of the stimuli are created in this script in real-time
    with MATLAB scripts & functions.
    see ../Generation & ../Common directries.
 2. Stimulus parameters are defined in the display & stimulus file.
 [reference]
 for stmulus generation, see ../Generation & ../Common directories.
CROSS-REFERENCE INFORMATION
This function calls:
BackUpObsoleteFiles Backups already-existing file(s) in the target directory by adding some file-prefix.
CheckPTBversion Checks the version of the currently running Psychtoolbox.
CreateBackgroundImage Creates background image that can be used as a background of your stimulus displays.
CreateFixationImgCircular Creates a circular fixation image for a monocular display setting.
CreateFixationImgConcentrateMono Creates a circular fixation image for a monocular display setting.
CreateFixationImgMono Creates a cross-shaped fixation image for a monocular display setting.
DisplayMessage2 Displays message on the center of each of multiple PTB windows.
DrawTextureWithCLUT Draws a texture with Color LookupTable you specified (modified version of Screen('DrawTexture')).
GammaLoadPTB Loads and sets display gamma-table(s) using PTB Screen() function.
GammaResetPTB Resets display gamma with PTB Screen() function.
InitializePTBDisplays Initializes PTB screen(s) for monocular/binocular presentations using PsychImaging() function.
InitializeRandomSeed Initializes MATLAB internal state of a random seed.
ValidateStructureFields Validates the input structure and set the default values to the missing field(s)
eventlogger
isstructmember Checks whether the target struct contains a filed you specified as a member.
mseq Generates maximum-length sequence(s).
responselogger
shift Shifts 2D matrix circularly.
shuffle Randomly sorts the input array.
DrawTextureWithCLUT Draws a texture with Color LookupTable you specified (modified version of Screen('DrawTexture')).
mf_GenerateCheckerBoard1D Generates multi-focal checkerboard patterns (polar angle-based subdivision) with an individual ID number on each patch.
This function is called by:
SOURCE CODE
function cmultifocal(subjID,exp_mode,acq,displayfile,stimulusfile,gamma_table,overwrite_flg,force_proceed_flag)
% Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
% function cmultifocal(subjID,exp_mode,acq,:displayfile,:stimulusfile,:gamma_table,:overwrite_flg,:force_proceed_flag)
% (: is optional)
%
% - This function generates and presents color/luminance-defined multi-focal checkerboard
%   stimulus for indentifying retinotopic visual areas and their visual field representations
%   based on the standard multi-focal retinotopy analysis.
%
%   reference: Multifocal fMRI mapping of visual cortical areas.
%              Vanni, S., Henriksson, L., James, A.C. (2005). Neuroimage, 27(1), 95-105.
%
% - This script shoud be used with MATLAB Psychtoolbox version 3 or above.
%
% - Luminance detection task: one of the checks of the checkerboard pattern
%   randomly turns to darker. An observer has to press the button if s/he
%   detects this luminance change. Response keys are defined in displayfile.
%
% [note]
% Behavioral task of (function_name)_fixtask is to detect changes of luminance
% of the central fixation point, while the task in (function_name) is to detect
% changes of luminance of one of the patches in the checkerboard stimuli.
% Here, the central fixation task is more easy to sustain the stable fixation
% on the center of the screen and may be suitable for naive/non-expert
% participants with minimizing unwilling eye movements. However, some studies
% have reported that attention to the target stimulus (checker-patch luminance
% change detection task) is required to get reliable retinotopic representations
% in higher-order visual areas.
%
% [*** IMPORTANT NOTE ***]
% The multi-focal checkerboard patterns are randomly generated based on mseq() function.
% To analyze the fMRI/MEG time series for specific patterns, please load result files,
% ./subjects/(subjID)/results/(date)/(subjID)_cmultifocal_results_run_(run_num).mat.
% In these files, "sparam.design", "checkerboard" and "checkerboardID" variables are stored,
% which are exactly the checkerboard patterns used in the sessions.
% By putting the variables into the gen_multifocal_windows() function, you can generate
% the stimulus windows across time
% Or by using sparam.deisgn, you can generate stimulus presentation protocol for GLM analysis.
%
%
% Created    : "2018-11-29 12:13:43 ban"
% Last Update: "2021-06-07 17:22:40 ban"
%
%
%
% [input variables]
% sujID         : ID of subject, string, such as 's01'
%                 you also need to create a directory ./subjects/(subj) and put displayfile and stimulusfile there.
%                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
%                 !!! if 'debug' (case insensitive) is included          !!!
%                 !!! in subjID string, this program runs as DEBUG mode; !!!
%                 !!! stimulus images are saved as *.png format at       !!!
%                 !!! ~/Retinotopy/Presentation/images                   !!!
%                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
%
% exp_mode      : experiment mode acceptable in this script is only "multifocal"
% acq           : acquisition number (design file number),
%                 an integer, such as 1, 2, 3, ...
% displayfile   : (optional) display condition file,
%                 *.m file, such as 'RetDepth_display_fmri.m'
%                 the file should be located in ./subjects/(subj)/
% stimulusfile  : (optional) stimulus condition file,
%                 *.m file, such as 'RetDepth_stimulus_exp1.m'
%                 the file should be located in ./subjects/(subj)/
% gamma_table   : (optional) table(s) of gamma-corrected video input values (Color LookupTable).
%                 256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
%                 or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
%                 The *.mat should include a variable named "gamma_table" consists of a 256x3xN matrix.
%                 if you use multiple (more than 1) displays and set a 256x3x1 gamma-table, the same
%                 table will be applied to all displays. if the number of displays and gamma tables
%                 are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
%                 gamma_table will be applied to the second and third displays.
%                 if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
% overwrite_flg : (optional) whether overwriting pre-existing result file. if 1, the previous result
%                 file with the same acquisition number will be overwritten by the previous one.
%                 if 0, the existing file will be backed-up by adding a prefix '_old' at the tail
%                 of the file. 0 by default.
% force_proceed_flag : (optional) whether proceeding stimulus presentatin without waiting for
%                 the experimenter response (e.g. presesing the ENTER key) or a trigger.
%                 if 1, the stimulus presentation will be automatically carried on.
%
% !!! NOTICE !!!!
% displayfile & stimulusfile should be located at
% ./subjects/(subjID)/
% as ./subjects/(subjID)/*_display_fmri.m
%    ./subjects/(subjID)/*_stimuli.m
%
%
% [output variables]
% no output matlab variable.
%
%
% [output files]
% 1. result file
%    stored ./subjects/(subjID)/results/(date)
%    as ./subjects/(subjID)/results/(date)/(subjID)_cmultifocal_results_run_(run_num).mat
%
%
% [example]
% >> cmultifocal('HB','ccw',1,'ret_display.m','ret_checker_stimulus_exp1.m')
%
% [About displayfile]
% The contents of the displayfile are as below.
% (The file includs 6 lines of headers and following display parameters)
%
% (an example of the displayfile)
%
% % ************************************************************
% % This is the display configuration file for the retinotopy stimuli
% % Programmed by Hiroshi Ban Nov 01 2013
% % ************************************************************
%
% % display mode, one of "mono", "dual", "dualcross", "dualparallel", "cross", "parallel", "redgreen", "greenred",
% % "redblue", "bluered", "shutter", "topbottom", "bottomtop", "interleavedline", "interleavedcolumn", "propixxmono", "propixxstereo"
% dparam.ExpMode='mono';
%
% dparam.scrID=1; % screen ID, generally 0 for a single display setup, 1 for dual display setup
%
% % a method to start stimulus presentation
% % 0:ENTER/SPACE, 1:Left-mouse button, 2:the first MR trigger pulse (CiNet),
% % 3:waiting for a MR trigger pulse (BUIC) -- checking onset of pin #11 of the parallel port,
% % or 4:custom key trigger (wait for a key input that you specify as tgt_key).
% dparam.start_method=2;
%
% % a pseudo trigger key from the MR scanner when it starts, valid only when dparam.start_method=4;
% dparam.custom_trigger='t';
%
% % keyboard settings
% dparam.Key1=51; % key 1 (left)
% dparam.Key2=52; % key 2 (right)
%
% % screen settings
%
% %%% whether displaying the stimuli in full-screen mode or
% %%% as is (the precise resolution), 'true' or 'false' (true)
% dparam.fullscr=false;
%
% %%% the resolution of the screen height
% dparam.ScrHeight=1200;
%
% %% the resolution of the screen width
% dparam.ScrWidth=1920;
%
% % whether forcing to use specific frame rate, if 0, the frame rate wil bw computed in the ImagesShowPTB function.
% % if non zero, the value is used as the screen frame rate.
% dparam.force_frame_rate=60;
%
% % whther skipping the PTB's vertical-sync signal test. if 1, the sync test is skipped
% dparam.skip_sync_test=0;
%
%
% [About stimulusfile]
% The contents of the stimulusfile are as below.
% (The file includs 6 lines of headers and following stimulus parameters)
%
% (an example of the stimulusfile)
%
% % ************************************************************
% % This is the stimulus parameter file for the multifocal retinotopy stimulus
% % Programmed by Hiroshi Ban Nov 29 2018
% % ************************************************************
%
% %%% stimulus parameters
% sparam.nwedges     = 36;   % number of wedge subdivisions along polar angle
% sparam.nrings      = 9;    % number of ring subdivisions along eccentricity angle
% sparam.width       = 360;  % wedge width in deg along polar angle
% sparam.ndivsP      = 12;   % number of visual field subdivisions along polar angle
% sparam.ndivsE      = 3;    % number of visual field subdivisions along eccentricity
% sparam.phase       = 0;    % phase shift in deg
% sparam.startangle  = 0;    % presentation start angle in deg, from right-horizontal meridian, ccw
%
% sparam.maxRad      = 6.0;  % maximum radius of  annulus (degrees)
% sparam.minRad      = 0;    % minumum
%
% sparam.dimratio    = 0.4; % luminance dim ratio for the checker-pattern change detection task
%
% sparam.colors      = [ 128, 128, 128; % number of colors for compensating flickering checkerboard
%                        255,   0,   0; % the first row is background
%                          0, 255,   0; % the second to end are patch colors
%                        255, 255,   0;
%                          0,   0, 255;
%                        255,   0, 255;
%                          0, 255, 255;
%                        255, 255, 255;
%                          0,   0,   0;
%                        255, 128,   0;
%                        128,   0, 255;];
%
% %%% generate stimulus presentation design
%
% % generating 0/1 sequence using m-sequence generation algorithm
% % ms=mseq(baseVal,powerVal,shift,whichSeq,balance_flag,user_taps).
% % here, shift and whichSeq should be set if you want to use a specific stimulus presentation order.
% % if these values are not set, shift=1 and whichSeq=ceil(rand(1)*length(tap)) are used as defult,
% % which means the different m-sequences are generated each time when the mseq() function is called.
% % or if you want to provide a specific stimulus presentation order, please set sparam.design as a
% % fixed matrix as below (sparam.design should be [ndivsE*ndivsP,numel(mseq(2,8))]).
% %
% % % sparam.design=[
% %     0,1,1,0,1,1,1,1,0,1,...;
% %     1,1,0,0,0,0,0,0,1,1,...;
% %     1,1,0,1,1,1,1,0,1,1,...];
%
% tmp_design=mseq(2,8,1,1); % to provide a specific stimulation order, the third and fourth variables are explicitly given.
% tmp_shift=[1:sparam.ndivsP*sparam.ndivsE];
% shift=zeros(numel(tmp_shift),1);
% shift_counter=1;
% while ~isempty(tmp_shift)
%   if mod(shift_counter,2)
%     shift(shift_counter)=tmp_shift(1);
%     tmp_shift(1)=[];
%   else
%     shift(shift_counter)=tmp_shift(floor(numel(tmp_shift/2)));
%     tmp_shift(floor(numel(tmp_shift/2)))=[];
%   end
%   shift_counter=shift_counter+1;
% end
%
% sparam.design=zeros(numel(shift),numel(tmp_design));
% for mmmm=1:1:numel(shift), sparam.design(mmmm,:)=tmp_design([shift(mmmm):end,1:shift(mmmm)-1]); end
%
% clear tmp_design tmp_shift shift shift_counter mmmm;
%
% %%% duration in msec for each trial
% sparam.trial_duration=2000; % msec
% sparam.rest_duration=0;
%
% sparam.numTrials=size(sparam.design,2);
%
% %%% set number of frames to flip the screen
% % Here, I set the number as large as I can to minimize vertical cynching error.
% % the final 2 is for 2 times repetitions of flicker
% % Set 1 if you want to flip the display at each vertical sync, but not recommended as it uses much CPU power
% %sparam.waitframes = Screen('FrameRate',0)*((sparam.trial_duration-sparam.rest_duration)/1000) / ((size(sparam.colors,1)-1)*2);
% sparam.waitframes = 60*((sparam.trial_duration-sparam.rest_duration)/1000) / ((size(sparam.colors,1)-1)*2);
% %sparam.waitframes = 1;
%
% %%% fixation period in msec before/after presenting the target stimuli, integer
% % must set a value more than 1 TR for initializing the frame counting.
% sparam.initial_fixation_time=[4000,4000];
%
% %%% fixation size & color
% sparam.fixtype=1; % 1: circular, 2: rectangular, 3: concentric fixation point
% sparam.fixsize=4; % radius in pixels
% sparam.fixcolor=[255,255,255];
%
% %%% background color
% sparam.bgcolor=sparam.colors(1,:); %[0,0,0];
%
% %%% background-patch colors (RGB)
% sparam.bgtype=1; % 1: a simple background with sparam.bgcolor (then, the parameters belows are not used), 2: a background with grid guides
% sparam.patch_size=[30,30]; % background patch size, [height,width] in pixels
% sparam.patch_num=[20,40];  % the number of background patches along vertical and horizontal axis
% sparam.patch_color1=[255,255,255];
% sparam.patch_color2=[0,0,0];
%
% %%% for converting degree to pixels
% run(fullfile(fileparts(mfilename('fullpath')),'sizeparams'));
% %sparam.pix_per_cm=57.1429;
% %sparam.vdist=65;
%
%
% [HOWTO create stimulus files]
% 1. All of the stimuli are created in this script in real-time
%    with MATLAB scripts & functions.
%    see ../Generation & ../Common directries.
% 2. Stimulus parameters are defined in the display & stimulus file.
%
%
% [reference]
% for stmulus generation, see ../Generation & ../Common directories.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Check the input variables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear global; clear mex;
if nargin<3, help(mfilename()); return; end
if nargin<4 || isempty(displayfile), displayfile=[]; end
if nargin<5 || isempty(stimulusfile), stimulusfile=[]; end
if nargin<6 || isempty(gamma_table), gamma_table=[]; end
if nargin<7 || isempty(overwrite_flg), overwrite_flg=1; end
if nargin<8 || isempty(force_proceed_flag), force_proceed_flag=0; end
% check the aqcuisition number
if acq<1, error('Acquistion number must be integer and greater than zero'); end
% check the experiment mode (stimulus type)
if ~strcmpi(exp_mode,'multifocal'), error('exp_mode acceptable in this script is only "multifocal". check the input variable.'); end
rootDir=fileparts(mfilename('fullpath'));
% check the subject directory
if ~exist(fullfile(rootDir,'subjects',subjID),'dir'), error('can not find subj directory. check the input variable.'); end
% check the display/stimulus files
if ~isempty(displayfile)
  if ~strcmpi(displayfile(end-1:end),'.m'), displayfile=[displayfile,'.m']; end
  if ~exist(fullfile(rootDir,'subjects',subjID,displayfile),'file'), error('displayfile not found. check the input variable.'); end
end
if ~isempty(stimulusfile)
  if ~strcmpi(stimulusfile(end-1:end),'.m'), stimulusfile=[stimulusfile,'.m']; end
  if ~exist(fullfile(rootDir,'subjects',subjID,stimulusfile),'file'), error('stimulusfile not found. check the input variable.'); end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Add path to the subfunctions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% add paths to the subfunctions
addpath(genpath(fullfile(rootDir,'..','Common')));
addpath(fullfile(rootDir,'..','Generation'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% For log file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% get date
today=datestr(now,'yymmdd');
% result directry & file
resultDir=fullfile(rootDir,'subjects',num2str(subjID),'results',today);
if ~exist(resultDir,'dir'), mkdir(resultDir); end
% record the output window
logfname=fullfile(resultDir,[num2str(subjID),'_cmultifocal_results_run_',num2str(acq,'%02d'),'.log']);
diary(logfname);
warning off; %#ok warning('off','MATLAB:dispatcher:InexactCaseMatch');
%%%%% try & catch %%%%%
try
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Check the PTB version
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PTB_OK=CheckPTBversion(3); % check wether the PTB version is 3
if ~PTB_OK, error('Wrong version of Psychtoolbox is running. %s requires PTB ver.3',mfilename()); end
% debug level, black screen during calibration
Screen('Preference', 'VisualDebuglevel', 3);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setup random seed
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
InitializeRandomSeed();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Reset display Gamma-function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(gamma_table)
  gamma_table=repmat(linspace(0.0,1.0,256),3,1); %#ok
  GammaResetPTB(1.0);
else
  GammaLoadPTB(gamma_table);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Validate dparam (displayfile) and sparam (stimulusfile) structures
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% organize dparam
dparam=struct(); % initialize
if ~isempty(displayfile), run(fullfile(rootDir,'subjects',subjID,displayfile)); end % load specific dparam parameters configured for each of the participants
dparam=ValidateStructureFields(dparam,... % validate fields and set the default values to missing field(s)
         'ExpMode','mono',...
         'scrID',1,...
         'start_method',0,...
         'custom_trigger','t',...
         'Key1',51,...
         'Key2',52,...
         'fullscr',false,...
         'ScrHeight',1200,...
         'ScrWidth',1920,...
         'force_frame_rate',60,...
         'skip_sync_test',0);
% organize sparam
sparam=struct(); % initialize
sparam.mode=exp_mode;
if ~isempty(stimulusfile), run(fullfile(rootDir,'subjects',subjID,stimulusfile)); end % load specific sparam parameters configured for each of the participants
sparam=ValidateStructureFields(sparam,... % validate fields and set the default values to missing field(s)
         'nwedges',36,...
         'nrings',9,...
         'width',360,...
         'ndivsP',12,...
         'ndivsE',3,...
         'phase',0,...
         'startangle',0,...
         'maxRad',8,...
         'minRad',0,...
         'dimratio',0.4,...
         'colors',[ 128, 128, 128;
                    255,   0,   0;
                      0, 255,   0;
                    255, 255,   0;
                      0,   0, 255;
                    255,   0, 255;
                      0, 255, 255;
                    255, 255, 255;
                      0,   0,   0;
                    255, 128,   0;
                    128,   0, 255],...
         'trial_duration',2000,...
         'rest_duration',0,...
         'numTrials',255,...
         'waitframes',6,... % Screen('FrameRate',0)*((sparam.trial_duration-sparam.rest_duration)/1000) / ( (size(sparam.colors,1)-1)*2 );
         'initial_fixation_time',[4000,4000],...
         'fixtype',1,...
         'fixsize',12,...
         'fixcolor',[255,255,255],...
         'bgcolor',[128,128,128],... % sparam.colors(1,:);
         'bgtype',1,...
         'patch_size',[30,30],...
         'patch_num',[20,40],...
         'patch_color1',[255,255,255],...
         'patch_color2',[0,0,0],...
         'pix_per_cm',57.1429,...
         'vdist',65);
% set the stimulus presentation design based on M-sequences
if ~isstructmember(sparam,'design') || isempty(sparam.design)
  tmp_design=mseq(2,8,1,1); % to provide a specific stimulation order, the third and fourth variables are explicitly given.
  tmp_shift=[1:sparam.ndivsP*sparam.ndivsE];
  shift=zeros(numel(tmp_shift),1);
  shift_counter=1;
  while ~isempty(tmp_shift)
    if mod(shift_counter,2)
      shift(shift_counter)=tmp_shift(1);
      tmp_shift(1)=[];
    else
      shift(shift_counter)=tmp_shift(floor(numel(tmp_shift/2)));
      tmp_shift(floor(numel(tmp_shift/2)))=[];
    end
    shift_counter=shift_counter+1;
  end
  sparam.design=zeros(numel(shift),numel(tmp_design));
  for mmmm=1:1:numel(shift), sparam.design(mmmm,:)=tmp_design([shift(mmmm):end,1:shift(mmmm)-1]); end
  sparam.numTrials=size(sparam.design,2);
  clear tmp_design tmp_shift shift shift_counter mmmm;
end
% change unit from msec to sec.
sparam.initial_fixation_time=sparam.initial_fixation_time./1000; %#ok
% change unit from msec to sec.
sparam.trial_duration = sparam.trial_duration./1000;
sparam.rest_duration  = sparam.rest_duration./1000;
% set the other parameters
dparam.RunScript = mfilename();
sparam.RunScript = mfilename();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying the presentation parameters you set
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('The Presentation Parameters are as below.\n\n');
fprintf('************************************************\n');
fprintf('****** Script, Subject, Acquistion Number ******\n');
fprintf('Date & Time            : %s\n',strcat([datestr(now,'yymmdd'),' ',datestr(now,'HH:mm:ss')]));
fprintf('Running Script Name    : %s\n',mfilename());
fprintf('Subject ID             : %s\n',subjID);
fprintf('Acquisition Number     : %d\n',acq);
fprintf('********* Run Type, Display Image Type *********\n');
fprintf('Display Mode           : %s\n',dparam.ExpMode);
fprintf('use Full Screen Mode   : %d\n',dparam.fullscr);
fprintf('Start Method           : %d\n',dparam.start_method);
if dparam.start_method==4
  fprintf('Custom Trigger         : %d\n',dparam.custom_trigger);
end
fprintf('*************** Screen Settings ****************\n');
fprintf('Screen Height          : %d\n',dparam.ScrHeight);
fprintf('Screen Width           : %d\n',dparam.ScrWidth);
fprintf('*********** Stimulation Periods etc. ***********\n');
fprintf('Fixation Time(sec)     : %d & %d\n',sparam.initial_fixation_time(1),sparam.initial_fixation_time(2));
fprintf('Trial Duration(sec)    : %d\n',sparam.trial_duration);
fprintf('Rest  Duration(sec)    : %d\n',sparam.rest_duration);
fprintf('#Trials                : %d\n',sparam.numTrials);
fprintf('Frame Flip(per VerSync): %d\n',sparam.waitframes);
fprintf('Total Time (sec)       : %d\n',sum(sparam.initial_fixation_time)+sparam.numTrials*sparam.trial_duration);
fprintf('**************** Stimulus Type *****************\n');
fprintf('Experiment Mode        : %s\n',sparam.mode);
fprintf('************ Response key settings *************\n');
fprintf('Reponse Key #1         : %d = %s\n',dparam.Key1,KbName(dparam.Key1));
fprintf('Reponse Key #2         : %d = %s\n',dparam.Key2,KbName(dparam.Key2));
fprintf('************************************************\n\n');
fprintf('Please carefully check before proceeding.\n\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialize response & event logger objects
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialize MATLAB objects for event and response logs
event=eventlogger();
resps=responselogger([dparam.Key1,dparam.Key2]);
resps.initialize(event); % initialize responselogger
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Wait for user reponse to start
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~force_proceed_flag
  [user_answer,resps]=resps.wait_to_proceed();
  if ~user_answer, diary off; return; end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialization of Left & Right screens for binocular presenting/viewing mode
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dparam.skip_sync_test, Screen('Preference','SkipSyncTests',1); end
[winPtr,winRect,nScr,dparam.fps,dparam.ifi,initDisplay_OK]=InitializePTBDisplays(dparam.ExpMode,sparam.bgcolor,0,[],dparam.scrID);
if ~initDisplay_OK, error('Display initialization error. Please check your exp_run parameter.'); end
HideCursor();
if isstructmember(dparam,'force_frame_rate')
  if dparam.force_frame_rate
    dparam.fps=dparam.force_frame_rate;
    dparam.ifi=1/dparam.fps;
  end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setting the PTB runnning priority to MAX
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% set the priority of this script to MAX
priorityLevel=MaxPriority(winPtr,'WaitBlanking');
Priority(priorityLevel);
% conserve VRAM memory: Workaround for flawed hardware and drivers
% 32 == kPsychDontShareContextRessources: Do not share ressources between
% different onscreen windows. Usually you want PTB to share all ressources
% like offscreen windows, textures and GLSL shaders among all open onscreen
% windows. If that causes trouble for some weird reason, you can prevent
% automatic sharing with this flag.
%Screen('Preference','ConserveVRAM',32);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setting the PTB OpenGL functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Enable OpenGL mode of Psychtoolbox: This is crucially needed for clut animation
InitializeMatlabOpenGL();
% This script calls Psychtoolbox commands available only in OpenGL-based
% versions of the Psychtoolbox. (So far, the OS X Psychtoolbox is the
% only OpenGL-base Psychtoolbox.)  The Psychtoolbox command AssertPsychOpenGL will issue
% an error message if someone tries to execute this script on a computer without
% an OpenGL Psychtoolbox
AssertOpenGL();
% set OpenGL blend functions
Screen('BlendFunction', winPtr, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing MATLAB OpenGL shader API
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% just call DrawTextureWithCLUT with window pointer alone
DrawTextureWithCLUT(winPtr);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying 'Initializing...'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% displaying texts on the center of the screen
DisplayMessage2('Initializing...',sparam.bgcolor,winPtr,nScr,'Arial',36);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing variables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% unit conversion
% cm per pix
sparam.cm_per_pix=1/sparam.pix_per_cm;
% pixles per degree
sparam.pix_per_deg=round(1/(180*atan(sparam.cm_per_pix/sparam.vdist)/pi));
% deg to radian
% do not convert!
% sparam.width, sparam.phase, sparam.startangle, sparam.rotangle are used in deg formats
% number of checkerboard color
sparam.ncolors=(size(sparam.colors,1)-1)/2;
% sec to number of frames
nframe_fixation=round(sparam.initial_fixation_time.*dparam.fps./sparam.waitframes);
nframe_stim=round((sparam.trial_duration-sparam.rest_duration)*dparam.fps/sparam.waitframes);
nframe_rest=round(sparam.rest_duration*dparam.fps/sparam.waitframes);
nframe_flicker=round(nframe_stim/sparam.ncolors/4);
nframe_task=round(nframe_stim/2);
%% initialize chackerboard parameters
% adjust size ratio considering full-screen effect
if dparam.fullscr
  % here, use width information alone, assuming that the pixel is square
  ratio_wid=( winRect(3)-winRect(1) )/dparam.ScrWidth;
  %ratio_hei=( winRect(4)-winRect(2) )/dparam.ScrHeight;
  % min/max radius of annulus
  rmin=sparam.minRad*ratio_wid; % !!! degree, not pixel or cm !!!
  rmax=sparam.maxRad*ratio_wid;
else
  rmin=sparam.minRad;
  rmax=sparam.maxRad;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Generating checkerboard patterns
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% [note]
% After this processing, each checkerboard image has checker elements with values as shown below
% 0 = background
% 1 = checker ID 1
% 2 = checker ID 2
% 3 = checker ID 3
% .....
% sparam.npatches = checker ID
% Each patch ID will be associated with a CLUT color of the same ID
% generate the base of the multifocal checkerboard
[checkerboardID_base,bincheckerboard,mfcheckerboard]=mf_GenerateCheckerBoard1D(rmin,rmax,sparam.width,sparam.ndivsP,sparam.ndivsE,...
                                                     sparam.startangle,sparam.pix_per_deg,sparam.nwedges,sparam.nrings,sparam.phase);
% generate all the multifocal checkerboards
checkerboard=cell(sparam.numTrials,1);
checkerboardID=cell(sparam.numTrials,1);
for cc=1:1:sparam.numTrials
  cmask=zeros(size(mfcheckerboard));
  mask_idx=find(sparam.design(:,cc)==1);
  for mm=1:1:numel(mask_idx), cmask(mfcheckerboard==mask_idx(mm))=1; end
  checkerboard{cc}=bincheckerboard.*cmask;
  checkerboardID{cc}=checkerboardID_base.*cmask;
end
clear cmask mask_idx checkerboardID_base bincheckerboard mfcheckerboard;
%% update number of patches and number of wedges, taking into an account of checkerboard phase shift
% here, all parameters are generated for each checkerboard
% This looks circuitous, duplicating procedures, and it consumes more CPU and memory.
% 'if' statements may be better.
% However, to decrease the number of 'if' statement after starting stimulus
% presentation as possible as I can, I will do adopt this circuitous procedures.
patchids=cell(sparam.numTrials,1);
% in the bar presentation, the number of patches/wedges are different over time
% because a part of the bar can be occluded by the circular aperture mask.
% therefore, we have to re-compute the patches and the corresponding IDs here.
for cc=1:1:sparam.numTrials
  patchids{cc}=unique(checkerboardID{cc})';
  patchids{cc}=patchids{cc}(2:end); % omit background id
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing Color Lookup-Table (CLUT)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% [note]
% all checker color/luminance flickering is realized by just flipping CLUT generated here
% to save memory and CPU power
CLUT=cell(sparam.ncolors,2); % 2 is for compensating patterns
% generate base CLUT
for cc=1:1:sparam.ncolors
  for pp=1:1:2 % compensating checkers
    % initialize, DrawTextureWithCLUT requires [256x4] color lookup table even when we do not use whole 256 colors
    % though DrawTextureWithCLUT does not support alpha transparency up to now...
    CLUT{cc,pp}=zeros(256,4);
    CLUT{cc,pp}(:,4)=1; % default alpha is 1 (no transparent)
    CLUT{cc,pp}(1,:)=[sparam.colors(1,:),0]; % background LUT, default alpha is 0 (invisible);
    if ~mod(pp,2)
      CLUT{cc,pp}(2,1:3)=sparam.colors(2*cc,:);
      CLUT{cc,pp}(3,1:3)=sparam.colors(2*cc+1,:);
      CLUT{cc,pp}(4,1:3)=sparam.dimratio.*sparam.colors(2*cc,:);
      CLUT{cc,pp}(5,1:3)=sparam.dimratio.*sparam.colors(2*cc+1,:);
    else
      CLUT{cc,pp}(2,1:3)=sparam.colors(2*cc+1,:);
      CLUT{cc,pp}(3,1:3)=sparam.colors(2*cc,:);
      CLUT{cc,pp}(4,1:3)=sparam.dimratio.*sparam.colors(2*cc+1,:);
      CLUT{cc,pp}(5,1:3)=sparam.dimratio.*sparam.colors(2*cc,:);
    end
  end % for pp=1:1:2 % compensating checkers
end % for cc=1:1:sparam.ncolors
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Debug codes
%%%% saving the stimulus images as *.png format files and enter the debug (keyboard) mode
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %%%%%% DEBUG codes start here
% note: debug stimuli have no jitters of binocular disparity
if strfind(upper(subjID),'DEBUG')
  % just to get stimulus figures
  Screen('CloseAll');
  save_dir=fullfile(resultDir,'images_cmultifocal');
  if ~exist(save_dir,'dir'), mkdir(save_dir); end
  figure; hold off;
  for nn=1:1:sparam.numTrials
    imagesc(checkerboard{nn}+1,[1,numel(unique(checkerboard{nn}))]);
    axis off; axis equal;
    for cc=1:1:sparam.ncolors
      for pp=1:1:2 % compensating checkers
        colormap(CLUT{cc,pp}(1:3,1:3)./255);
        drawnow;
        pause(0.05);
        imwrite(checkerboard{nn}+1,CLUT{cc,pp}(1:3,1:3)./255,fullfile(save_dir,sprintf('checkerboard_%s_pos_%02d_lut_%02d_%02d.png',sparam.mode,nn,cc,pp)),'png'); % +1 is required as the image index is assumed to be started from 1.
      end
    end
  end
  close all;
  save(fullfile(save_dir,sprintf('stimulus_%s.mat',sparam.mode)),'checkerboard','sparam','dparam','CLUT');
  keyboard;
end % if strfind(upper(subjID),'DEBUG')
% %%%%%% DEBUG code ends here
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Generating contrast detection task parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% set task variables
% flag to decide in which period (first half or second half) the disparity task is applied
% about task_flg:
% 1, task is added in the first half period
% 2, task is added in the second half period
task_flg=randi(2,[ceil(sparam.numTrials*nframe_stim/nframe_task),1]);
% flag whether presenting disparity task
do_task=zeros(ceil(sparam.numTrials*nframe_stim/nframe_task),1);
do_task(1)=0; % no task for the first presentation
for ii=2:1:ceil(sparam.numTrials*nframe_stim/nframe_task)
  if do_task(ii-1)==1
    do_task(ii)=0;
  else
    do_task(ii)=round(rand(1,1));
  end
end
% variable to store the current task array order
task_id=1;
% variable to store task position
task_pos=cell(sparam.numTrials,1);
for cc=1:1:sparam.numTrials
  task_pos{cc}=zeros(1,ceil(sparam.numTrials*nframe_stim/nframe_task));
  for pp=1:1:ceil(sparam.numTrials*nframe_stim/nframe_task)
    tmp_id=shuffle(patchids{cc});
    task_pos{cc}(pp)=tmp_id(1);
  end
end
% flag to index the first task frame
firsttask_flg=0;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing checkerboard color management parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% checkerboard color id
color_id=1;
% checkerboard compensating color id
compensate_id=1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Creating background images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if sparam.bgtype==1 % a simple background with sparam.bgcolor
  bgimg{1}=repmat(reshape(sparam.colors(1,:),[1,1,3]),[dparam.ScrHeight,dparam.ScrWidth]);
elseif sparam.bgtype==2 % a background with grid guides
  % calculate the central aperture size of the background image
  edgeY=mod(dparam.ScrHeight,sparam.patch_num(1)); % delete the exceeded region
  p_height=round((dparam.ScrHeight-edgeY)/sparam.patch_num(1)); % height in pix of patch_height + interval-Y
  edgeX=mod(dparam.ScrWidth,sparam.patch_num(2)); % delete exceeded region
  p_width=round((dparam.ScrWidth-edgeX)/sparam.patch_num(2)); % width in pix of patch_width + interval-X
  if dparam.fullscr
    aperture_size=[2*( p_height*ceil( size(checkerboard{1},1)/2*( (winRect(4)-winRect(2))/dparam.ScrHeight ) /p_height ) ),...
                   2*( p_width*ceil( size(checkerboard{1},2)/2*( (winRect(3)-winRect(1))/dparam.ScrWidth ) /p_width ) )];
  else
    aperture_size=[2*( p_height*ceil(size(checkerboard{1},1)/2/p_height) ),...
                   2*( p_width*ceil(size(checkerboard{1},2)/2/p_width) )];
  end
  bgimg=CreateBackgroundImage([dparam.ScrHeight,dparam.ScrWidth],aperture_size,sparam.patch_size,sparam.bgcolor,sparam.patch_color1,sparam.patch_color2,sparam.fixcolor,sparam.patch_num,0,0,0);
else
  error('sparam.bgtype should be 1 or 2. check the input variable.');
end
background=Screen('MakeTexture',winPtr,bgimg{1});
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Creating the central fixation, cross images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create fixation cross images.
% Firstly larger fixations are generated, then they are antialiased. This is required to present a beautiful circle
if sparam.fixtype==1 % circular fixation
  fixW=CreateFixationImgCircular(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*sparam.fixsize,0,0);
  fixD=CreateFixationImgCircular(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*sparam.fixsize,0,0);
elseif sparam.fixtype==2 % rectangular fixation
  fixW=CreateFixationImgMono(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*2,4*ceil(0.4*sparam.fixsize),0,0);
  fixD=CreateFixationImgMono(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*2,4*ceil(0.4*sparam.fixsize),0,0);
elseif sparam.fixtype==3 % concentric fixation
  fixW=CreateFixationImgConcentrateMono(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*[2,ceil(0.8*sparam.fixsize)],0,0,0);
  fixD=CreateFixationImgConcentrateMono(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*[2,ceil(0.8*sparam.fixsize)],0,0,0);
else
  error('sparam.fixtype should be one of 1,2, and 3. check the input variable.');
end
fixW=imresize(fixW,0.25);
fixD=imresize(fixD,0.25);
fix=cell(2,1); % 1 is for default fixation, 2 is for darker fixation (luminance detection task)
fix{1}=Screen('MakeTexture',winPtr,fixW);
fix{2}=Screen('MakeTexture',winPtr,fixD);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Prepare blue lines for stereo image flip sync with VPixx PROPixx
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% There seems to be a blueline generation bug on some OpenGL systems.
% SetStereoBlueLineSyncParameters(winPtr, winRect(4)) corrects the
% bug on some systems, but breaks on other systems.
% We'll just disable automatic blueline, and manually draw our own bluelines!
if strcmpi(dparam.ExpMode,'propixxstereo')
  SetStereoBlueLineSyncParameters(winPtr, winRect(4)+10);
  blueRectOn(1,:)=[0, winRect(4)-1, winRect(3)/4, winRect(4)];
  blueRectOn(2,:)=[0, winRect(4)-1, winRect(3)*3/4, winRect(4)];
  blueRectOff(1,:)=[winRect(3)/4, winRect(4)-1, winRect(3), winRect(4)];
  blueRectOff(2,:)=[winRect(3)*3/4, winRect(4)-1, winRect(3), winRect(4)];
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Image size adjusting to match the current display resolutions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dparam.fullscr
  ratio_wid= ( winRect(3)-winRect(1) )/dparam.ScrWidth;
  ratio_hei= ( winRect(4)-winRect(2) )/dparam.ScrHeight;
  bgSize   = [size(bgimg{1},2)*ratio_wid, size(bgimg{1},1)*ratio_hei];
  stimSize = [size(checkerboard{1},2)*ratio_wid, size(checkerboard{1},1)*ratio_hei];
  fixSize  = [2*sparam.fixsize*ratio_wid, 2*sparam.fixsize*ratio_hei];
else
  bgSize   = [dparam.ScrWidth, dparam.ScrHeight];
  stimSize = [size(checkerboard{1},2), size(checkerboard{1},1)];
  fixSize  = [2*sparam.fixsize, 2*sparam.fixsize];
end
% for some display modes in which one screen is splitted into two binocular displays
if strcmpi(dparam.ExpMode,'cross') || strcmpi(dparam.ExpMode,'parallel') || ...
   strcmpi(dparam.ExpMode,'topbottom') || strcmpi(dparam.ExpMode,'bottomtop')
  bgSize=bgSize./2;
  stimSize=stimSize./2;
  fixSize=fixSize./2;
end
bgRect  = [0, 0, bgSize]; % used to display background images;
stimRect= [0, 0, stimSize];
fixRect = [0, 0, fixSize]; % used to display the central fixation point
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying 'Ready to Start'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% displaying texts on the center of the screen
DisplayMessage2('Ready to Start',sparam.bgcolor,winPtr,nScr,'Arial',36);
ttime=GetSecs(); while (GetSecs()-ttime < 0.5), end  % run up the clock.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Flip the display(s) to the background image(s)
%%%% and inform the ready of stimulus presentation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% change the screen and wait for the trigger or pressing the start button
for nn=1:1:nScr
  Screen('SelectStereoDrawBuffer',winPtr,nn-1);
  Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
  Screen('DrawTexture',winPtr,fix{2},[],CenterRect(fixRect,winRect));
  % blue line for stereo sync
  if strcmpi(dparam.ExpMode,'propixxstereo')
    Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
    Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
  end
end
Screen('DrawingFinished',winPtr);
Screen('Flip', winPtr,[],[],[],1);
% prepare the next frame for the initial fixation period
for nn=1:1:nScr
  Screen('SelectStereoDrawBuffer',winPtr,nn-1);
  Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
  Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect));
  % blue line for stereo sync
  if strcmpi(dparam.ExpMode,'propixxstereo')
    Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
    Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
  end
end
Screen('DrawingFinished',winPtr);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Wait for the first trigger pulse from fMRI scanner or start with button pressing
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% add time stamp (this also works to load add_event method in memory in advance of the actual displays)
fprintf('\nWaiting for the start...\n');
event=event.add_event('Experiment Start',strcat([datestr(now,'yymmdd'),' ',datestr(now,'HH:mm:ss')]),NaN);
% waiting for stimulus presentation
resps.wait_stimulus_presentation(dparam.start_method,dparam.custom_trigger);
%PlaySound(1);
fprintf('\nExperiment running...\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initial Fixation Period
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
vbl=Screen('Flip',winPtr,[],[],[],1); % the first flip
[event,the_experiment_start]=event.set_reference_time(vbl);
event=event.add_event('Initial Fixation',[]);
fprintf('\nfixation\n\n');
% wait for the initial fixation
for ff=1:1:nframe_fixation(1)
  for nn=1:1:nScr
    Screen('SelectStereoDrawBuffer',winPtr,nn-1);
    Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
    Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect));
    % blue line for stereo sync
    if strcmpi(dparam.ExpMode,'propixxstereo')
      Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
      Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
    end
  end
  Screen('DrawingFinished',winPtr);
  while GetSecs()<vbl+(ff*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
  Screen('Flip',winPtr,[],[],[],1);
1000 end
1001
1002
1003 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1004 %%%% The Trial Loop
1005 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1006
1007 for cc=1:1:sparam.numTrials
1008
1009   %% stimulus presentation loop
1010   for ff=1:1:nframe_stim+nframe_rest
1011
1012     % generate a checkerboard texture with/without a luminance detection task
1013     if ff<=nframe_stim
1014       if do_task(task_id) && ...
1015         ((task_flg(task_id)==1 && mod(ff,nframe_stim)<=nframe_stim/2) || ...
1016           (task_flg(task_id)==2 && mod(ff,nframe_stim)>nframe_stim/2))
1017         tidx=find(checkerboardID{cc}==task_pos{cc}(task_id));
1018         checkerboard{cc}(tidx)=checkerboard{cc}(tidx)+2; % here +2 is for a dim checker pattern. for details, please see codes in generating CLUT.
1019         checkertexture=Screen('MakeTexture',winPtr,checkerboard{cc});
1020         checkerboard{cc}(tidx)=checkerboard{cc}(tidx)-2; % put the checkerboard ID back to the default
1021       else
1022         tidx=[];
1023         checkertexture=Screen('MakeTexture',winPtr,checkerboard{cc});
1024       end
1025     end
1026
1027     %% display the current frame
1028     for nn=1:1:nScr
1029       Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1030       Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect)); % background
1031       if ff<=nframe_stim
1032         DrawTextureWithCLUT(winPtr,checkertexture,CLUT{color_id,compensate_id},[],CenterRect(stimRect,winRect)); % checkerboard
1033       end
1034       Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect)); % the central fixation oval
1035
1036       % blue line for stereo sync
1037       if strcmpi(dparam.ExpMode,'propixxstereo')
1038         Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1039         Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1040       end
1041     end
1042
1043     % flip the window
1044     Screen('DrawingFinished',winPtr);
1045     while GetSecs()<vbl+sparam.initial_fixation_time(1)+(cc-1)*sparam.trial_duration+((ff-1)*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1046     Screen('Flip',winPtr,[],[],[],1);
1047
1048     if ff==1
1049       event=event.add_event(sprintf('Trial: %d',cc),[]);
1050       if cc==1, fprintf('Trial: '); end
1051       if mod(cc,20)~=0 && cc~=sparam.numTrials, fprintf(sprintf('%03d, ',cc)); end
1052       if mod(cc,20)==0 || cc==sparam.numTrials, fprintf('%03d\n       ',cc); end
1053     end
1054
1055     if ff<=nframe_stim && firsttask_flg==1 && (do_task(task_id) && ...
1056        ((task_flg(task_id)==1 && mod(ff,nframe_stim)<=nframe_stim/2) || ...
1057          (task_flg(task_id)==2 && mod(ff,nframe_stim)>nframe_stim/2))), event=event.add_event('Luminance Task',[]); end
1058
1059     % clean up
1060     if ff<=nframe_stim, Screen('Close',checkertexture); end
1061
1062     %% exit from the loop if the final frame is displayed
1063     if ff==nframe_stim+nframe_rest && cc==sparam.numTrials, continue; end
1064
1065     %% update IDs
1066
1067     % flickering checkerboard
1068     if ff<=nframe_stim
1069       if ~mod(ff,nframe_flicker) % color reversal
1070         compensate_id=mod(compensate_id,2)+1;
1071       end
1072
1073       if ~mod(ff,2*nframe_flicker) % color change
1074         color_id=color_id+1;
1075         if color_id>sparam.ncolors, color_id=1; end
1076       end
1077
1078       %% update task. about task_flg: 1, task is added in the first half period. 2, task is added in the second half period
1079       if ~mod(ff,nframe_task), task_id=task_id+1; firsttask_flg=0; end
1080       firsttask_flg=firsttask_flg+1;
1081     else
1082       compensate_id=1;
1083       color_id=1;
1084       firsttask_flg=0;
1085     end
1086   end % for ff=1:1:nframe_stim+nframe_rest
1087
1088 end % for cc=1:1:sparam.numTrials
1089
1090
1091 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1092 %%%% Final Fixation
1093 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1094
1095 for nn=1:1:nScr
1096   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1097   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1098   Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect));
1099
1100   % blue line for stereo sync
1101   if strcmpi(dparam.ExpMode,'propixxstereo')
1102     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1103     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1104   end
1105 end
1106 Screen('DrawingFinished',winPtr);
1107 while GetSecs()<vbl+sparam.initial_fixation_time(1)+sparam.numTrials*sparam.trial_duration-0.5*dparam.ifi, [resps,event]=resps.check_responses(event); end
1108 Screen('Flip',winPtr,[],[],[],1);
1109 event=event.add_event('Final Fixation',[]);
1110 fprintf('\nfixation\n');
1111
1112 % wait for the initial fixation
1113 for ff=1:1:nframe_fixation(2)
1114   for nn=1:1:nScr
1115     Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1116     Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1117     Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect));
1118
1119     % blue line for stereo sync
1120     if strcmpi(dparam.ExpMode,'propixxstereo')
1121       Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1122       Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1123     end
1124   end
1125   Screen('DrawingFinished',winPtr);
1126   while GetSecs()<vbl+sparam.initial_fixation_time(1)+sparam.numTrials*sparam.trial_duration+(ff*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1127   Screen('Flip',winPtr,[],[],[],1);
1128 end
1129
1130 % the final clock up
1131 while GetSecs()-the_experiment_start<sum(sparam.initial_fixation_time)+sparam.numTrials*sparam.trial_duration
1132   [resps,event]=resps.check_responses(event);
1133 end
1134
1135
1136 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1137 %%%% Experiment & scanner end here
1138 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1139
1140 experimentDuration=GetSecs()-the_experiment_start;
1141 event=event.add_event('End',[]);
1142 fprintf('\n');
1143 fprintf('Experiment Completed: %.2f/%.2f secs\n',experimentDuration,...
1144         sum(sparam.initial_fixation_time)+sparam.numTrials*sparam.trial_duration);
1145 fprintf('\n');
1146
1147
1148 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1149 %%%% Cleaning up MATLAB OpenGL shader API
1150 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1151
1152 % just call DrawTextureWithCLUT without any input argument
1153 DrawTextureWithCLUT();
1154
1155
1156 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1157 %%%% Cleaning up the PTB screen
1158 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1159
1160 Screen('CloseAll');
1161
1162 % closing datapixx
1163 if strcmpi(dparam.ExpMode,'propixxmono') || strcmpi(dparam.ExpMode,'propixxstereo')
1164   if Datapixx('IsViewpixx3D')
1165     Datapixx('DisableVideoLcd3D60Hz');
1166     Datapixx('RegWr');
1167   end
1168   Datapixx('Close');
1169 end
1170
1171 ShowCursor();
1172 Priority(0);
1173 GammaResetPTB(1.0);
1174
1175
1176 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1177 %%%% Write data into file for post analysis
1178 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1179
1180 % saving the results
1181 fprintf('saving data...');
1182
1183 % save data
1184 savefname=fullfile(resultDir,[num2str(subjID),'_cmultifocal_results_run_',num2str(acq,'%02d'),'.mat']);
1185
1186 % backup the old file(s)
1187 if ~overwrite_flg
1188   BackUpObsoleteFiles(fullfile('subjects',num2str(subjID),'results',today),...
1189                       [num2str(subjID),'_cmultifocal_results_run_',num2str(acq,'%02d'),'.mat'],'_old');
1190 end
1191
1192 eval(sprintf('save %s subjID acq sparam dparam event gamma_table checkerboard checkerboardID;',savefname));
1193 fprintf('done.\n');
1194
1195 % calculate & display task performance
1196 fprintf('calculating task accuracy...\n');
1197 correct_event=cell(2,1); for ii=1:1:2, correct_event{ii}=sprintf('key%d',ii); end
1198 [task.numTasks,task.numHits,task.numErrors,task.numResponses,task.RT]=event.calc_accuracy(correct_event);
1199 event=event.get_event(); % convert an event logger object to a cell data structure
1200 eval(sprintf('save -append %s event task;',savefname));
1201 fprintf('done.\n');
1202
1203
1204 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1205 %%%% Removing path to the subfunctions, and finalizing the script
1206 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1207
1208 rmpath(genpath(fullfile(rootDir,'..','Common')));
1209 rmpath(fullfile(rootDir,'..','Generation'));
1210 clear all; clear mex; clear global;
1211 diary off;
1212
1213
1214 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1215 %%%% tell the experimenter that the measurements are completed
1216 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1217
1218 try
1219   for ii=1:1:3, Snd('Play',sin(2*pi*0.2*(0:900)),8000); end
1220 catch
1221   % do nothing
1222 end
1223
1224
1225 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1226 %%%% Catch the errors
1227 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1228
1229 catch lasterror
1230   % this "catch" section executes in case of an error in the "try" section
1231   % above.  Importantly, it closes the onscreen window if its open.
1232   Screen('CloseAll');
1233
1234   if exist('dparam','var')
1235     if isstructmember(dparam,'ExpMode')
1236       if strcmpi(dparam.ExpMode,'propixxmono') || strcmpi(dparam.ExpMode,'propixxstereo')
1237         if Datapixx('IsViewpixx3D')
1238           Datapixx('DisableVideoLcd3D60Hz');
1239           Datapixx('RegWr');
1240         end
1241         Datapixx('Close');
1242       end
1243     end
1244   end
1245
1246   ShowCursor();
1247   Priority(0);
1248   GammaResetPTB(1.0);
1249   tmp=lasterror; %#ok
1250   %if exist('event','var'), event=event.get_event(); end %#ok % just for debugging
1251   diary off;
1252   fprintf(['\nError detected and the program was terminated.\n',...
1253            'To check error(s), please type ''tmp''.\n',...
1254            'Please save the current variables now if you need.\n',...
1255            'Then, quit by ''dbquit''\n']);
1256   keyboard;
1257   rmpath(genpath(fullfile(rootDir,'..','Common')));
1258   rmpath(fullfile(rootDir,'..','Generation'));
1259   clear all; clear mex; clear global;
1260   return
1261 end % try..catch
1262
1263
1264 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1265 %%%%% That's it - we're done
1266 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1267 return;
1268 % end % function cmultifocal