Description of idual_fixtask
idual_fixtask
PURPOSE
Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SYNOPSIS
function idual_fixtask(subjID,exp_mode,acq,displayfile,stimulusfile,gamma_table,overwrite_flg,force_proceed_flag)
DESCRIPTION
 Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
 function idual_fixtask(subjID,exp_mode,acq,:displayfile,:stimulusfile,:gamma_table,:overwrite_flg,:force_proceed_flag)
 (: is optional)
 - This function generates and presents dual retinotopy stimulus (rotating wedge +
   expanding/contracting annulus) on which object images are randomly located with
   brownian noise images on its background.
   The stimulus can be used to measure cortical retinotopy and to delineate retinotopic
   borders using the standard phase-encoded or pRF (population receptive field) analysis techniques.
   references: 1. Population receptive field estimates in human visual cortex.
                  Dumoulin, S.O. and Wandell, B.A. (2008). Neuroimage, 39(2), 647-660.
               2. Borders of multiple visual areas in humans revealed by functional magnetic resonance imaging.
                  Sereno MI, Dale AM, Reppas JB, Kwong KK, Belliveau JW, Brady TJ, Rosen BR, Tootell RB. (1995).
                  Science 268(5212), 889-893.
               3. fMRI of human visual cortex.
                  Engel SA, Rumelhart DE, Wandell BA, Lee AT, Glover GH, Chichilnisky EJ, Shadlen MN. (1994).
                  Nature, 369(6481), 525.
               4. Visual field maps in human cortex.
                  Wandell BA, Dumoulin SO, Brewer AA. (2007). Neuron, 56(2), 366-383.
 - This script shoud be used with MATLAB Psychtoolbox version 3 or above.
 - Luminance detection task: the central fixation point (default: white)
   randomly turns to gray. An observer has to press the button if s/he
   detects this luminance change. Response keys are defined in displayfile.
 [about the object images used in this function]
 The object images used in this function (stored in ~/Retinotopy/object_images/ as object_image_database.mat) are
 obtained and modified from the databases publicly available from http://konklab.fas.harvard.edu/#
 I sincerely express my gratitude to the developers, distributors, and scientists in Dr Talia Konkle's research group
 for their contributions to these databases. When you use this function for your research, please cite the original
 papers listed below.
 - Tripartite Organization of the Ventral Stream by Animacy and Object Size.
   Konkle, T., & Caramazza, A. (2013). Journal of Neuroscience, 33 (25), 10235-42.
 - A real-world size organization of object responses in occipito-temporal cortex.
   Konkle. T., & Oliva, A. (2012). Neuron, 74(6), 1114-24.
 - Visual long-term memory has a massive storage capacity for object details.
   Brady, T. F., Konkle, T., Alvarez, G. A. & Oliva, A. (2008). Proceedings of the National Academy of Sciences USA, 105(38), 14325-9.
 - Conceptual distinctiveness supports detailed visual long-term memory.
   Konkle, T., Brady, T. F., Alvarez, G. A., & Oliva, A. (2010). Journal of Experimental Psychology: General, 139(3), 558-578.
 - A Familiar Size Stroop Effect: Real-world size is an automatic property of object representation.
   Konkle, T., & Oliva, A. (2012). Journal of Experimental Psychology: Human Perception & Performance, 38, 561-9.
 [note]
 Behavioral task of (function_name)_fixtask is to detect changes of luminance
 of the central fixation point, while the task in (function_name) is to detect
 changes of luminance of one of the patches in the checkerboard stimuli.
 Here, the central fixation task is more easy to sustain the stable fixation
 on the center of the screen and may be suitable for naive/non-expert
 participants with minimizing unwilling eye movements. However, some studies
 have reported that attention to the target stimulus (checker-patch luminance
 change detection task) is required to get reliable retinotopic representations
 in higher-order visual areas.
 Created    : "2018-12-20 14:26:03 ban"
 Last Update: "2021-06-07 17:18:34 ban"
 [input variables]
 sujID         : ID of subject, string, such as 's01'
                 you also need to create a directory ./subjects/(subj) and put displayfile and stimulusfile there.
                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
                 !!! if 'debug' (case insensitive) is included          !!!
                 !!! in subjID string, this program runs as DEBUG mode; !!!
                 !!! stimulus images are saved as *.png format at       !!!
                 !!! ~/Retinotopy/Presentation/images                   !!!
                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
 exp_mode      : experiment mode that you want to run, one of
  - ccwexp : a wedge rotating counter-clockwisely + an expanding annulus
  - cwexp  : a wedge rotating clockwisely + an expanding annulus
  - ccwcont: a wedge rotating counter-clockwisely + a contracting annulus
  - cwcont : a wedge rotating clockwisely + a contracting annulus
 acq           : acquisition number (design file number),
                 an integer, such as 1, 2, 3, ...
 displayfile   : (optional) display condition file,
                 *.m file, such as 'RetDepth_display_fmri.m'
                 the file should be located in ./subjects/(subj)/
 stimulusfile  : (optional) stimulus condition file,
                 *.m file, such as 'RetDepth_stimulus_exp1.m'
                 the file should be located in ./subjects/(subj)/
 gamma_table   : (optional) table(s) of gamma-corrected video input values (Color LookupTable).
                 256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
                 or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
                 The *.mat should include a variable named "gamma_table" consists of a 256x3xN matrix.
                 if you use multiple (more than 1) displays and set a 256x3x1 gamma-table, the same
                 table will be applied to all displays. if the number of displays and gamma tables
                 are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
                 gamma_table will be applied to the second and third displays.
                 if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
 overwrite_flg : (optional) whether overwriting pre-existing result file. if 1, the previous result
                 file with the same acquisition number will be overwritten by the previous one.
                 if 0, the existing file will be backed-up by adding a prefix '_old' at the tail
                 of the file. 0 by default.
 force_proceed_flag : (optional) whether proceeding stimulus presentatin without waiting for
                 the experimenter response (e.g. presesing the ENTER key) or a trigger.
                 if 1, the stimulus presentation will be automatically carried on.
 !!! NOTICE !!!!
 displayfile & stimulusfile should be located at
 ./subjects/(subjID)/
 as ./subjects/(subjID)/*_display_fmri.m
    ./subjects/(subjID)/*_stimuli.m
 [output variables]
 no output matlab variable.
 [output files]
 1. result file
    stored ./subjects/(subjID)/results/(date)
    as ./subjects/(subjID)/results/(date)/(subjID)_idual_fixtask_(exp_mode)_results_run_(run_num).mat
 [example]
 >> idual_fixtask('HB','ccwexp',1,'ret_display.m','ret_checker_stimulus_exp1.m')
 [About displayfile]
 The contents of the displayfile are as below.
 (The file includs 6 lines of headers and following display parameters)
 (an example of the displayfile)
 % ************************************************************
 % This is the display configuration file for the retinotopy stimuli
 % Programmed by Hiroshi Ban Nov 01 2013
 % ************************************************************
 % display mode, one of "mono", "dual", "dualcross", "dualparallel", "cross", "parallel", "redgreen", "greenred",
 % "redblue", "bluered", "shutter", "topbottom", "bottomtop", "interleavedline", "interleavedcolumn", "propixxmono", "propixxstereo"
 dparam.ExpMode='mono';
 dparam.scrID=1; % screen ID, generally 0 for a single display setup, 1 for dual display setup
 % a method to start stimulus presentation
 % 0:ENTER/SPACE, 1:Left-mouse button, 2:the first MR trigger pulse (CiNet),
 % 3:waiting for a MR trigger pulse (BUIC) -- checking onset of pin #11 of the parallel port,
 % or 4:custom key trigger (wait for a key input that you specify as tgt_key).
 dparam.start_method=2;
 % a pseudo trigger key from the MR scanner when it starts, valid only when dparam.start_method=4;
 dparam.custom_trigger='t';
 % keyboard settings
 dparam.Key1=51; % key 1 (left)
 dparam.Key2=52; % key 2 (right)
 % screen settings
 %%% whether displaying the stimuli in full-screen mode or
 %%% as is (the precise resolution), 'true' or 'false' (true)
 dparam.fullscr=false;
 %%% the resolution of the screen height
 dparam.ScrHeight=1200;
 %% the resolution of the screen width
 dparam.ScrWidth=1920;
 % whether forcing to use specific frame rate, if 0, the frame rate wil bw computed in the ImagesShowPTB function.
 % if non zero, the value is used as the screen frame rate.
 dparam.force_frame_rate=60;
 % whther skipping the PTB's vertical-sync signal test. if 1, the sync test is skipped
 dparam.skip_sync_test=0;
 [About stimulusfile]
 The contents of the stimulusfile are as below.
 (The file includs 6 lines of headers and following stimulus parameters)
 (an example of the stimulusfile)
 % ************************************************************
 % This is the stimulus parameter file for the dual (wedge + annulus) retinotopy stimulus
 % Programmed by Hiroshi Ban Jan 25 2019
 % ************************************************************
 % "sparam" means "stimulus generation parameters"
 %%% stimulus parameters
 sparam.pol_width       = 48;    % wedge width in deg along polar angle
 sparam.pol_rotangle    = 12;    % rotation angle in deg
 sparam.pol_startangle  = -sparam.pol_width/2-90; % presentation start angle in deg, from right-horizontal meridian, ccw
 sparam.ecc_width       = sparam.pol_width/2;
 sparam.ecc_rotangle    = sparam.pol_rotangle;
 sparam.ecc_startangle  = -sparam.ecc_width/2-90;  % presentation start angle in deg, from right-horizontal meridian, ccw (actually this value is not used for the eccentricity stimuli (exp and cont))
 sparam.maxRad      = 6.0;  % maximum radius of  annulus (degrees)
 sparam.minRad      = 0;    % minumum
 %%% duration in msec for each cycle & repetitions
 % ===========================================================================================================================================
 % IMPORTANT NOTE: sparam.pol_cycle_duration x sparam.pol_numRepeats should be the same with sparam.ecc_cycle_duration x sparam.ecc_numRepeats
 % ===========================================================================================================================================
 sparam.pol_cycle_duration=60000; % msec
 sparam.pol_rest_duration =0; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
 sparam.pol_numRepeats=6;
 sparam.ecc_cycle_duration=40000; % msec
 sparam.ecc_rest_duration =8000; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
 sparam.ecc_numRepeats=9;
 %%% parameters used only for object-image-based retinotopy stimuli
 sparam.flip_duration=250; % msec
 sparam.nimg=120; % number of images to be presented at a frame
 sparam.imRatio=[0.2,0.5]; % image magnification ratio, [min, max] (0.0-1.0), the image sizes are randomly selected whithin this range
 sparam.imdepth=[-12,12]; % disparities (arcmins) added to the images, effective only in a stereo mode (e.g. shutter, dual, parallel etc)
 %%% set number of frames to flip the screen
 % Here, I set the number as large as I can to minimize vertical cynching error.
 % Set 1 if you want to flip the display at each vertical sync, but not recommended as it uses much CPU power
 sparam.waitframes = 6; % #frames for each object-images, 30 = 0.5 sec if the display vsynch = 60 Hz.
 %%% fixation period in msec before/after presenting the target stimuli, integer
 % must set a value more than 1 TR for initializing the frame counting.
 sparam.initial_fixation_time=[4000,4000];
 %%% fixation size & color
 sparam.fixtype=1; % 1: circular, 2: rectangular, 3: concentric fixation point
 sparam.fixsize=12; % radius in pixels
 sparam.fixcolor=[255,255,255];
 %%% background color
 sparam.bgcolor=sparam.colors(1,:); %[0,0,0];
 %%% background-patch colors (RGB)
 sparam.bgtype=1; % 1: a simple background with sparam.bgcolor (then, the parameters belows are not used), 2: a background with grid guides
 sparam.patch_size=[30,30]; % background patch size, [height,width] in pixels
 sparam.patch_num=[20,40];  % the number of background patches along vertical and horizontal axis
 sparam.patch_color1=[255,255,255];
 sparam.patch_color2=[0,0,0];
 %%% for converting degree to pixels
 run(fullfile(fileparts(mfilename('fullpath')),'sizeparams'));
 %sparam.pix_per_cm=57.1429;
 %sparam.vdist=65;
 %sparam.ipd=6.5;
 [HOWTO create stimulus files]
 1. All of the stimuli are created in this script in real-time
    with MATLAB scripts & functions.
    see ../Generation & ../Common directries.
 2. Stimulus parameters are defined in the display & stimulus file.
 [reference]
 for stmulus generation, see ../Generation & ../Common directories.
CROSS-REFERENCE INFORMATION
This function calls:
BackUpObsoleteFiles Backups already-existing file(s) in the target directory by adding some file-prefix.
CalcDistFromDisparity Calculates the actual distance (cm) from binocular disparity (arcmin).
CheckPTBversion Checks the version of the currently running Psychtoolbox.
CreateBackgroundImage Creates background image that can be used as a background of your stimulus displays.
CreateColoredNoise Creates colored (i.e. pink, brown(ian), blue, and white) noise image(s).
CreateFixationImgCircular Creates a circular fixation image for a monocular display setting.
CreateFixationImgConcentrateMono Creates a circular fixation image for a monocular display setting.
CreateFixationImgMono Creates a cross-shaped fixation image for a monocular display setting.
DisplayMessage2 Displays message on the center of each of multiple PTB windows.
GammaLoadPTB Loads and sets display gamma-table(s) using PTB Screen() function.
GammaResetPTB Resets display gamma with PTB Screen() function.
InitializePTBDisplays Initializes PTB screen(s) for monocular/binocular presentations using PsychImaging() function.
InitializeRandomSeed Initializes MATLAB internal state of a random seed.
ValidateStructureFields Validates the input structure and set the default values to the missing field(s)
eventlogger
isstructmember Checks whether the target struct contains a filed you specified as a member.
responselogger
shuffle Randomly sorts the input array.
ecc_GenerateCheckerBoard1D Generates checkerboard patterns (annulus-based subdivision) with an individual ID number on each patch.
pol_GenerateCheckerBoard1D Generates checkerboard patterns (polar angle-based subdivision) with an individual ID number on each patch.
This function is called by:
SOURCE CODE
function idual_fixtask(subjID,exp_mode,acq,displayfile,stimulusfile,gamma_table,overwrite_flg,force_proceed_flag)
% Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
% function idual_fixtask(subjID,exp_mode,acq,:displayfile,:stimulusfile,:gamma_table,:overwrite_flg,:force_proceed_flag)
% (: is optional)
%
% - This function generates and presents dual retinotopy stimulus (rotating wedge +
%   expanding/contracting annulus) on which object images are randomly located with
%   brownian noise images on its background.
%   The stimulus can be used to measure cortical retinotopy and to delineate retinotopic
%   borders using the standard phase-encoded or pRF (population receptive field) analysis techniques.
%
%   references: 1. Population receptive field estimates in human visual cortex.
%                  Dumoulin, S.O. and Wandell, B.A. (2008). Neuroimage, 39(2), 647-660.
%               2. Borders of multiple visual areas in humans revealed by functional magnetic resonance imaging.
%                  Sereno MI, Dale AM, Reppas JB, Kwong KK, Belliveau JW, Brady TJ, Rosen BR, Tootell RB. (1995).
%                  Science 268(5212), 889-893.
%               3. fMRI of human visual cortex.
%                  Engel SA, Rumelhart DE, Wandell BA, Lee AT, Glover GH, Chichilnisky EJ, Shadlen MN. (1994).
%                  Nature, 369(6481), 525.
%               4. Visual field maps in human cortex.
%                  Wandell BA, Dumoulin SO, Brewer AA. (2007). Neuron, 56(2), 366-383.
%
% - This script shoud be used with MATLAB Psychtoolbox version 3 or above.
%
% - Luminance detection task: the central fixation point (default: white)
%   randomly turns to gray. An observer has to press the button if s/he
%   detects this luminance change. Response keys are defined in displayfile.
%
% [about the object images used in this function]
% The object images used in this function (stored in ~/Retinotopy/object_images/ as object_image_database.mat) are
% obtained and modified from the databases publicly available from http://konklab.fas.harvard.edu/#
% I sincerely express my gratitude to the developers, distributors, and scientists in Dr Talia Konkle's research group
% for their contributions to these databases. When you use this function for your research, please cite the original
% papers listed below.
%
% - Tripartite Organization of the Ventral Stream by Animacy and Object Size.
%   Konkle, T., & Caramazza, A. (2013). Journal of Neuroscience, 33 (25), 10235-42.
%
% - A real-world size organization of object responses in occipito-temporal cortex.
%   Konkle. T., & Oliva, A. (2012). Neuron, 74(6), 1114-24.
%
% - Visual long-term memory has a massive storage capacity for object details.
%   Brady, T. F., Konkle, T., Alvarez, G. A. & Oliva, A. (2008). Proceedings of the National Academy of Sciences USA, 105(38), 14325-9.
%
% - Conceptual distinctiveness supports detailed visual long-term memory.
%   Konkle, T., Brady, T. F., Alvarez, G. A., & Oliva, A. (2010). Journal of Experimental Psychology: General, 139(3), 558-578.
%
% - A Familiar Size Stroop Effect: Real-world size is an automatic property of object representation.
%   Konkle, T., & Oliva, A. (2012). Journal of Experimental Psychology: Human Perception & Performance, 38, 561-9.
%
% [note]
% Behavioral task of (function_name)_fixtask is to detect changes of luminance
% of the central fixation point, while the task in (function_name) is to detect
% changes of luminance of one of the patches in the checkerboard stimuli.
% Here, the central fixation task is more easy to sustain the stable fixation
% on the center of the screen and may be suitable for naive/non-expert
% participants with minimizing unwilling eye movements. However, some studies
% have reported that attention to the target stimulus (checker-patch luminance
% change detection task) is required to get reliable retinotopic representations
% in higher-order visual areas.
%
%
% Created    : "2018-12-20 14:26:03 ban"
% Last Update: "2021-06-07 17:18:34 ban"
%
%
%
% [input variables]
% sujID         : ID of subject, string, such as 's01'
%                 you also need to create a directory ./subjects/(subj) and put displayfile and stimulusfile there.
%                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
%                 !!! if 'debug' (case insensitive) is included          !!!
%                 !!! in subjID string, this program runs as DEBUG mode; !!!
%                 !!! stimulus images are saved as *.png format at       !!!
%                 !!! ~/Retinotopy/Presentation/images                   !!!
%                 !!!!!!!!!!!!!!!!!! IMPORTANT NOTE !!!!!!!!!!!!!!!!!!!!!!!!
%
% exp_mode      : experiment mode that you want to run, one of
%  - ccwexp : a wedge rotating counter-clockwisely + an expanding annulus
%  - cwexp  : a wedge rotating clockwisely + an expanding annulus
%  - ccwcont: a wedge rotating counter-clockwisely + a contracting annulus
%  - cwcont : a wedge rotating clockwisely + a contracting annulus
% acq           : acquisition number (design file number),
%                 an integer, such as 1, 2, 3, ...
% displayfile   : (optional) display condition file,
%                 *.m file, such as 'RetDepth_display_fmri.m'
%                 the file should be located in ./subjects/(subj)/
% stimulusfile  : (optional) stimulus condition file,
%                 *.m file, such as 'RetDepth_stimulus_exp1.m'
%                 the file should be located in ./subjects/(subj)/
% gamma_table   : (optional) table(s) of gamma-corrected video input values (Color LookupTable).
%                 256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
%                 or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
%                 The *.mat should include a variable named "gamma_table" consists of a 256x3xN matrix.
%                 if you use multiple (more than 1) displays and set a 256x3x1 gamma-table, the same
%                 table will be applied to all displays. if the number of displays and gamma tables
%                 are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
%                 gamma_table will be applied to the second and third displays.
%                 if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
% overwrite_flg : (optional) whether overwriting pre-existing result file. if 1, the previous result
%                 file with the same acquisition number will be overwritten by the previous one.
%                 if 0, the existing file will be backed-up by adding a prefix '_old' at the tail
%                 of the file. 0 by default.
% force_proceed_flag : (optional) whether proceeding stimulus presentatin without waiting for
%                 the experimenter response (e.g. presesing the ENTER key) or a trigger.
%                 if 1, the stimulus presentation will be automatically carried on.
%
% !!! NOTICE !!!!
% displayfile & stimulusfile should be located at
% ./subjects/(subjID)/
% as ./subjects/(subjID)/*_display_fmri.m
%    ./subjects/(subjID)/*_stimuli.m
%
%
% [output variables]
% no output matlab variable.
%
%
% [output files]
% 1. result file
%    stored ./subjects/(subjID)/results/(date)
%    as ./subjects/(subjID)/results/(date)/(subjID)_idual_fixtask_(exp_mode)_results_run_(run_num).mat
%
%
% [example]
% >> idual_fixtask('HB','ccwexp',1,'ret_display.m','ret_checker_stimulus_exp1.m')
%
% [About displayfile]
% The contents of the displayfile are as below.
% (The file includs 6 lines of headers and following display parameters)
%
% (an example of the displayfile)
%
% % ************************************************************
% % This is the display configuration file for the retinotopy stimuli
% % Programmed by Hiroshi Ban Nov 01 2013
% % ************************************************************
%
% % display mode, one of "mono", "dual", "dualcross", "dualparallel", "cross", "parallel", "redgreen", "greenred",
% % "redblue", "bluered", "shutter", "topbottom", "bottomtop", "interleavedline", "interleavedcolumn", "propixxmono", "propixxstereo"
% dparam.ExpMode='mono';
%
% dparam.scrID=1; % screen ID, generally 0 for a single display setup, 1 for dual display setup
%
% % a method to start stimulus presentation
% % 0:ENTER/SPACE, 1:Left-mouse button, 2:the first MR trigger pulse (CiNet),
% % 3:waiting for a MR trigger pulse (BUIC) -- checking onset of pin #11 of the parallel port,
% % or 4:custom key trigger (wait for a key input that you specify as tgt_key).
% dparam.start_method=2;
%
% % a pseudo trigger key from the MR scanner when it starts, valid only when dparam.start_method=4;
% dparam.custom_trigger='t';
%
% % keyboard settings
% dparam.Key1=51; % key 1 (left)
% dparam.Key2=52; % key 2 (right)
%
% % screen settings
%
% %%% whether displaying the stimuli in full-screen mode or
% %%% as is (the precise resolution), 'true' or 'false' (true)
% dparam.fullscr=false;
%
% %%% the resolution of the screen height
% dparam.ScrHeight=1200;
%
% %% the resolution of the screen width
% dparam.ScrWidth=1920;
%
% % whether forcing to use specific frame rate, if 0, the frame rate wil bw computed in the ImagesShowPTB function.
% % if non zero, the value is used as the screen frame rate.
% dparam.force_frame_rate=60;
%
% % whther skipping the PTB's vertical-sync signal test. if 1, the sync test is skipped
% dparam.skip_sync_test=0;
%
%
% [About stimulusfile]
% The contents of the stimulusfile are as below.
% (The file includs 6 lines of headers and following stimulus parameters)
%
% (an example of the stimulusfile)
%
% % ************************************************************
% % This is the stimulus parameter file for the dual (wedge + annulus) retinotopy stimulus
% % Programmed by Hiroshi Ban Jan 25 2019
% % ************************************************************
%
% % "sparam" means "stimulus generation parameters"
%
% %%% stimulus parameters
% sparam.pol_width       = 48;    % wedge width in deg along polar angle
% sparam.pol_rotangle    = 12;    % rotation angle in deg
% sparam.pol_startangle  = -sparam.pol_width/2-90; % presentation start angle in deg, from right-horizontal meridian, ccw
%
% sparam.ecc_width       = sparam.pol_width/2;
% sparam.ecc_rotangle    = sparam.pol_rotangle;
% sparam.ecc_startangle  = -sparam.ecc_width/2-90;  % presentation start angle in deg, from right-horizontal meridian, ccw (actually this value is not used for the eccentricity stimuli (exp and cont))
%
% sparam.maxRad      = 6.0;  % maximum radius of  annulus (degrees)
% sparam.minRad      = 0;    % minumum
%
% %%% duration in msec for each cycle & repetitions
% % ===========================================================================================================================================
% % IMPORTANT NOTE: sparam.pol_cycle_duration x sparam.pol_numRepeats should be the same with sparam.ecc_cycle_duration x sparam.ecc_numRepeats
% % ===========================================================================================================================================
%
% sparam.pol_cycle_duration=60000; % msec
% sparam.pol_rest_duration =0; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
% sparam.pol_numRepeats=6;
%
% sparam.ecc_cycle_duration=40000; % msec
% sparam.ecc_rest_duration =8000; % msec, rest after each cycle, stimulation = cycle_duration-eccrest
% sparam.ecc_numRepeats=9;
%
% %%% parameters used only for object-image-based retinotopy stimuli
% sparam.flip_duration=250; % msec
% sparam.nimg=120; % number of images to be presented at a frame
% sparam.imRatio=[0.2,0.5]; % image magnification ratio, [min, max] (0.0-1.0), the image sizes are randomly selected whithin this range
% sparam.imdepth=[-12,12]; % disparities (arcmins) added to the images, effective only in a stereo mode (e.g. shutter, dual, parallel etc)
%
% %%% set number of frames to flip the screen
% % Here, I set the number as large as I can to minimize vertical cynching error.
% % Set 1 if you want to flip the display at each vertical sync, but not recommended as it uses much CPU power
% sparam.waitframes = 6; % #frames for each object-images, 30 = 0.5 sec if the display vsynch = 60 Hz.
%
% %%% fixation period in msec before/after presenting the target stimuli, integer
% % must set a value more than 1 TR for initializing the frame counting.
% sparam.initial_fixation_time=[4000,4000];
%
% %%% fixation size & color
% sparam.fixtype=1; % 1: circular, 2: rectangular, 3: concentric fixation point
% sparam.fixsize=12; % radius in pixels
% sparam.fixcolor=[255,255,255];
%
% %%% background color
% sparam.bgcolor=sparam.colors(1,:); %[0,0,0];
%
% %%% background-patch colors (RGB)
% sparam.bgtype=1; % 1: a simple background with sparam.bgcolor (then, the parameters belows are not used), 2: a background with grid guides
% sparam.patch_size=[30,30]; % background patch size, [height,width] in pixels
% sparam.patch_num=[20,40];  % the number of background patches along vertical and horizontal axis
% sparam.patch_color1=[255,255,255];
% sparam.patch_color2=[0,0,0];
%
% %%% for converting degree to pixels
% run(fullfile(fileparts(mfilename('fullpath')),'sizeparams'));
% %sparam.pix_per_cm=57.1429;
% %sparam.vdist=65;
% %sparam.ipd=6.5;
%
%
% [HOWTO create stimulus files]
% 1. All of the stimuli are created in this script in real-time
%    with MATLAB scripts & functions.
%    see ../Generation & ../Common directries.
% 2. Stimulus parameters are defined in the display & stimulus file.
%
%
% [reference]
% for stmulus generation, see ../Generation & ../Common directories.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Check the input variables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear global; clear mex;
if nargin<3, help(mfilename()); return; end
if nargin<4 || isempty(displayfile), displayfile=[]; end
if nargin<5 || isempty(stimulusfile), stimulusfile=[]; end
if nargin<6 || isempty(gamma_table), gamma_table=[]; end
if nargin<7 || isempty(overwrite_flg), overwrite_flg=1; end
if nargin<8 || isempty(force_proceed_flag), force_proceed_flag=0; end
% check the aqcuisition number
if acq<1, error('Acquistion number must be integer and greater than zero'); end
% check the experiment mode (stimulus type)
if ~strcmpi(exp_mode,'ccwexp') && ~strcmpi(exp_mode,'cwexp') && ~strcmpi(exp_mode,'ccwcont') && ~strcmpi(exp_mode,'cwcont')
  error('exp_mode should be one of "ccwexp", "cwexp", "ccwcont", and "cwcont". check the input variable.');
end
rootDir=fileparts(mfilename('fullpath'));
% check the subject directory
if ~exist(fullfile(rootDir,'subjects',subjID),'dir'), error('can not find subj directory. check the input variable.'); end
% check the display/stimulus files
if ~isempty(displayfile)
  if ~strcmpi(displayfile(end-1:end),'.m'), displayfile=[displayfile,'.m']; end
  if ~exist(fullfile(rootDir,'subjects',subjID,displayfile),'file'), error('displayfile not found. check the input variable.'); end
end
if ~isempty(stimulusfile)
  if ~strcmpi(stimulusfile(end-1:end),'.m'), stimulusfile=[stimulusfile,'.m']; end
  if ~exist(fullfile(rootDir,'subjects',subjID,stimulusfile),'file'), error('stimulusfile not found. check the input variable.'); end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Add path to the subfunctions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% add paths to the subfunctions
addpath(genpath(fullfile(rootDir,'..','Common')));
addpath(fullfile(rootDir,'..','Generation'));
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% For log file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% get date
today=datestr(now,'yymmdd');
% result directry & file
resultDir=fullfile(rootDir,'subjects',num2str(subjID),'results',today);
if ~exist(resultDir,'dir'), mkdir(resultDir); end
% record the output window
logfname=fullfile(resultDir,[num2str(subjID),'_idual_fixtask_',exp_mode,'_results_run_',num2str(acq,'%02d'),'.log']);
diary(logfname);
warning off; %#ok warning('off','MATLAB:dispatcher:InexactCaseMatch');
%%%%% try & catch %%%%%
try
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Check the PTB version
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PTB_OK=CheckPTBversion(3); % check wether the PTB version is 3
if ~PTB_OK, error('Wrong version of Psychtoolbox is running. %s requires PTB ver.3',mfilename()); end
% debug level, black screen during calibration
Screen('Preference', 'VisualDebuglevel', 3);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setup random seed
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
InitializeRandomSeed();
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Reset display Gamma-function
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(gamma_table)
  gamma_table=repmat(linspace(0.0,1.0,256),3,1); %#ok
  GammaResetPTB(1.0);
else
  GammaLoadPTB(gamma_table);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Validate dparam (displayfile) and sparam (stimulusfile) structures
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% organize dparam
dparam=struct(); % initialize
if ~isempty(displayfile), run(fullfile(rootDir,'subjects',subjID,displayfile)); end % load specific dparam parameters configured for each of the participants
dparam=ValidateStructureFields(dparam,... % validate fields and set the default values to missing field(s)
         'ExpMode','mono',...
         'scrID',1,...
         'start_method',0,...
         'custom_trigger','t',...
         'Key1',51,...
         'Key2',52,...
         'fullscr',false,...
         'ScrHeight',1200,...
         'ScrWidth',1920,...
         'force_frame_rate',60,...
         'skip_sync_test',0);
% organize sparam
sparam=struct(); % initialize
sparam.mode=exp_mode;
if ~isempty(stimulusfile), run(fullfile(rootDir,'subjects',subjID,stimulusfile)); end % load specific sparam parameters configured for each of the participants
sparam=ValidateStructureFields(sparam,... % validate fields and set the default values to missing field(s)
         'pol_width',48,...
         'pol_rotangle',12,...
         'pol_startangle',-48/2-90,...
         'ecc_width',48,...
         'ecc_rotangle',12,...
         'ecc_startangle',-48/2-90,...
         'maxRad',8,...
         'minRad',0,...
         'pol_cycle_duration',60000,...
         'pol_rest_duration',0,...
         'pol_numRepeats',6,...
         'ecc_cycle_duration',40000,...
         'ecc_rest_duration',8000,...
         'ecc_numRepeats',9,...
         'flip_duration',250,...
         'nimg',120,...
         'imRatio',[0.2,0.5],...
         'imdepth',[-12,12],... % effective only when the stimuli are presented in stereo mode (e.g. dual, cross, parallel etc)
         'waitframes',6,... % Screen('FrameRate',0)*(sparam.cycle_duration/1000) / (360/sparam.rotangle) / ( (size(sparam.colors,1)-1)*2 );
         'initial_fixation_time',[4000,4000],...
         'fixtype',1,...
         'fixsize',12,...
         'fixcolor',[255,255,255],...
         'bgcolor',[128,128,128],... % sparam.colors(1,:);
         'bgtype',1,...
         'patch_size',[30,30],...
         'patch_num',[20,40],...
         'patch_color1',[255,255,255],...
         'patch_color2',[0,0,0],...
         'pix_per_cm',57.1429,...
         'vdist',65,...
         'ipd',6.5);
% change unit from msec to sec.
sparam.initial_fixation_time=sparam.initial_fixation_time./1000; %#ok
% change unit from msec to sec.
sparam.pol_cycle_duration = sparam.pol_cycle_duration./1000;
sparam.pol_rest_duration  = sparam.pol_rest_duration./1000;
sparam.ecc_cycle_duration = sparam.ecc_cycle_duration./1000;
sparam.ecc_rest_duration  = sparam.ecc_rest_duration./1000;
sparam.flip_duration  = sparam.flip_duration./1000;
% set the other parameters
dparam.RunScript = mfilename();
sparam.RunScript = mfilename();
%% check varidity of parameters
fprintf('checking validity of stimulus generation/presentation parameters...');
if sparam.pol_cycle_duration*sparam.pol_numRepeats~=sparam.ecc_cycle_duration*sparam.ecc_numRepeats
  error('sparam.pol_cycle_duration x sparam.pol_numRepeats should be the same with sparam.ecc_cycle_duration x sparam.ecc_numRepeats. check the input variables.');
end
if mod(360,sparam.pol_rotangle), error('mod(360,sparam.pol_rotangle) should be 0. check the input variables.'); end
if mod(360,sparam.ecc_rotangle), error('mod(360,sparam.ecc_rotangle) should be 0. check the input variables.'); end
if mod(sparam.pol_width,sparam.pol_rotangle), error('mod(sparam.pol_width,sparam.pol_rotangle) should be 0. check the input variables.'); end
if mod(sparam.ecc_width,sparam.ecc_rotangle), error('mod(sparam.ecc_width,sparam.ecc_rotangle) should be 0. check the input variables.'); end
fprintf('done.\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying the presentation parameters you set
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
fprintf('The Presentation Parameters are as below.\n\n');
fprintf('************************************************\n');
fprintf('****** Script, Subject, Acquistion Number ******\n');
fprintf('Date & Time            : %s\n',strcat([datestr(now,'yymmdd'),' ',datestr(now,'HH:mm:ss')]));
fprintf('Running Script Name    : %s\n',mfilename());
fprintf('Subject ID             : %s\n',subjID);
fprintf('Acquisition Number     : %d\n',acq);
fprintf('********* Run Type, Display Image Type *********\n');
fprintf('Display Mode           : %s\n',dparam.ExpMode);
fprintf('use Full Screen Mode   : %d\n',dparam.fullscr);
fprintf('Start Method           : %d\n',dparam.start_method);
if dparam.start_method==4
  fprintf('Custom Trigger         : %d\n',dparam.custom_trigger);
end
fprintf('*************** Screen Settings ****************\n');
fprintf('Screen Height          : %d\n',dparam.ScrHeight);
fprintf('Screen Width           : %d\n',dparam.ScrWidth);
fprintf('*********** Stimulation Periods etc. ***********\n');
fprintf('Fixation Time(sec)     : %d & %d\n',sparam.initial_fixation_time(1),sparam.initial_fixation_time(2));
fprintf('[POL] Cycle Duration(sec) : %d\n',sparam.pol_cycle_duration);
fprintf('      Rest  Duration(sec) : %d\n',sparam.pol_rest_duration);
fprintf('      Repetitions(cycles) : %d\n',sparam.pol_numRepeats);
fprintf('[ECC] Cycle Duration(sec) : %d\n',sparam.ecc_cycle_duration);
fprintf('      Rest  Duration(sec) : %d\n',sparam.ecc_rest_duration);
fprintf('      Repetitions(cycles) : %d\n',sparam.ecc_numRepeats);
fprintf('Frame Flip(per VerSync): %d\n',sparam.waitframes);
fprintf('Total Time (sec)       : %d\n',sum(sparam.initial_fixation_time)+sparam.pol_numRepeats*sparam.pol_cycle_duration);
fprintf('**************** Stimulus Type *****************\n');
fprintf('Experiment Mode        : %s\n',sparam.mode);
fprintf('************ Response key settings *************\n');
fprintf('Reponse Key #1         : %d = %s\n',dparam.Key1,KbName(dparam.Key1));
fprintf('Reponse Key #2         : %d = %s\n',dparam.Key2,KbName(dparam.Key2));
fprintf('************************************************\n\n');
fprintf('Please carefully check before proceeding.\n\n');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialize response & event logger objects
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% initialize MATLAB objects for event and response logs
event=eventlogger();
resps=responselogger([dparam.Key1,dparam.Key2]);
resps.initialize(event); % initialize responselogger
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Wait for user reponse to start
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~force_proceed_flag
  [user_answer,resps]=resps.wait_to_proceed();
  if ~user_answer, diary off; return; end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initialization of Left & Right screens for binocular presenting/viewing mode
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if dparam.skip_sync_test, Screen('Preference','SkipSyncTests',1); end
[winPtr,winRect,nScr,dparam.fps,dparam.ifi,initDisplay_OK]=InitializePTBDisplays(dparam.ExpMode,sparam.bgcolor,0,[],dparam.scrID);
if ~initDisplay_OK, error('Display initialization error. Please check your exp_run parameter.'); end
HideCursor();
if isstructmember(dparam,'force_frame_rate')
  if dparam.force_frame_rate
    dparam.fps=dparam.force_frame_rate;
    dparam.ifi=1/dparam.fps;
  end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setting the PTB runnning priority to MAX
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% set the priority of this script to MAX
priorityLevel=MaxPriority(winPtr,'WaitBlanking');
Priority(priorityLevel);
% conserve VRAM memory: Workaround for flawed hardware and drivers
% 32 == kPsychDontShareContextRessources: Do not share ressources between
% different onscreen windows. Usually you want PTB to share all ressources
% like offscreen windows, textures and GLSL shaders among all open onscreen
% windows. If that causes trouble for some weird reason, you can prevent
% automatic sharing with this flag.
%Screen('Preference','ConserveVRAM',32);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Setting the PTB OpenGL functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Enable OpenGL mode of Psychtoolbox: This is crucially needed for clut animation
InitializeMatlabOpenGL();
% This script calls Psychtoolbox commands available only in OpenGL-based
% versions of the Psychtoolbox. (So far, the OS X Psychtoolbox is the
% only OpenGL-base Psychtoolbox.)  The Psychtoolbox command AssertPsychOpenGL will issue
% an error message if someone tries to execute this script on a computer without
% an OpenGL Psychtoolbox
AssertOpenGL();
% set OpenGL blend functions
Screen('BlendFunction', winPtr, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Displaying 'Initializing...'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% displaying texts on the center of the screen
DisplayMessage2('Initializing...',sparam.bgcolor,winPtr,nScr,'Arial',36);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing variables
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% unit conversion
% cm per pix
sparam.cm_per_pix=1/sparam.pix_per_cm;
% pixles per degree
sparam.pix_per_deg=round(1/(180*atan(sparam.cm_per_pix/sparam.vdist)/pi));
% deg to radian
% do not convert!
% sparam.width, sparam.phase, sparam.startangle, sparam.rotangle are used in deg formats
% number of checkerboard color
sparam.ncolors=(size(sparam.colors,1)-1)/2;
% sec to number of frames
nframe_fixation=round(sparam.initial_fixation_time.*dparam.fps./sparam.waitframes);
sparam.pol_npositions=360/sparam.pol_rotangle;
sparam.ecc_npositions=sparam.pol_npositions*(sparam.ecc_cycle_duration-sparam.ecc_rest_duration)/(sparam.pol_cycle_duration-sparam.pol_rest_duration);
nframe_stim=round((sparam.pol_cycle_duration-sparam.pol_rest_duration)*dparam.fps/(360/sparam.pol_rotangle)/sparam.waitframes);
nframe_flicker=round(sparam.flip_duration*dparam.fps/sparam.waitframes);
nframe_task=round(18/sparam.waitframes); % just arbitral, you can change as you like
%% initialize chackerboard parameters
% adjust size ratio considering full-screen effect
if dparam.fullscr
  % here, use width information alone, assuming that the pixel is square
  ratio_wid=( winRect(3)-winRect(1) )/dparam.ScrWidth;
  %ratio_hei=( winRect(4)-winRect(2) )/dparam.ScrHeight;
  % min/max radius of annulus
  rmin=sparam.minRad*ratio_wid; % !!! degree, not pixel or cm !!!
  rmax=sparam.maxRad*ratio_wid;
else
  rmin=sparam.minRad;
  rmax=sparam.maxRad;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Generating checkerboard patterns
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% [note]
% After this processing, each checkerboard image has checker elements with values as shown below
% 0 = background
% 1 = checker ID 1
% 2 = checker ID 2
% 3 = checker ID 3
% .....
% sparam.npatches = checker ID
% Each patch ID will be associated with a CLUT color of the same ID
%%% a wedge for polar representation
startangles=zeros(sparam.pol_npositions,1);
for nn=1:1:sparam.pol_npositions, startangles(nn)=sparam.pol_startangle+(nn-1)*sparam.pol_rotangle; end
[dummy1,dummy2,pol_checkerboard]=pol_GenerateCheckerBoard1D(rmin,rmax,sparam.pol_width,startangles,sparam.pix_per_deg,1,1,0);
%%% an annulus for eccentricity representation
eccedge=(rmax-rmin)/(sparam.ecc_npositions-1);
eccwidth=eccedge*(sparam.ecc_width/sparam.ecc_rotangle);
% get annuli's min/max lims
ecclims=zeros(sparam.ecc_npositions,3);
for nn=1:1:sparam.ecc_npositions %1:1:sparam.npositions
  minlim=rmin+(nn-1)*eccedge-eccwidth/2;
  if minlim<rmin, minlim=rmin; end
  maxlim=rmin+(nn-1)*eccedge+eccwidth/2;
  if maxlim>rmax, maxlim=rmax; end
  ecclims(nn,:)=[minlim,maxlim,eccwidth];
end
[dummy1,dummy2,ecc_checkerboard]=ecc_GenerateCheckerBoard1D(ecclims,360,sparam.ecc_startangle,sparam.pix_per_deg,1,1,0);
%% flip all data for ccw/cont
if ~isempty(strfind(sparam.mode,'ccw'))
  tmp_checkerboard=cell(sparam.pol_npositions,1);
  for nn=1:1:sparam.pol_npositions, tmp_checkerboard{nn}=pol_checkerboard{sparam.pol_npositions-(nn-1)}; end
  pol_checkerboard=tmp_checkerboard;
  clear tmp_checkerboard;
end
if ~isempty(strfind(sparam.mode,'cont'))
  tmp_checkerboard=cell(sparam.ecc_npositions,1);
  for nn=1:1:sparam.ecc_npositions, tmp_checkerboard{nn}=ecc_checkerboard{sparam.ecc_npositions-(nn-1)}; end
  ecc_checkerboard=tmp_checkerboard;
  clear tmp_checkerboard;
end
%%% generate the combined checkerboard patterns
commduration=lcm(sparam.pol_cycle_duration,sparam.ecc_cycle_duration); % the least common multiple duration at which the stimulus rotation turns to the beginning.
if commduration<sparam.pol_cycle_duration*sparam.pol_numRepeats
  pol_subrepeats=ceil(commduration/sparam.pol_cycle_duration);
  ecc_subrepeats=ceil(commduration/sparam.ecc_cycle_duration);
else
  fprintf('WARNING: It is recommended to adjust the sparam parameters so that lcm(sparam.pol_cycle_duration,sparam.ecc_cycle_duration) is less than sparam.pol_cycle_duration*sparam.pol_numRepeats\n');
  pol_subrepeats=sparam.pol_numRepeats;
  ecc_subrepeats=sparam.ecc_numRepeats;
end
% put the rest period for polar patterns
nrest=sparam.pol_npositions/(sparam.pol_cycle_duration-sparam.pol_rest_duration)*sparam.pol_rest_duration;
if nrest>0
  if ~isempty(strfind(sparam.mode,'ccw'))
    pol_checkerboard=[pol_checkerboard;repmat({zeros(size(pol_checkerboard{1}))},nrest,1)];
  else % if ~isempty(strfind(sparam.mode,'cw'))
    pol_checkerboard=[repmat({zeros(size(pol_checkerboard{1}))},nrest,1);pol_checkerboard];
  end
end
% put the rest period for eccentricity patterns
nrest=sparam.ecc_npositions/(sparam.ecc_cycle_duration-sparam.ecc_rest_duration)*sparam.ecc_rest_duration;
if nrest>0
  if ~isempty(strfind(sparam.mode,'cont'))
    ecc_checkerboard=[repmat({zeros(size(ecc_checkerboard{1}))},nrest,1);ecc_checkerboard];
  else % if ~isempty(strfind(sparam.mode,'ecc'))
    ecc_checkerboard=[ecc_checkerboard;repmat({zeros(size(ecc_checkerboard{1}))},nrest,1)];
  end
end
% multiply the patterns for the pol_subrepeats
pol_checkerboard=repmat(pol_checkerboard,pol_subrepeats,1);
% initialize the final checkerboard by eccentricity patterns
checkerboard=repmat(ecc_checkerboard,ecc_subrepeats,1);
% overwrite the polar patterns
for nn=1:1:length(pol_checkerboard)
  checkerboard{nn}(pol_checkerboard{nn}~=0)=pol_checkerboard{nn}(pol_checkerboard{nn}~=0);
end
clear pol_checkerboard ecc_checkerboard;
% generate the final checkerboard patterns
subrepeats=ceil(sparam.pol_numRepeats/pol_subrepeats);
checkerboard=repmat(checkerboard,[subrepeats,1]);
% cut the patterns that exceeds the whole stimulus presentation trials
if length(checkerboard) > sparam.pol_cycle_duration*sparam.pol_numRepeats/(sparam.pol_cycle_duration/sparam.pol_npositions)
  checkerboard=checkerboard(1:sparam.pol_cycle_duration*sparam.pol_numRepeats/(sparam.pol_cycle_duration/sparam.pol_npositions));
end
%% organize the checkerboard into masks
for nn=1:1:length(checkerboard)
  checkerboard{nn}=255.*(~checkerboard{nn});
  checkerboard{nn}=repmat(checkerboard{nn},[1,1,4]);
  checkerboard{nn}(:,:,1:3)=repmat(reshape(sparam.bgcolor,[1,1,3]),[size(checkerboard{nn},1),size(checkerboard{nn},2)]);
end
%% Make Checkerboard textures
checkertexture=cell(length(checkerboard),1);
for nn=1:1:length(checkerboard)
  checkertexture{nn}=Screen('MakeTexture',winPtr,checkerboard{nn});
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing a background brownian noise image
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%pdims=[4,4];
%szh=size(checkerboard{1},1);
%if mod(szh,pdims(1)), szh=szh+pdims(1)-mod(szh,pdims(1)); end
%szw=size(checkerboard{1},2);
%if mod(szw,pdims(2)), szw=szw+pdims(2)-mod(szw,pdims(1)); end
%bnimg=CreateColoredNoise([szh,szw],pdims,3,2,1,0,0);
%bnimg=bnimg(1:size(checkerboard{1},1),1:size(checkerboard{1},2),:);
bnimg=CreateColoredNoise(round([size(checkerboard{1},1),size(checkerboard{1},2)]./4),[1,1],3,2,1,0,0); % ./4 is for reducing computation time, 3 is required for RGB color noise
noisetexture=Screen('MakeTexture',winPtr,bnimg);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Initializing object images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% loading the object image database
load(fullfile(fileparts(mfilename('fullpath')),'..','object_images','object_image_database.mat')); % img is loaded on the memory
% shuffling the presentation order
img=img(:,:,:,shuffle(1:size(img,4)));
imgsz=[size(img,1),size(img,2)];
posLims=CenterRect([0,0,size(checkerboard{1},2),size(checkerboard{1},1)],winRect); % image location limit, [x_min, y_min, x_max, y_max], the image positions are randomly selected whithin this range
% initializing the firt object image textures
% image IDs
imgids=1:1:sparam.nimg;
imgids(imgids>size(img,4))=mod(imgids(imgids>size(img,4)),size(img,4));
imgids(imgids==0)=size(img,4);
% rectangles
cpos=[(posLims(3)-posLims(1)).*rand(sparam.nimg,1)+posLims(1),(posLims(4)-posLims(2)).*rand(sparam.nimg,1)+posLims(2)]; % center positions, [x,y]
cszs=(sparam.imRatio(2)-sparam.imRatio(1)).*rand(sparam.nimg,1)+sparam.imRatio(1); % image maginification factor
imgpos=[round(cpos(:,1)-cszs*imgsz(2)/2)+1,round(cpos(:,2)-cszs*imgsz(1)/2)+1,round(cpos(:,1)+cszs*imgsz(2)/2),round(cpos(:,2)+cszs*imgsz(1)/2)]';
% angles
imgrot=360.*rand(sparam.nimg,1);
% stereo depth
if nScr>1
  % compute image shift from disparity
  depths=(sparam.imdepth(2)-sparam.imdepth(1)).*rand(sparam.nimg,1)+sparam.imdepth(1);
  zdist=CalcDistFromDisparity(sparam.ipd,depths,sparam.vdist);
  zdist=sort(zdist,'descend');
  [Lshift,Rshift]=RayTrace_ScreenPos_X_MEX(zdist,sparam.ipd,sparam.vdist,sparam.pix_per_cm,0);
  stereopos{1}=[Lshift,zeros(sparam.nimg,1),Lshift,zeros(sparam.nimg,1)]';
  stereopos{2}=[Rshift,zeros(sparam.nimg,1),Rshift,zeros(sparam.nimg,1)]';
else
  stereopos{1}=repmat([0,0,0,0],[sparam.nimg,1])';
  stereopos{2}=repmat([0,0,0,0],[sparam.nimg,1])';
end
% generate the object image textures at the first frame
objecttextures=zeros(numel(imgids),1);
for pp=1:1:numel(imgids), objecttextures(pp)=Screen('MakeTexture',winPtr,img(:,:,:,imgids(pp))); end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Debug codes
%%%% saving the stimulus images as *.png format files and enter the debug (keyboard) mode
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% %%%%%% DEBUG codes start here
if strfind(upper(subjID),'DEBUG')
  Screen('CloseAll');
  save_dir=fullfile(resultDir,'images_idual_fixtask');
  if ~exist(save_dir,'dir'), mkdir(save_dir); end
  % open a new window for drawing stimuli
  stimRect=[0,0,size(checkerboard{1},2),size(checkerboard{1},1)];
  [winPtr,winRect]=Screen('OpenWindow',dparam.scrID,sparam.bgcolor,CenterRect(stimRect,Screen('Rect',dparam.scrID)));
  % set OpenGL
  priorityLevel=MaxPriority(winPtr,'WaitBlanking');
  Priority(priorityLevel);
  AssertOpenGL();
  Screen('BlendFunction', winPtr, GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
  % regenerate checkerboard textures
  for nn=1:1:length(checkerboard), checkertexture{nn}=Screen('MakeTexture',winPtr,checkerboard{nn}); end
  % check the number of flickers
  if mod((sparam.pol_cycle_duration-sparam.pol_rest_duration)/(360/sparam.pol_rotangle)/sparam.flip_duration,1)~=0
    warning('(sparam.pol_cycle_duration-sparam.pol_rest_duration)/(360/sparam.pol_rotangle)/sparam.flip_duration is not an integer. check the sparam parameters.');
  end
  % processing
  obj_counter=0;
  for nn=1:1:length(checkerboard)
    for cc=1:1:round((sparam.pol_cycle_duration-sparam.pol_rest_duration)/(360/sparam.pol_rotangle)/sparam.flip_duration);
      % brownian noise image
      bnimg=CreateColoredNoise(round([size(checkerboard{1},1),size(checkerboard{1},2)]./4),[1,1],3,2,1,0,0);
      noisetexture=Screen('MakeTexture',winPtr,bnimg);
      for pp=1:1:2 % by default, 2 image sets in one background noise flicker
        % generate object image textures
        % image IDs
        obj_counter=obj_counter+1;
        imgids=sparam.nimg*(obj_counter-1)+1:1:sparam.nimg*obj_counter;
        imgids(imgids>size(img,4))=mod(imgids(imgids>size(img,4)),size(img,4));
        imgids(imgids==0)=size(img,4);
        % rectangles
        cpos=[(stimRect(3)-stimRect(1)).*rand(sparam.nimg,1)+stimRect(1),(stimRect(4)-stimRect(2)).*rand(sparam.nimg,1)+stimRect(2)]; % center positions, [x,y]
        cszs=(sparam.imRatio(2)-sparam.imRatio(1)).*rand(sparam.nimg,1)+sparam.imRatio(1); % image maginification factor
        imgpos=[round(cpos(:,1)-cszs*imgsz(2)/2)+1,round(cpos(:,2)-cszs*imgsz(1)/2)+1,round(cpos(:,1)+cszs*imgsz(2)/2),round(cpos(:,2)+cszs*imgsz(1)/2)]';
        % angles
        imgrot=360.*rand(sparam.nimg,1);
        % stereo depth
        if nScr>1
          % compute image shift from disparity
          depths=(sparam.imdepth(2)-sparam.imdepth(1)).*rand(sparam.nimg,1)+sparam.imdepth(1);
          zdist=CalcDistFromDisparity(sparam.ipd,depths,sparam.vdist);
          zdist=sort(zdist,'descend');
          [Lshift,Rshift]=RayTrace_ScreenPos_X_MEX(zdist,sparam.ipd,sparam.vdist,sparam.pix_per_cm,0);
          stereopos{1}=[Lshift,zeros(sparam.nimg,1),Lshift,zeros(sparam.nimg,1)]';
          stereopos{2}=[Rshift,zeros(sparam.nimg,1),Rshift,zeros(sparam.nimg,1)]';
        else
          stereopos{1}=repmat([0,0,0,0],[sparam.nimg,1])';
          stereopos{2}=repmat([0,0,0,0],[sparam.nimg,1])';
        end
        for mm=1:1:numel(imgids), objecttextures(mm)=Screen('MakeTexture',winPtr,img(:,:,:,imgids(mm))); end
        for nnnn=1:1:nScr
          % drawing
          Screen('DrawTexture',winPtr,noisetexture,[],CenterRect(stimRect,winRect)); % noise textures
          Screen('DrawTextures',winPtr,objecttextures,[],imgpos+stereopos{nnnn},imgrot); % object images
          Screen('DrawTexture',winPtr,checkertexture{nn},[],CenterRect(stimRect,winRect)); % checkerboard mask
          % flip the window
          Screen('DrawingFinished',winPtr);
          Screen('Flip',winPtr,[],[],[],1);
          % get the current frame and save it
          imwrite(Screen('GetImage',winPtr,winRect),fullfile(save_dir,sprintf('retinotopy_%s_pos_%02d_type_%02d_%02d_stereo_%02d.png',sparam.mode,nn,cc,pp,nnnn)),'png');
        end
        % close the textures and OffScreenWindow
        for mm=1:1:numel(imgids), Screen('Close',objecttextures(mm)); end
      end
      Screen('Close',noisetexture);
    end % for cc=1:1:round((sparam.pol_cycle_duration-sparam.pol_rest_duration)/(360/sparam.pol_rotangle)/sparam.flip_duration);
  end % for nn=1:1:length(checkerboard)
  Screen('CloseAll');
  save(fullfile(save_dir,sprintf('stimulus_%s.mat',sparam.mode)),'checkerboard','sparam','dparam');
  keyboard;
end % if strfind(upper(subjID),'DEBUG')
% %%%%%% DEBUG code ends here
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Generating fixation detection task parameters
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% set task variables
% flag to decide whether presenting fixation task
totalframes=max(sum(nframe_fixation),1)+length(checkerboard)*nframe_stim;
num_tasks=ceil(totalframes/nframe_task);
task_flg=ones(1,num_tasks);
for nn=2:1:num_tasks
  if task_flg(nn-1)==2
    task_flg(nn)=1;
  else
    if mod(randi(4,1),4)==0 % this is arbitral, but I put these lines just to reduce the number of tasks
      task_flg(nn)=round(rand(1,1))+1;
    else
      task_flg(nn)=1;
    end
  end
end
task_flg=repmat(task_flg,nframe_task,1);
task_flg=task_flg(:);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Creating background images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if sparam.bgtype==1 % a simple background with sparam.bgcolor
  bgimg{1}=repmat(reshape(sparam.bgcolor,[1,1,3]),[dparam.ScrHeight,dparam.ScrWidth]);
elseif sparam.bgtype==2 % a background with grid guides
  % calculate the central aperture size of the background image
  edgeY=mod(dparam.ScrHeight,sparam.patch_num(1)); % delete the exceeded region
  p_height=round((dparam.ScrHeight-edgeY)/sparam.patch_num(1)); % height in pix of patch_height + interval-Y
  edgeX=mod(dparam.ScrWidth,sparam.patch_num(2)); % delete exceeded region
  p_width=round((dparam.ScrWidth-edgeX)/sparam.patch_num(2)); % width in pix of patch_width + interval-X
  if dparam.fullscr
    aperture_size=[2*( p_height*ceil( size(checkerboard{1},1)/2*( (winRect(4)-winRect(2))/dparam.ScrHeight ) /p_height ) ),...
                   2*( p_width*ceil( size(checkerboard{1},2)/2*( (winRect(3)-winRect(1))/dparam.ScrWidth ) /p_width ) )];
  else
    aperture_size=[2*( p_height*ceil(size(checkerboard{1},1)/2/p_height) ),...
                   2*( p_width*ceil(size(checkerboard{1},2)/2/p_width) )];
  end
  bgimg=CreateBackgroundImage([dparam.ScrHeight,dparam.ScrWidth],aperture_size,sparam.patch_size,sparam.bgcolor,sparam.patch_color1,sparam.patch_color2,sparam.fixcolor,sparam.patch_num,0,0,0);
else
  error('sparam.bgtype should be 1 or 2. check the input variable.');
end
% set mask and transparency in the middle region of the background where the target stimuli are to be presented.
% this mask is required to prevent the object images from being presented in the external regions.
bgimg=bgimg{1};
bgimg(:,:,4)=255*ones(size(bgimg,1),size(bgimg,2));
maskRect=CenterRect([1,1,size(checkerboard{1},2),size(checkerboard{1},1)],[1,1,size(bgimg,2),size(bgimg,1)]);
bgimg(maskRect(2)+1:maskRect(4),maskRect(1)+1:maskRect(3),4)=0; % alpha channel, transparency
background=Screen('MakeTexture',winPtr,bgimg);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Creating the central fixation, cross images
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create fixation cross images.
% Firstly larger fixations are generated, then they are antialiased. This is required to present a beautiful circle
if sparam.fixtype==1 % circular fixation
  fixW=CreateFixationImgCircular(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*sparam.fixsize,0,0);
  fixD=CreateFixationImgCircular(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*sparam.fixsize,0,0);
elseif sparam.fixtype==2 % rectangular fixation
  fixW=CreateFixationImgMono(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*2,4*ceil(0.4*sparam.fixsize),0,0);
  fixD=CreateFixationImgMono(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*2,4*ceil(0.4*sparam.fixsize),0,0);
elseif sparam.fixtype==3 % concentric fixation
  fixW=CreateFixationImgConcentrateMono(4*sparam.fixsize,sparam.fixcolor,sparam.bgcolor,4*[2,ceil(0.8*sparam.fixsize)],0,0,0);
  fixD=CreateFixationImgConcentrateMono(4*sparam.fixsize,[64,64,64],sparam.bgcolor,4*[2,ceil(0.8*sparam.fixsize)],0,0,0);
else
  error('sparam.fixtype should be one of 1,2, and 3. check the input variable.');
end
fixW=imresize(fixW,0.25);
fixD=imresize(fixD,0.25);
fix=cell(2,1); % 1 is for default fixation, 2 is for darker fixation (luminance detection task)
fix{1}=Screen('MakeTexture',winPtr,fixW);
fix{2}=Screen('MakeTexture',winPtr,fixD);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%% Prepare blue lines for stereo image flip sync with VPixx PROPixx
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% There seems to be a blueline generation bug on some OpenGL systems.
% SetStereoBlueLineSyncParameters(winPtr, winRect(4)) corrects the
% bug on some systems, but breaks on other systems.
% We'll just disable automatic blueline, and manually draw our own bluelines!
if strcmpi(dparam.ExpMode,'propixxstereo')
  SetStereoBlueLineSyncParameters(winPtr, winRect(4)+10);
1000   blueRectOn(1,:)=[0, winRect(4)-1, winRect(3)/4, winRect(4)];
1001   blueRectOn(2,:)=[0, winRect(4)-1, winRect(3)*3/4, winRect(4)];
1002   blueRectOff(1,:)=[winRect(3)/4, winRect(4)-1, winRect(3), winRect(4)];
1003   blueRectOff(2,:)=[winRect(3)*3/4, winRect(4)-1, winRect(3), winRect(4)];
1004 end
1005
1006
1007 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1008 %%%% Image size adjusting to match the current display resolutions
1009 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1010
1011 if dparam.fullscr
1012   ratio_wid= (winRect(3)-winRect(1))/dparam.ScrWidth;
1013   ratio_hei= (winRect(4)-winRect(2))/dparam.ScrHeight;
1014   bgSize   = [size(bgimg{1},2)*ratio_wid, size(bgimg{1},1)*ratio_hei];
1015   stimSize = [size(checkerboard{1},2)*ratio_wid, size(checkerboard{1},1)*ratio_hei];
1016   fixSize  = [2*sparam.fixsize*ratio_wid, 2*sparam.fixsize*ratio_hei];
1017 else
1018   bgSize   = [dparam.ScrWidth, dparam.ScrHeight];
1019   stimSize = [size(checkerboard{1},2), size(checkerboard{1},1)];
1020   fixSize  = [2*sparam.fixsize, 2*sparam.fixsize];
1021 end
1022
1023 % for some display modes in which one screen is splitted into two binocular displays
1024 if strcmpi(dparam.ExpMode,'cross') || strcmpi(dparam.ExpMode,'parallel') || ...
1025    strcmpi(dparam.ExpMode,'topbottom') || strcmpi(dparam.ExpMode,'bottomtop')
1026   bgSize=bgSize./2;
1027   stimSize=stimSize./2;
1028   fixSize=fixSize./2;
1029
1030   % adjust image size (note: in contrast, we have to keep the stereo shifts as they are)
1031   imgsz=imgsz./2;
1032
1033   % update lim positions just for the first frame
1034   posLims=CenterRect([0,0,size(checkerboard{1},2)./2,size(checkerboard{1},1)./2],winRect); % image location limit, [x_min, y_min, x_max, y_max], the image positions are randomly selected whithin this range
1035
1036   % update image locations just for the first frame
1037   cpos=[(posLims(3)-posLims(1)).*rand(sparam.nimg,1)+posLims(1),(posLims(4)-posLims(2)).*rand(sparam.nimg,1)+posLims(2)]; % center positions, [x,y]
1038   cszs=(sparam.imRatio(2)-sparam.imRatio(1)).*rand(sparam.nimg,1)+sparam.imRatio(1); % image maginification factor
1039   imgpos=[round(cpos(:,1)-cszs*imgsz(2)/2)+1,round(cpos(:,2)-cszs*imgsz(1)/2)+1,round(cpos(:,1)+cszs*imgsz(2)/2),round(cpos(:,2)+cszs*imgsz(1)/2)]';
1040 end
1041
1042 bgRect  = [0, 0, bgSize]; % used to display background images;
1043 stimRect= [0, 0, stimSize];
1044 fixRect = [0, 0, fixSize]; % used to display the central fixation point
1045
1046
1047 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1048 %%%% Generating additional mask which covers the outside region of the background.
1049 %%%% The mask is required to hide parts of the objects presented outside the background
1050 %%%% when the script is not running with full-screen mode.
1051 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1052
1053
1054 wrect=Screen('Rect',winPtr);
1055 if wrect(3)-wrect(1)>bgRect(3)-bgRect(1) | wrect(4)-wrect(2)>bgRect(4)-bgRect(2) % if background is smaller than the whole screen
1056   hide_flg=1;
1057   amskimg=repmat(reshape(sparam.colors(1,:),[1,1,3]),[wrect(4)-wrect(2),wrect(3)-wrect(1)]);
1058   amskimg(:,:,4)=255*ones(size(amskimg,1),size(amskimg,2));
1059   amskRect=CenterRect(bgRect,wrect);
1060   amskimg(amskRect(2)+1:amskRect(4),amskRect(1)+1:amskRect(3),4)=0; % alpha channel, transparency
1061
1062   abackground=Screen('MakeTexture',winPtr,amskimg);
1063 else
1064   hide_flg=0;
1065 end
1066
1067
1068 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1069 %%%% Initialize functions and variables for trial loop
1070 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1071
1072 % initialize variables that we will use during the experiment (faster)
1073 cur_frames=0;
1074
1075 % object image counter
1076 obj_counter=0;
1077
1078
1079 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1080 %%%% Displaying 'Ready to Start'
1081 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1082
1083 % displaying texts on the center of the screen
1084 DisplayMessage2('Ready to Start',sparam.bgcolor,winPtr,nScr,'Arial',36);
1085 ttime=GetSecs(); while (GetSecs()-ttime < 0.5), end  % run up the clock.
1086
1087
1088 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1089 %%%% Flip the display(s) to the background image(s)
1090 %%%% and inform the ready of stimulus presentation
1091 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1092
1093 % change the screen and wait for the trigger or pressing the start button
1094 for nn=1:1:nScr
1095   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1096   Screen('DrawTexture',winPtr,fix{2},[],CenterRect(fixRect,winRect));
1097   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1098
1099   % blue line for stereo sync
1100   if strcmpi(dparam.ExpMode,'propixxstereo')
1101     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1102     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1103   end
1104 end
1105 Screen('DrawingFinished',winPtr);
1106 Screen('Flip', winPtr,[],[],[],1);
1107
1108 % prepare the next frame for the initial fixation period
1109 for nn=1:1:nScr
1110   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1111   Screen('DrawTexture',winPtr,fix{1},[],CenterRect(fixRect,winRect)); % fix{1} is valid as no task in the first period
1112   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1113
1114   % blue line for stereo sync
1115   if strcmpi(dparam.ExpMode,'propixxstereo')
1116     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1117     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1118   end
1119 end
1120 Screen('DrawingFinished',winPtr);
1121
1122
1123 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1124 %%%% Wait for the first trigger pulse from fMRI scanner or start with button pressing
1125 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1126
1127 % add time stamp (this also works to load add_event method in memory in advance of the actual displays)
1128 fprintf('\nWaiting for the start...\n');
1129 event=event.add_event('Experiment Start',strcat([datestr(now,'yymmdd'),' ',datestr(now,'HH:mm:ss')]),NaN);
1130
1131 % waiting for stimulus presentation
1132 resps.wait_stimulus_presentation(dparam.start_method,dparam.custom_trigger);
1133 %PlaySound(1);
1134 fprintf('\nExperiment running...\n');
1135
1136
1137 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1138 %%%% Initial Fixation Period
1139 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1140
1141 vbl=Screen('Flip',winPtr,[],[],[],1); % the first flip
1142 [event,the_experiment_start]=event.set_reference_time(vbl);
1143 event=event.add_event('Initial Fixation',[]);
1144 fprintf('\nfixation\n\n');
1145 cur_frames=cur_frames+1;
1146
1147 % wait for the initial fixation
1148 for ff=1:1:nframe_fixation(1)
1149   for nn=1:1:nScr
1150     Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1151     Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect));
1152     Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1153
1154     % blue line for stereo sync
1155     if strcmpi(dparam.ExpMode,'propixxstereo')
1156       Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1157       Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1158     end
1159   end
1160   Screen('DrawingFinished',winPtr);
1161   while GetSecs()<vbl+(ff*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1162   Screen('Flip',winPtr,[],[],[],1);
1163
1164   % update task
1165   cur_frames=cur_frames+1;
1166   if task_flg(cur_frames-1)==2 && task_flg(cur_frames-2)==1, event=event.add_event('Luminance Task',[]); end
1167 end
1168
1169
1170 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1171 %%%% The Trial Loop
1172 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1173
1174 for cc=1:1:length(checkerboard)
1175
1176   %% stimulus presentation loop
1177   for ff=1:1:nframe_stim
1178
1179     %% display the current frame
1180     for nn=1:1:nScr
1181       Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1182       Screen('DrawTexture',winPtr,noisetexture,[],CenterRect(stimRect,winRect)); % noise textures
1183       Screen('DrawTextures',winPtr,objecttextures,[],imgpos+stereopos{nn},imgrot); % object images
1184       Screen('DrawTexture',winPtr,checkertexture{cc},[],CenterRect(stimRect,winRect)); % checkerboard mask
1185       Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect)); % the central fixation oval
1186       Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect)); % background
1187       if hide_flg, Screen('DrawTexture',winPtr,abackground,[],winRect); end % additional background to hide the external region
1188
1189       % blue line for stereo sync
1190       if strcmpi(dparam.ExpMode,'propixxstereo')
1191         Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1192         Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1193       end
1194     end
1195
1196     % flip the window
1197     Screen('DrawingFinished',winPtr);
1198     while GetSecs()<vbl+sparam.initial_fixation_time(1)+(((cc-1)*nframe_stim+(ff-1))*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1199     Screen('Flip',winPtr,[],[],[],1);
1200
1201     if ff==1
1202       event=event.add_event(sprintf('Trial: %d',cc),[]);
1203       if cc==1, fprintf('Trial: '); end
1204       if mod(cc,20)~=0 && cc~=length(checkerboard), fprintf(sprintf('%03d, ',cc)); end
1205       if mod(cc,20)==0 || cc==length(checkerboard), fprintf('%03d\n       ',cc); end
1206     end
1207
1208     % update task
1209     cur_frames=cur_frames+1;
1210     if task_flg(cur_frames)==2 && task_flg(cur_frames-1)==1, event=event.add_event('Luminance Task',[]); end
1211
1212     %% exit from the loop if the final frame is displayed
1213     if ff==nframe_stim && cc==length(checkerboard), continue; end
1214
1215     %% update IDs
1216
1217     % flickering checkerboard
1218     if ~mod(ff,nframe_flicker) % noise pattern reversal
1219       % update the brownian noise texture.
1220       Screen('Close',noisetexture);
1221       %bnimg=CreateColoredNoise([szh,szw],pdims,3,2,1,0,0);
1222       %bnimg=bnimg(1:size(checkerboard{1},1),1:size(checkerboard{1},2),:);
1223       bnimg=CreateColoredNoise(round([size(checkerboard{1},1),size(checkerboard{1},2)]./4),[1,1],3,2,1,0,0);
1224       noisetexture=Screen('MakeTexture',winPtr,bnimg);
1225     end
1226
1227     if ~mod(ff,ceil(nframe_flicker/2)) % object image reversal
1228       %% update object images
1229       for pp=1:1:numel(imgids), Screen('Close',objecttextures(pp)); end
1230
1231       obj_counter=obj_counter+1;
1232
1233       % image IDs
1234       imgids=sparam.nimg*obj_counter+1:1:sparam.nimg*(obj_counter+1); % the first image set is already presented
1235       imgids(imgids>size(img,4))=mod(imgids(imgids>size(img,4)),size(img,4));
1236       imgids(imgids==0)=size(img,4);
1237
1238       % rectangles
1239       cpos=[(posLims(3)-posLims(1)).*rand(sparam.nimg,1)+posLims(1),(posLims(4)-posLims(2)).*rand(sparam.nimg,1)+posLims(2)]; % center positions, [x,y]
1240       cszs=(sparam.imRatio(2)-sparam.imRatio(1)).*rand(sparam.nimg,1)+sparam.imRatio(1); % image maginification factor
1241       imgpos=[round(cpos(:,1)-cszs*imgsz(2)/2)+1,round(cpos(:,2)-cszs*imgsz(1)/2)+1,round(cpos(:,1)+cszs*imgsz(2)/2),round(cpos(:,2)+cszs*imgsz(1)/2)]';
1242
1243       % angles
1244       imgrot=360.*rand(sparam.nimg,1);
1245
1246       % stereo depth
1247       if nScr>1
1248         % compute image shift from disparity
1249         depths=(sparam.imdepth(2)-sparam.imdepth(1)).*rand(sparam.nimg,1)+sparam.imdepth(1);
1250         zdist=CalcDistFromDisparity(sparam.ipd,depths,sparam.vdist);
1251         zdist=sort(zdist,'descend');
1252         [Lshift,Rshift]=RayTrace_ScreenPos_X_MEX(zdist,sparam.ipd,sparam.vdist,sparam.pix_per_cm,0);
1253         stereopos{1}=[Lshift,zeros(sparam.nimg,1),Lshift,zeros(sparam.nimg,1)]';
1254         stereopos{2}=[Rshift,zeros(sparam.nimg,1),Rshift,zeros(sparam.nimg,1)]';
1255       else
1256         stereopos{1}=repmat([0,0,0,0],[sparam.nimg,1])';
1257         stereopos{2}=repmat([0,0,0,0],[sparam.nimg,1])';
1258       end
1259
1260       % generate object image textures
1261       for pp=1:1:numel(imgids), objecttextures(pp)=Screen('MakeTexture',winPtr,img(:,:,:,imgids(pp))); end
1262     end
1263   end % for ff=1:1:nframe_stim
1264 end % for cc=1:1:length(checkerboard)
1265
1266
1267 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1268 %%%% Final Fixation
1269 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1270
1271 for nn=1:1:nScr
1272   Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1273   Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect));
1274   Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1275
1276   % blue line for stereo sync
1277   if strcmpi(dparam.ExpMode,'propixxstereo')
1278     Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1279     Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1280   end
1281 end
1282 Screen('DrawingFinished',winPtr);
1283 while GetSecs()<vbl+sparam.initial_fixation_time(1)+sparam.pol_numRepeats*sparam.pol_cycle_duration-0.5*dparam.ifi, [resps,event]=resps.check_responses(event); end
1284 Screen('Flip',winPtr,[],[],[],1);
1285 %cur_frames=cur_frames+1;
1286 event=event.add_event('Final Fixation',[]);
1287 fprintf('\nfixation\n');
1288
1289 % wait for the initial fixation
1290 for ff=1:1:nframe_fixation(2)
1291   for nn=1:1:nScr
1292     Screen('SelectStereoDrawBuffer',winPtr,nn-1);
1293     Screen('DrawTexture',winPtr,fix{task_flg(cur_frames)},[],CenterRect(fixRect,winRect));
1294     Screen('DrawTexture',winPtr,background,[],CenterRect(bgRect,winRect));
1295
1296     % blue line for stereo sync
1297     if strcmpi(dparam.ExpMode,'propixxstereo')
1298       Screen('FillRect',winPtr,[0,0,255],blueRectOn(nn,:));
1299       Screen('FillRect',winPtr,[0,0,0],blueRectOff(nn,:));
1300     end
1301   end
1302   Screen('DrawingFinished',winPtr);
1303   while GetSecs()<vbl+sparam.initial_fixation_time(1)+sparam.pol_numRepeats*sparam.pol_cycle_duration+(ff*sparam.waitframes-0.5)*dparam.ifi, [resps,event]=resps.check_responses(event); end
1304   Screen('Flip',winPtr,[],[],[],1);
1305
1306   % update task
1307   cur_frames=cur_frames+1;
1308   if task_flg(cur_frames-1)==2 && task_flg(cur_frames-2)==1, event=event.add_event('Luminance Task',[]); end
1309 end
1310
1311 % the final clock up
1312 while GetSecs()-the_experiment_start<sum(sparam.initial_fixation_time)+sparam.pol_numRepeats*sparam.pol_cycle_duration
1313   [resps,event]=resps.check_responses(event);
1314 end
1315
1316
1317 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1318 %%%% Experiment & scanner end here
1319 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1320
1321 experimentDuration=GetSecs()-the_experiment_start;
1322 event=event.add_event('End',[]);
1323 fprintf('\n');
1324 fprintf('Experiment Completed: %.2f/%.2f secs\n',experimentDuration,...
1325         sum(sparam.initial_fixation_time)+sparam.pol_numRepeats*sparam.pol_cycle_duration);
1326 fprintf('\n');
1327
1328
1329 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1330 %%%% Cleaning up the PTB screen
1331 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1332
1333 Screen('CloseAll');
1334
1335 % closing datapixx
1336 if strcmpi(dparam.ExpMode,'propixxmono') || strcmpi(dparam.ExpMode,'propixxstereo')
1337   if Datapixx('IsViewpixx3D')
1338     Datapixx('DisableVideoLcd3D60Hz');
1339     Datapixx('RegWr');
1340   end
1341   Datapixx('Close');
1342 end
1343
1344 ShowCursor();
1345 Priority(0);
1346 GammaResetPTB(1.0);
1347
1348
1349 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1350 %%%% Write data into file for post analysis
1351 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1352
1353 % saving the results
1354 fprintf('saving data...');
1355
1356 % save data
1357 savefname=fullfile(resultDir,[num2str(subjID),'_idual_fixtask_',sparam.mode,'_results_run_',num2str(acq,'%02d'),'.mat']);
1358
1359 % backup the old file(s)
1360 if ~overwrite_flg
1361   BackUpObsoleteFiles(fullfile('subjects',num2str(subjID),'results',today),...
1362                       [num2str(subjID),'_idual_fixtask_',sparam.mode,'_results_run_',num2str(acq,'%02d'),'.mat'],'_old');
1363 end
1364
1365 eval(sprintf('save %s subjID acq sparam dparam event gamma_table;',savefname));
1366 fprintf('done.\n');
1367
1368 % calculate & display task performance
1369 fprintf('calculating task accuracy...\n');
1370 correct_event=cell(2,1); for ii=1:1:2, correct_event{ii}=sprintf('key%d',ii); end
1371 [task.numTasks,task.numHits,task.numErrors,task.numResponses,task.RT]=event.calc_accuracy(correct_event);
1372 event=event.get_event(); % convert an event logger object to a cell data structure
1373 eval(sprintf('save -append %s event task;',savefname));
1374 fprintf('done.\n');
1375
1376
1377 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1378 %%%% Removing path to the subfunctions, and finalizing the script
1379 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1380
1381 rmpath(genpath(fullfile(rootDir,'..','Common')));
1382 rmpath(fullfile(rootDir,'..','Generation'));
1383 clear all; clear mex; clear global;
1384 diary off;
1385
1386
1387 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1388 %%%% tell the experimenter that the measurements are completed
1389 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1390
1391 try
1392   for ii=1:1:3, Snd('Play',sin(2*pi*0.2*(0:900)),8000); end
1393 catch
1394   % do nothing
1395 end
1396
1397
1398 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1399 %%%% Catch the errors
1400 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1401
1402 catch lasterror
1403   % this "catch" section executes in case of an error in the "try" section
1404   % above.  Importantly, it closes the onscreen window if its open.
1405   Screen('CloseAll');
1406
1407   if exist('dparam','var')
1408     if isstructmember(dparam,'ExpMode')
1409       if strcmpi(dparam.ExpMode,'propixxmono') || strcmpi(dparam.ExpMode,'propixxstereo')
1410         if Datapixx('IsViewpixx3D')
1411           Datapixx('DisableVideoLcd3D60Hz');
1412           Datapixx('RegWr');
1413         end
1414         Datapixx('Close');
1415       end
1416     end
1417   end
1418
1419   ShowCursor();
1420   Priority(0);
1421   GammaResetPTB(1.0);
1422   tmp=lasterror; %#ok
1423   %if exist('event','var'), event=event.get_event(); end %#ok % just for debugging
1424   diary off;
1425   fprintf(['\nError detected and the program was terminated.\n',...
1426            'To check error(s), please type ''tmp''.\n',...
1427            'Please save the current variables now if you need.\n',...
1428            'Then, quit by ''dbquit''\n']);
1429   keyboard;
1430   rmpath(genpath(fullfile(rootDir,'..','Common')));
1431   rmpath(fullfile(rootDir,'..','Generation'));
1432   clear all; clear mex; clear global;
1433   return
1434 end % try..catch
1435
1436
1437 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1438 %%%%% That's it - we're done
1439 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1440 return;
1441 % end % function idual_fixtask