Description of BackUpObsoleteFiles
BackUpObsoleteFiles
PURPOSE
Backups already-existing file(s) in the target directory by adding some file-prefix.
SYNOPSIS
function [new_fname,backup_fname]=BackUpObsoleteFiles(tgt_dir,tgt_fname,backup_prefix)
DESCRIPTION
 Backups already-existing file(s) in the target directory by adding some file-prefix.
 function BackUpObsoleteFiles(tgt_dir,tgt_fname,:backup_prefix)
 (: is optional)
 This function detects all the target files in a specific directory and
 backups them by adding a prefix you set at the end of their file names.
 [example]
 When tgt_dir='../HB_results/';, and you have 3 files below in tgt_dir.
 1. results_run01.mat
 2. results_run01_old.mat
 3. results_run01_old_old.mat
 You are now wanting to save a new file named 'results_run01.mat' after
 backuping the old file listed above.
 To achieve this, you can run
 >> tgt_fname='results_run01.mat';
 >> backup_prefix='_old';
 >> BackUpObsoleteFiles(tgt_dir,tgt_fname,backup_prefix);
 Then, the files above (1-3) will be first renamed as
 1. results_run01_old.mat
 2. results_run01_old_old.mat
 3. results_run01_old_old_old.mat
 And you can save your new file as 'results_run01.mat' now.
 [input]
 tgt_dir       : taret directory to be looked for. should be set with a relative path format.
                 e.g. tgt_dir='../../HB/results/';
 tgt_fname     : target file name to be backuped. e.g. tgt_fname='params_run01.mat';
 backup_prefix : (optional) file prefix to be added to backup the old taget files.
                 '_old' by default.
 [output]
 new_fname     : the renamed(backuped) file name(s), cell structure
 old_fname     : the corresponding original file name(s), cell structure
 Created    : "2013-11-19 13:56:33 ban (ban.hiroshi@gmail.com)"
 Last Update: "2013-11-22 18:22:21 ban (ban.hiroshi@gmail.com)"
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cbar_fixtask Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cdual_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
chrf Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks for measuring and estimating a HRF function.
chrf_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
clgnlocalizer Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks, for localizing LGN.
clgnlocalizer_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
clocalizer_fixtask Color/luminance-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
cmeridian Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch luminance change-detection tasks.
cmeridian_fixtask Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
cretinotopy Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cretinotopy_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
dbar_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
ddual_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dhrf Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks for measuring and estimating a HRF function.
dhrf_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
dlgnlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change-detection tasks, for localizing LGN.
dlgnlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmeridian Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch depth change-detection tasks.
dmeridian_fixtask Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dretinotopy Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dretinotopy_fixtask Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function [new_fname,backup_fname]=BackUpObsoleteFiles(tgt_dir,tgt_fname,backup_prefix)
% Backups already-existing file(s) in the target directory by adding some file-prefix.
% function BackUpObsoleteFiles(tgt_dir,tgt_fname,:backup_prefix)
% (: is optional)
%
% This function detects all the target files in a specific directory and
% backups them by adding a prefix you set at the end of their file names.
%
% [example]
% When tgt_dir='../HB_results/';, and you have 3 files below in tgt_dir.
% 1. results_run01.mat
% 2. results_run01_old.mat
% 3. results_run01_old_old.mat
% You are now wanting to save a new file named 'results_run01.mat' after
% backuping the old file listed above.
%
% To achieve this, you can run
% >> tgt_fname='results_run01.mat';
% >> backup_prefix='_old';
% >> BackUpObsoleteFiles(tgt_dir,tgt_fname,backup_prefix);
%
% Then, the files above (1-3) will be first renamed as
% 1. results_run01_old.mat
% 2. results_run01_old_old.mat
% 3. results_run01_old_old_old.mat
% And you can save your new file as 'results_run01.mat' now.
%
% [input]
% tgt_dir       : taret directory to be looked for. should be set with a relative path format.
%                 e.g. tgt_dir='../../HB/results/';
% tgt_fname     : target file name to be backuped. e.g. tgt_fname='params_run01.mat';
% backup_prefix : (optional) file prefix to be added to backup the old taget files.
%                 '_old' by default.
%
% [output]
% new_fname     : the renamed(backuped) file name(s), cell structure
% old_fname     : the corresponding original file name(s), cell structure
%
%
% Created    : "2013-11-19 13:56:33 ban (ban.hiroshi@gmail.com)"
% Last Update: "2013-11-22 18:22:21 ban (ban.hiroshi@gmail.com)"
% check input variables
if nargin<2, help(mfilename()); return; end
if nargin<3 || isempty(backup_prefix), backup_prefix='_old'; end
% check directory
if ~exist(fullfile(pwd,tgt_dir),'dir'), error('can not find target directory. check input variable.'); end
% processing
tmpfname=fullfile(pwd,tgt_dir,tgt_fname); backup_fname=''; backup_counter=0;
while exist(tmpfname,'file')
  backup_counter=backup_counter+1;
  backup_fname{backup_counter}=tmpfname;
  [tmppath,tmpfname,tmpext]=fileparts(backup_fname{backup_counter});
  tmpfname=fullfile(tmppath,[tmpfname,backup_prefix,tmpext]);
end
new_fname='';
if ~isempty(backup_fname)
  for ii=length(backup_fname):-1:1
    [tmppath,tmpfname,tmpext]=fileparts(backup_fname{ii});
    new_fname{ii}=fullfile(tmppath,[tmpfname,backup_prefix,tmpext]);
    movefile(backup_fname{ii},new_fname{ii});
  end
end
return