Description of CalcDistFromDisparity
CalcDistFromDisparity
PURPOSE
Calculates the actual distance (cm) from binocular disparity (arcmin).
SYNOPSIS
function zdist = CalcDistFromDisparity(ipd,disparity,viewdist)
DESCRIPTION
 Calculates the actual distance (cm) from binocular disparity (arcmin).
 function zdist = CalcDistFromDisparity(ipd,disparity,viewdist)
 [INPUT]
 ipd       : distance between left and right eyes (cm)
 disparity : disparity (arcmin)
 viewdist  : viewing distance from eye to the screen (cm)
 [OUTPUT]
 zdist     : distance from the reference plane (cm)
 June 29 2009 Hiroshi Ban
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
CreateDepthPatchField Creates a plane of lattice depth patches
GetDotPositionsRDS Returns XY positions and colors (grayscale, 0-255) of dots in a Random-Dot-Stereogram(RDS) image.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function zdist = CalcDistFromDisparity(ipd,disparity,viewdist)
% Calculates the actual distance (cm) from binocular disparity (arcmin).
% function zdist = CalcDistFromDisparity(ipd,disparity,viewdist)
%
% [INPUT]
% ipd       : distance between left and right eyes (cm)
% disparity : disparity (arcmin)
% viewdist  : viewing distance from eye to the screen (cm)
%
% [OUTPUT]
% zdist     : distance from the reference plane (cm)
%
% June 29 2009 Hiroshi Ban
disp_rad = disparity ./ 60 .* 2.*pi ./ 360;
zdist = (viewdist.*viewdist.*disp_rad) ./ (ipd - viewdist.*disp_rad);
return;