Description of CheckPTBversion
CheckPTBversion
PURPOSE
Checks the version of the currently running Psychtoolbox.
SYNOPSIS
function [PTB_OK,vertxt] = CheckPTBversion(num_mainver_youwant)
DESCRIPTION
 Checks the version of the currently running Psychtoolbox.
 function [PTB_OK,vertxt] = CheckPTBversion(num_mainver_youwant)
 This function checks wether the PTB version you want to use is valid or not
 [input]
 num_mainver_youwant : version num you want, [val]
 [output]
 PTB_OK   : if the version of PTB is what you want, return 1. [0/1]
 vertxt   : text message from PTB
 Created    : "2010-01-29 13:41:41 ban"
 Last Update: "2013-11-22 18:29:12 ban (ban.hiroshi@gmail.com)"
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cbar_fixtask Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cdual_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
chrf Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks for measuring and estimating a HRF function.
chrf_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
clgnlocalizer Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks, for localizing LGN.
clgnlocalizer_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
clocalizer_fixtask Color/luminance-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
cmeridian Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch luminance change-detection tasks.
cmeridian_fixtask Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
cretinotopy Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cretinotopy_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
dbar_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
ddual_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dhrf Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks for measuring and estimating a HRF function.
dhrf_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
dlgnlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change-detection tasks, for localizing LGN.
dlgnlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmeridian Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch depth change-detection tasks.
dmeridian_fixtask Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dretinotopy Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dretinotopy_fixtask Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function [PTB_OK,vertxt] = CheckPTBversion(num_mainver_youwant)
% Checks the version of the currently running Psychtoolbox.
% function [PTB_OK,vertxt] = CheckPTBversion(num_mainver_youwant)
%
% This function checks wether the PTB version you want to use is valid or not
%
% [input]
% num_mainver_youwant : version num you want, [val]
%
% [output]
% PTB_OK   : if the version of PTB is what you want, return 1. [0/1]
% vertxt   : text message from PTB
%
% Created    : "2010-01-29 13:41:41 ban"
% Last Update: "2013-11-22 18:29:12 ban (ban.hiroshi@gmail.com)"
if nargin < 1
  wantver = num2str(3);
else
  wantver = num2str(num_mainver_youwant);
end
if ~exist('PsychtoolboxVersion','file')
  warning('MATLAB Psychtoolbox is not installed on this machine!'); %#ok
  PTB_OK=0;
  vertxt='MATLAB Psychtoolbox is not installed on this machine!';
  return
end
ptbver=PsychtoolboxVersion();
% PTB 3 changes the output of this to a char + a struct.
% nasty way of checking is to see if class of ver is char or double - check
% the first character as Matlab complains if the length of the string is
% different
c=class(ptbver);
if c(1)=='c'
  [vertxt,verstruct]=PsychtoolboxVersion();
  ver_ma = verstruct.major; ver_mi = verstruct.minor; ver_po = verstruct.point;
  ptbversion = [num2str(ver_ma) '.' num2str(ver_mi) '.' num2str(ver_po)];
  eval(sprintf('disp (''Using Psychtoolbox %s - make sure this is correct before you continue'');',ptbversion));
else
  disp('Your PTB''s version is 1 or 2');
  ver_ma = 2;
  vertxt = '';
end
if strcmp(num2str(ver_ma),wantver)
  PTB_OK = 1;
else
  PTB_OK = 0;
end
return