Description of cleanpport
cleanpport
PURPOSE
Sets most pins of the parallel port to zero.
SYNOPSIS
function cleanpport
DESCRIPTION
 Sets most pins of the parallel port to zero.
 function cleanpport
 no input/output variable
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
WaitingStimulusPresentation Waits for the start of stimulus presentation.
responselogger
responseloggerQueue
SOURCE CODE
function cleanpport
% Sets most pins of the parallel port to zero.
% function cleanpport
%
% no input/output variable
parport = digitalio('parallel','LPT1');
addline(parport,0:7,'out');
parport
putvalue(parport.Line(1:8),0)
delete(parport);