Description of DisplayMessage2
DisplayMessage2
PURPOSE
Displays message on the center of each of multiple PTB windows.
SYNOPSIS
function DisplayMessage2(message,bgcolor,winPtr,numScreens,drawing_font,drawing_size)
DESCRIPTION
 Displays message on the center of each of multiple PTB windows.
 function DisplayMessage2(message,bgcolor,winPtr,numScreens,drawing_font,drawing_size)
 Display message on the center of the left/right (if available)
 screen with your specified background color
 [requirement/dependency]
 Psychtoolbox ver.3 or above
 [input]
 message : string, you want to display
 bgcolor : background color [r,g,b]
 winPtr  : the parent window pointer
 numScreens   : the number of screens to be used
 drawing_font : option for setting text font (e.g. 'Arial')
 drawing_size : option for setting text size (e.g. 36)
 [ouput]
 no output variable
 Created: Feb 04 2010 Hiroshi Ban
 Last Update: "2017-11-23 14:26:57 ban"
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cbar_fixtask Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cdual_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
chrf Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks for measuring and estimating a HRF function.
chrf_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
clgnlocalizer Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks, for localizing LGN.
clgnlocalizer_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
clocalizer_fixtask Color/luminance-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
cmeridian Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch luminance change-detection tasks.
cmeridian_fixtask Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
cretinotopy Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cretinotopy_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
dbar_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
ddual_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dhrf Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks for measuring and estimating a HRF function.
dhrf_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
dlgnlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change-detection tasks, for localizing LGN.
dlgnlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmeridian Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch depth change-detection tasks.
dmeridian_fixtask Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dretinotopy Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dretinotopy_fixtask Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function DisplayMessage2(message,bgcolor,winPtr,numScreens,drawing_font,drawing_size)
% Displays message on the center of each of multiple PTB windows.
% function DisplayMessage2(message,bgcolor,winPtr,numScreens,drawing_font,drawing_size)
%
% Display message on the center of the left/right (if available)
% screen with your specified background color
%
% [requirement/dependency]
% Psychtoolbox ver.3 or above
%
% [input]
% message : string, you want to display
% bgcolor : background color [r,g,b]
% winPtr  : the parent window pointer
% numScreens   : the number of screens to be used
% drawing_font : option for setting text font (e.g. 'Arial')
% drawing_size : option for setting text size (e.g. 36)
%
% [ouput]
% no output variable
%
% Created: Feb 04 2010 Hiroshi Ban
% Last Update: "2017-11-23 14:26:57 ban"
% input variable check
if nargin < 3, help(mfilename()); end
if nargin < 4, numScreens=1; end
if nargin < 5, drawing_font='Arial'; end
if nargin < 6, drawing_size=36; end
% get the size of the screen
tmp=Screen(0,'rect');
screen_size=[tmp(3) tmp(4)];
% create background texture
grey_texture=repmat(bgcolor,screen_size(1),screen_size(2));
for ii=1:1:numScreens
  Screen('SelectStereoDrawBuffer',winPtr,ii-1);
  greyScreen=Screen('MakeTexture',winPtr,grey_texture);
  Screen('DrawTexture',winPtr,greyScreen);
  % set drawing options
  eval(sprintf('Screen(winPtr,''TextFont'',''%s'');',drawing_font));
  eval(sprintf('Screen(winPtr,''TextSize'',%d);',drawing_size));
  if sum(bgcolor)==0, eval(sprintf('Screen(winPtr,''TextColor'',%d);',255)); end
  % draw formatterd text on the center of the screen
  DrawFormattedText(winPtr,message,'center','center');
  Screen('Close',greyScreen);
end
% display
Screen('DrawingFinished',winPtr,2);
Screen('Flip',winPtr,[],[],[],1);
return