Description of GammaResetPTB
GammaResetPTB
PURPOSE
Resets display gamma with PTB Screen() function.
SYNOPSIS
function GammaResetPTB(luminance_ratio)
DESCRIPTION
 Resets display gamma with PTB Screen() function.
 function GammaResetPTB(:luminance_ratio)
 (: is optional)
 Resets gamma tables to a default (linear, no gamma applied) setting using PTB Screen() function.
 [input]
 luminance_ratio : gain(s) of the luminance, 0.0-1.0. a scalar or 1x3 vector (RGB). 1.0 by default.
                    I recommend to use this option only when gamma-level is adjusted by hardware
                    or device settings. I can not confirm the validity of this option on a computer
                    whose gamma is software-adjusted.
 [output]
 no output variable
 [dependency]
 Psychtoolbox by Denis Pelli et al. version 3.x or above. Should be installed independently.
 !!!NOTICE!!!
 If the luminance_ratio is too small, the general graphics driver can not handle it to assign voltage,
 and will result in error. luminance_ratio>=0.5 is recommended.
 Created    : "2011-09-06 17:44:10 banh"
 Last Update: "2020-02-27 19:05:18 ban"
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cbar_fixtask Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cdual_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
chrf Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks for measuring and estimating a HRF function.
chrf_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
clgnlocalizer Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks, for localizing LGN.
clgnlocalizer_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
clocalizer_fixtask Color/luminance-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
cmeridian Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch luminance change-detection tasks.
cmeridian_fixtask Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
cretinotopy Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cretinotopy_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
dbar_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
ddual_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dhrf Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks for measuring and estimating a HRF function.
dhrf_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
dlgnlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change-detection tasks, for localizing LGN.
dlgnlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmeridian Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch depth change-detection tasks.
dmeridian_fixtask Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dretinotopy Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dretinotopy_fixtask Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function GammaResetPTB(luminance_ratio)
% Resets display gamma with PTB Screen() function.
% function GammaResetPTB(:luminance_ratio)
% (: is optional)
%
% Resets gamma tables to a default (linear, no gamma applied) setting using PTB Screen() function.
%
% [input]
% luminance_ratio : gain(s) of the luminance, 0.0-1.0. a scalar or 1x3 vector (RGB). 1.0 by default.
%                    I recommend to use this option only when gamma-level is adjusted by hardware
%                    or device settings. I can not confirm the validity of this option on a computer
%                    whose gamma is software-adjusted.
%
% [output]
% no output variable
%
% [dependency]
% Psychtoolbox by Denis Pelli et al. version 3.x or above. Should be installed independently.
%
% !!!NOTICE!!!
% If the luminance_ratio is too small, the general graphics driver can not handle it to assign voltage,
% and will result in error. luminance_ratio>=0.5 is recommended.
%
%
% Created    : "2011-09-06 17:44:10 banh"
% Last Update: "2020-02-27 19:05:18 ban"
% check input variable
if nargin<1, luminance_ratio=1.0; end
if numel(luminance_ratio)==1, luminance_ratio=repmat(luminance_ratio,1,3); end
if size(luminance_ratio,1)==3, luminance_ratio=luminance_ratio'; end
% generate default gamma table (no correction)
gamma_table=([luminance_ratio(1)*linspace(0.0,1.0,256);luminance_ratio(2)*linspace(0.0,1.0,256);luminance_ratio(3)*linspace(0.0,1.0,256)])';
% applying the default gamma table
screencount=size(Screen('Screens'),2)-1;
for ii=1:screencount, Screen('LoadNormalizedGammaTable',ii,gamma_table); end
return