Description of GammaLoadPTB
GammaLoadPTB
PURPOSE
Loads and sets display gamma-table(s) using PTB Screen() function.
SYNOPSIS
function GammaLoadPTB(gamma_table)
DESCRIPTION
 Loads and sets display gamma-table(s) using PTB Screen() function.
 function GammaLoadPTB(:gamma_table)
 (: is optional)
 Loads gamma table(s) and sets it(them) on PTB engine
 [input]
 gamma_table : table(s) of gamma-corrected video input values (Color LookupTable).
               256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
               or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
               The *.mat should include a variable named "gamma_table".
               if you use multiple (more than 1) displays and set 256x3x1 gamma-table, the same
               table will be applied to all displays. if the number of displays and gamma tables
               are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
               gamma_table will be applied to the second and third displays.
               if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
 [output]
 no output variable
 Created    : "12-08-22 02:52:30 ban"
 Last Update: "2020-03-18 14:07:54 ban"
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cbar_fixtask Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cdual_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
chrf Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks for measuring and estimating a HRF function.
chrf_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
clgnlocalizer Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks, for localizing LGN.
clgnlocalizer_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
clocalizer_fixtask Color/luminance-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
cmeridian Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch luminance change-detection tasks.
cmeridian_fixtask Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
cretinotopy Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cretinotopy_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
dbar_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
ddual_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dhrf Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks for measuring and estimating a HRF function.
dhrf_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
dlgnlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change-detection tasks, for localizing LGN.
dlgnlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmeridian Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch depth change-detection tasks.
dmeridian_fixtask Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dretinotopy Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dretinotopy_fixtask Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function GammaLoadPTB(gamma_table)
% Loads and sets display gamma-table(s) using PTB Screen() function.
% function GammaLoadPTB(:gamma_table)
% (: is optional)
%
% Loads gamma table(s) and sets it(them) on PTB engine
%
% [input]
% gamma_table : table(s) of gamma-corrected video input values (Color LookupTable).
%               256(8-bits) x 3(RGB) x 1(or 2,3,... when using multiple displays) matrix
%               or a *.mat file specified with a relative path format. e.g. '/gamma_table/gamma1.mat'
%               The *.mat should include a variable named "gamma_table".
%               if you use multiple (more than 1) displays and set 256x3x1 gamma-table, the same
%               table will be applied to all displays. if the number of displays and gamma tables
%               are different (e.g. you have 3 displays and 256x3x!2! gamma-tables), the last
%               gamma_table will be applied to the second and third displays.
%               if empty, normalized gamma table (repmat(linspace(0.0,1.0,256),3,1)) will be applied.
%
% [output]
% no output variable
%
%
% Created    : "12-08-22 02:52:30 ban"
% Last Update: "2020-03-18 14:07:54 ban"
% check input variable
if nargin<1 || isempty(gamma_table), gamma_table=(repmat(linspace(0.0,1.0,256),3,1))'; end
% load matlab matrix if the input gamma_table is a file.
if ischar(gamma_table)
  if ~exist(fullfile(pwd,gamma_table),'file'), error('can not find gamma table file. check input variable.'); end
  gamma_table=load(fullfile(pwd,gamma_table));
  gamma_table=gamma_table.gammatable; % just to organize structure...
end
if size(gamma_table,1)==3 && size(gamma_table,2)==256, gamma_table=permute(gamma_table,[2,1,3]); end
if size(gamma_table,1)~=256 || size(gamma_table,2)~=3, error('gamma_table should be 256x3xN matrix. check input variable'); end
% check OS (Windows or the others)
is_windows=false;
winstr=mexext(); winstr=winstr(end-2:end);
if strcmpi(winstr,'w32') || strcmpi(winstr,'w64'), is_windows=true; end
% apply gamma table(s)
% first, applying the first table to whole displays
screencount=size(Screen('Screens'),2)-1;
if screencount==1
  Screen('LoadNormalizedGammaTable',0,gamma_table(:,:,1)); return
else
  for ii=1:1:screencount, Screen('LoadNormalizedGammaTable',ii,gamma_table(:,:,1)); end
end
% then, setting each of gamma tables to each of displays
if is_windows % 0 = whole displays, 1 = the first, 2 = the second, ...
  for ii=2:1:screencount, Screen('LoadNormalizedGammaTable',ii,gamma_table(:,:,min(ii,size(gamma_table,3)))); end
else % 0 = the first display, 1 = the second, ...
  for ii=1:1:screencount, Screen('LoadNormalizedGammaTable',ii,gamma_table(:,:,min(ii+1,size(gamma_table,3)))); end
end
return