Description of RDSfast
RDSfast
PURPOSE
Generates left/right Random-Dot-Stereogram images.
SYNOPSIS
function [imgL,imgR]=RDSfast(heightfield,dotDens,imgNum,colors,ipd,vdist,pix_per_cm,oversampling_ratio,display_flag,save_flag)
DESCRIPTION
 Generates left/right Random-Dot-Stereogram images.
 function [imgL,imgR]=RDSfast(heightfield,dotDens,imgNum,ipd,vdist,pix_per_cm,oversampling_ratio,display_flag,save_flag)
 Generate left/right Random Dot Stereogram (RDS) Images based on heightfield.
 The generated images are the same size with heightfield image.
 [input]
 heightfield : height field to generate RDS, [row,col]
               *NOTICE* the unit of the height should be cm
 dotDens     : density of the random dots, [percent(1-100,integer)]
 imgNum      : the number of images to be generated, [num]
 colors      : dot/background colors, [0-255(dot1),0-255(dot2),0-255(background)]
 ipd         : distance between left/right pupils, [cm]
 vdist       : visual distance from screen to eyes, [cm]
 pix_per_cm  : pixels per cm
 oversampling_ratio : if above 1, oversampling of heightfield & disparity position
                      is conducted. [val](default,1)
 display_flag: if 1, the generated images will be displayed, [0/1]
 save_flag   : if 1, the generated images will be saved as RDS_imgs.mat, [0/1]
 [output]
 imgL        : generated image(s) for left eye, cells [row,col]
 imgR        : generated image(s) for right eye, cells [row,col]
 [example]
 field=CreateExpField([480,480],3,1);
 [imgL,imgR]=RDSfast(field,30,1,[255,0,128],6.4,50,57,1,0);
 !!! NOTICE !!!
 This is high-speed version of RDS generator.
 However, the density of dots will be biased in this method.
 If the bias affects your experiment, please use RDS instead.
 Created: "2010-04-03 14:05:21 ban"
 Last Update: "2019-05-17 16:15:23 ban"
CROSS-REFERENCE INFORMATION
This function calls:
RDS Generates left/right Random-Dot-Stereogram images.
RayTrace_ScreenPos_X Calculates the horizontal screen position (in pixels) of a point distance from the visual midline and z-distance.
size_one2one Displays an image in true size without any scaling
This function is called by:
SOURCE CODE
function [imgL,imgR]=RDSfast(heightfield,dotDens,imgNum,colors,ipd,vdist,pix_per_cm,oversampling_ratio,display_flag,save_flag)
% Generates left/right Random-Dot-Stereogram images.
% function [imgL,imgR]=RDSfast(heightfield,dotDens,imgNum,ipd,vdist,pix_per_cm,oversampling_ratio,display_flag,save_flag)
%
% Generate left/right Random Dot Stereogram (RDS) Images based on heightfield.
% The generated images are the same size with heightfield image.
%
% [input]
% heightfield : height field to generate RDS, [row,col]
%               *NOTICE* the unit of the height should be cm
% dotDens     : density of the random dots, [percent(1-100,integer)]
% imgNum      : the number of images to be generated, [num]
% colors      : dot/background colors, [0-255(dot1),0-255(dot2),0-255(background)]
% ipd         : distance between left/right pupils, [cm]
% vdist       : visual distance from screen to eyes, [cm]
% pix_per_cm  : pixels per cm
% oversampling_ratio : if above 1, oversampling of heightfield & disparity position
%                      is conducted. [val](default,1)
% display_flag: if 1, the generated images will be displayed, [0/1]
% save_flag   : if 1, the generated images will be saved as RDS_imgs.mat, [0/1]
%
% [output]
% imgL        : generated image(s) for left eye, cells [row,col]
% imgR        : generated image(s) for right eye, cells [row,col]
%
% [example]
% field=CreateExpField([480,480],3,1);
% [imgL,imgR]=RDSfast(field,30,1,[255,0,128],6.4,50,57,1,0);
%
% !!! NOTICE !!!
% This is high-speed version of RDS generator.
% However, the density of dots will be biased in this method.
% If the bias affects your experiment, please use RDS instead.
%
% Created: "2010-04-03 14:05:21 ban"
% Last Update: "2019-05-17 16:15:23 ban"
% --- input variable check
if nargin<1, help RDS; return; end
if nargin<2 || isempty(dotDens), dotDens=10; end
if nargin<3 || isempty(imgNum), imgNum=1; end
if nargin<4 || isempty(colors), colors=[255,0,128]; end
if nargin<5 || isempty(ipd), ipd=6.4; end
if nargin<6 || isempty(vdist), vdist=65; end
if nargin<7 || isempty(pix_per_cm),
  % cm per pix
  % 1 inch = 2.54 cm, my PC's display is 1920x1200, 15.4 inch.
  % So, 15.4(inch)*2.54(cm) / sqrt(1920^2+1200^2) (pix) = XXX cm/pixel
  cm_per_pix=15.4*2.54/sqrt(1920^2+1200^2);
  pix_per_cm=1/cm_per_pix;
end
if nargin<8 || isempty(oversampling_ratio), oversampling_ratio=1; end
if nargin<9 || isempty(display_flag), display_flag=0; end
if nargin<10 || isempty(save_flag), save_flag=0; end
if numel(colors)~=3
  error('RDS requires 3colors [0-255(dot1),0-255(dot2),0-255(background)]. Check input variable.');
end
% adjust parameters for oversampling
if oversampling_ratio~=1
  heightfield=imresize(heightfield,oversampling_ratio,'bilinear');
  dotDens=dotDens/oversampling_ratio;
  ipd=ipd*oversampling_ratio;
  vdist=vdist*oversampling_ratio;
  pix_per_cm=pix_per_cm*oversampling_ratio;
end
% --- initalize random seed
%InitializeRandomSeed;
% --- calculate position shifts for each value of heightfield
%heightfield=-1*heightfield; % since RayTrace_ScreenPos_X assumes the near position is minus value.
posL=round(RayTrace_ScreenPos_X(heightfield,ipd,vdist,1,pix_per_cm,0));
posR=round(RayTrace_ScreenPos_X(heightfield,ipd,vdist,2,pix_per_cm,0));
% --- generate RDS images
imgL=cell(imgNum,1); imgR=cell(imgNum,1);
for ii=1:1:imgNum
  imgL{ii}=double(colors(2)*ones(size(heightfield)));
  imgR{ii}=double(colors(2)*ones(size(heightfield)));
end
for n=1:1:imgNum
  % create initial random dot image
  randXY=randi(round(oversampling_ratio*100/dotDens),size(heightfield));
  randXY(randXY~=round(oversampling_ratio*100/dotDens))=0;
  randXY(logical(randXY))=1;
  randXY(randXY==0)=colors(3); % background;
  % set 2 colors
  [row,col]=find(randXY==1);
  for ii=1:1:size(row,1)
    if mod(randi(2),2)
      randXY(row(ii),col(ii))=colors(1); % dot1;
    else
      randXY(row(ii),col(ii))=colors(2); % dot2;
    end
  end
  % create left/right images
  tmpL=colors(3)*ones(size(randXY));
  tmpR=colors(3)*ones(size(randXY));
  for ii=1:1:size(row,1)
    if ~isnan(posL(row(ii),col(ii))) && ~isnan(posR(row(ii),col(ii)))
      % if you want to put the paired dots only, use the codes below
      %if ( (1 < col+posL(row,col)) && (col+posL(row,col) < size(randXY,2)) ) && ...
      %      ( (1 < col+posR(row,col)) && (col+posR(row,col) < size(randXY,2)) )
      %  tmpL(row,col+posL(row,col))=colors(1);
      %  tmpR(row,col+posR(row,col))=colors(1);
      %end
      % if you do not want to fill the 'hole' of the image use the codes below
      %if ( (1 < col+posL(row,col)) && (col+posL(row,col) < size(randXY,2)) )
      %  tmpL(row,col+posL(row,col))=colors(1);
      %end
      %if ( (1 < col+posR(row,col)) && (col+posR(row,col) < size(randXY,2)) )
      %  tmpR(row,col+posR(row,col))=colors(1);
      %end
      % if you want to fill the 'hole' of the image, use the codes below instead of those above
      if col(ii)+posL(row(ii),col(ii)) < 1
        tmpL(row(ii),col(ii)+posL(row(ii),col(ii))+size(tmpL,2))=randXY(row(ii),col(ii));
      elseif size(randXY,2) < col(ii)+posL(row(ii),col(ii))
        tmpL(row(ii),col(ii)+posL(row(ii),col(ii))-size(tmpL,2))=randXY(row(ii),col(ii));
      else
        tmpL(row(ii),col(ii)+posL(row(ii),col(ii)))=randXY(row(ii),col(ii));
      end
      if col(ii)+posR(row(ii),col(ii)) < 1
        tmpR(row(ii),col(ii)+posR(row(ii),col(ii))+size(tmpR,2))=randXY(row(ii),col(ii));
      elseif size(randXY,2) < col(ii)+posR(row(ii),col(ii))
        tmpR(row(ii),col(ii)+posR(row(ii),col(ii))-size(tmpR,2))=randXY(row(ii),col(ii));
      else
        tmpR(row(ii),col(ii)+posR(row(ii),col(ii)))=randXY(row(ii),col(ii));
      end
    end
  end
  % adjust oversampled image to the original size
  if oversampling_ratio~=1
    imgL{n}=imresize(uint8(tmpL),1/oversampling_ratio,'bilinear');
    imgR{n}=imresize(uint8(tmpR),1/oversampling_ratio,'bilinear');
  else
    imgL{n}=uint8(tmpL);
    imgR{n}=uint8(tmpR);
  end
end % for n=1:1:imgNum
% --- plot the results
if display_flag
  figure; hold on;
  for n=1:1:imgNum
    M = [imgL{n} 127*ones(size(imgL{n},1),20) imgR{n} 127*ones(size(imgL{n},1),20) imgL{n}];
    im_h = imagesc(M,[0 255]);
    axis off
    % truesize is necessary to avoid automatic scaling
    size_one2one(im_h);
    colormap(gray);
    shg;
  end
end
% --- save the results
if save_flag
  save RDS_imgs.mat imgL imgR posL posR heightfield;
end
return;