Description of shift
shift
PURPOSE
Shifts 2D matrix circularly.
SYNOPSIS
function res = shift(mtx, offset)
DESCRIPTION
 Shifts 2D matrix circularly.
 [RES] = shift(MTX, OFFSET)
 Circular shift 2D matrix samples by OFFSET (a [Y,X] 2-vector),
 such that  RES(POS) = MTX(POS-OFFSET).
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
mseq Generates maximum-length sequence(s).
test_mseq compare auto-correlations between M-sequnce & MT19937's rondom array
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
gen_multifocal_windows Generates multi-focal retinotopy stimulus windows for GLM modeling or pRF (population receptive field) analysis.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
c_multifocal ************************************************************
SOURCE CODE
function res = shift(mtx, offset)
% Shifts 2D matrix circularly.
% [RES] = shift(MTX, OFFSET)
%
% Circular shift 2D matrix samples by OFFSET (a [Y,X] 2-vector),
% such that  RES(POS) = MTX(POS-OFFSET).
dims = size(mtx);
offset = mod(-offset,dims);
res = [ mtx(offset(1)+1:dims(1), offset(2)+1:dims(2)),  ...
          mtx(offset(1)+1:dims(1), 1:offset(2));        ...
        mtx(1:offset(1), offset(2)+1:dims(2)),          ...
      mtx(1:offset(1), 1:offset(2)) ];
return