Description of shuffle
shuffle
PURPOSE
Randomly sorts the input array.
SYNOPSIS
function [Y,index] = shuffle(X)
DESCRIPTION
 Randomly sorts the input array.
 function [Y,index] = shuffle(X)
 Randomly sorts X.
 If X is a vector, sorts all of X, so Y = X(index).
 If X is an m-by-n matrix, sorts each column of X, so
   for j=1:n, Y(:,j)=X(index(:,j),j).
 Also see SORT, Sample, Randi, and RandSample.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
ConvertRandomDots2RandomOvals Converts each of random dots to a shaded oval texture.
GenerateBlockDesignSequence Generates a pseudo-random sequence for Block-design fMRI experiment.
GenerateRandomDesignSequence Generates a randomozed event array.
GenerateRandomEventSequenceByMseq [UNDER PROGRAMMING] Generates a pseudo-randomo event array using the Maximum Length Sequence method.
RDSbyOval Generates left/right Random-Dot-Stereogram images using oval textures, not dots.
RDSbyOvalFast Generates left/right Random-Dot-Stereogram images.
RDSbyOvalFastest Generates left/right Random-Dot-Stereogram images.
RDSbyOvalbyRayTracer Generates left/right Random-Dot-Stereogram images using Ray-tracer procedure (thus, vertical disparities are included).
RDSfastest_NEW function [imgL,imgR]=RDSfastest_NEW(posL,posR,wdot,bdot,dotalpha,dotDens,bgcolor,skipzero_flg,avoid_bias_flg,use_mex_flg)
RDSfastest_with_acor_noise_MEX Generates left/right Random-Dot-AntiCorrelated-Stereogram images with noise (MEX-based).
RDSfastest_with_noise_MEX Generates left/right Random-Dot-Stereogram images with noise (MEX-based).
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function [Y,index] = shuffle(X)
% Randomly sorts the input array.
% function [Y,index] = shuffle(X)
%
% Randomly sorts X.
% If X is a vector, sorts all of X, so Y = X(index).
% If X is an m-by-n matrix, sorts each column of X, so
%   for j=1:n, Y(:,j)=X(index(:,j),j).
%
% Also see SORT, Sample, Randi, and RandSample.
% xx/xx/92  dhb  Wrote it.
% 10/25/93  dhb  Return index.
% 5/25/96   dgp  Made consistent with sort and "for i=Shuffle(1:10)"
% 6/29/96   dgp  Edited comments above.
%
%
% Last Update: "2013-11-22 23:53:31 ban (ban.hiroshi@gmail.com)"
[null,index] = sort(rand(size(X)));
Y = X(index);