Description of ValidateStructureFields
ValidateStructureFields
PURPOSE
Validates the input structure and set the default values to the missing field(s)
SYNOPSIS
function structval=ValidateStructureFields(structval,varargin)
DESCRIPTION
 Validates the input structure and set the default values to the missing field(s)
 function structval=ValidateStructureFields(structval,varargin)
 [about]
 This function validates the input structure, structval, and set the default values
 to the missing field(s).
 For instance, if you run the codes below,
 >> dparam=struct(); % initialize
 >> if ~isempty(displayfile) % displayfile contains specific fields (dparam.*), and they are loaded onto memory
 >>   run(fullfile(rootDir,'subjects',subjID,displayfile));
 >> end
 >> dparam=ValidateStructureFields(dparam,... % validate fields and set the default values to missing field(s)
 >>          'ExpMode','shutter',...
 >>          'start_method',1,...
 >>          'custom_trigger',KbName(84),...
 >>          'Key1',37,...
 >>          'Key2',39,...
 >>          'givefeedback',1,...
 >>          'fullscr',false,...
 >>          'ScrHeight',1200,...
 >>          'ScrWidth',1920);
 The procedures below are evaluated.
 1.'dparam' structure is initialized as empty at the begnning.
 2. the specific fileds and values are set at the socond-fourth lines.
 3. the 'dparam' structure is validated and set the default values to the missing field(s) with this function.
 If some fields are already configured by user, this function never overwrites them.
 [input]
 structval : a structure to be validated. structval=struct(); by default.
 From the second input variables, please set as
 'fieldname1',default_value(s),'fieldname2',default_value(s),'fieldname3',default_value(s),...
 Therefore, the total number of input variables should be 1 (structval) + 2*N (N=the number of fields to be set to structval).
 [output]
 structval : structure with full fields you want.
 Created    : "2018-11-11 21:38:52 ban"
 Last Update: "2018-11-11 22:03:36 ban"
CROSS-REFERENCE INFORMATION
This function calls:
isstructmember Checks whether the target struct contains a filed you specified as a member.
This function is called by:
cbar Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cbar_fixtask Color/luminance-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
cdual Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cdual_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
chrf Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks for measuring and estimating a HRF function.
chrf_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
clgnlocalizer Color/luminance-defined checkerboard stimulus with checker-patch luminance change-detection tasks, for localizing LGN.
clgnlocalizer_fixtask Color/luminance-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
clocalizer Color/luminance-defined checkerboard stimulus with checkerboard luminance change detection tasks, for localizing specific retinotopic (eccentricity) regions.
clocalizer_fixtask Color/luminance-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
cmeridian Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch luminance change-detection tasks.
cmeridian_fixtask Color/luminance-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
cmultifocal Color/luminance-defined multi-focal retinotopy checkerboard stimulus with checker-patch luminance change-detection tasks.
cmultifocal_fixtask Color/luminance-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
cretinotopy Color/luminance-defined checkerboard retinotopy stimulus with checker-patch luminance change-detection tasks.
cretinotopy_fixtask Color/luminance-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dbar Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch depth change-detection tasks.
dbar_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard bar stimulus (pRF) with checker-patch luminance change-detection tasks.
ddual Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
ddual_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
dhrf Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks for measuring and estimating a HRF function.
dhrf_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
dlgnlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change-detection tasks, for localizing LGN.
dlgnlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with fixation-point luminance change-detection tasks, for localizing LGN.
dlocalizer Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with checker-patch depth change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dlocalizer_fixtask Random-Dot-Stereogram(RDS)-defined checkerboard stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
dmeridian Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with checker-patch depth change-detection tasks.
dmeridian_fixtask Random-Dot-Stereogram(RDS)-defined dual checkerboard stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
dmultifocal Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with checker-patch depth change-detection tasks.
dmultifocal_fixtask Random-Dot-Stereogram(RDS)-defined multi-focal retinotopy checkerboard stimulus with fixation luminance change-detection tasks.
dretinotopy Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with checker-patch depth change-detection tasks.
dretinotopy_fixtask Random-Dot-Stereogram(RDS)-defined stereo checkerboard retinotopy stimulus with fixation luminance change-detection tasks.
gen_bar_windows Generates bar stimulus windows for pRF (population receptive field) analysis.
gen_dual_windows Generates retinotopy stimulus (polar wedge + eccentricity annulus) windows for pRF (population receptive field) analysis.
gen_multifocal_windows Generates multi-focal retinotopy stimulus windows for GLM modeling or pRF (population receptive field) analysis.
gen_retinotopy_windows Generates retinotopy stimulus (polar/eccentricity) windows for pRF (population receptive field) analysis.
ibar_fixtask Object-image-defined bar stimulus with fixation luminance change-detection tasks.
idual_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
ihrf_fixtask Object-image-defined checkerboard stimulus with fixation-point luminance change detection tasks for measuring and estimating a HRF function.
ilgnlocalizer_fixtask Object-image-defined wedge stimulus with fixation luminance change-detection tasks, for localizing LGN.
ilocalizer_fixtask Object-image-defined annulus stimulus with central-fixation luminance change detection tasks, for localizing specific retinotopic (iso-eccentricity) regions.
imeridian_fixtask Object-image-defined dual wedge stimulus along horizontal/vertical meridians with fixation luminance change-detection tasks.
imultifocal_fixtask Object-image-defined multi-focal retinotopy stimulus with fixation luminance change-detection tasks.
iretinotopy_fixtask Object-image-defined retinotopy stimulus with fixation luminance change-detection tasks.
SOURCE CODE
function structval=ValidateStructureFields(structval,varargin)
% Validates the input structure and set the default values to the missing field(s)
% function structval=ValidateStructureFields(structval,varargin)
%
% [about]
% This function validates the input structure, structval, and set the default values
% to the missing field(s).
% For instance, if you run the codes below,
% >> dparam=struct(); % initialize
% >> if ~isempty(displayfile) % displayfile contains specific fields (dparam.*), and they are loaded onto memory
% >>   run(fullfile(rootDir,'subjects',subjID,displayfile));
% >> end
% >> dparam=ValidateStructureFields(dparam,... % validate fields and set the default values to missing field(s)
% >>          'ExpMode','shutter',...
% >>          'start_method',1,...
% >>          'custom_trigger',KbName(84),...
% >>          'Key1',37,...
% >>          'Key2',39,...
% >>          'givefeedback',1,...
% >>          'fullscr',false,...
% >>          'ScrHeight',1200,...
% >>          'ScrWidth',1920);
%
% The procedures below are evaluated.
% 1.'dparam' structure is initialized as empty at the begnning.
% 2. the specific fileds and values are set at the socond-fourth lines.
% 3. the 'dparam' structure is validated and set the default values to the missing field(s) with this function.
% If some fields are already configured by user, this function never overwrites them.
%
% [input]
% structval : a structure to be validated. structval=struct(); by default.
%
% From the second input variables, please set as
% 'fieldname1',default_value(s),'fieldname2',default_value(s),'fieldname3',default_value(s),...
% Therefore, the total number of input variables should be 1 (structval) + 2*N (N=the number of fields to be set to structval).
%
% [output]
% structval : structure with full fields you want.
%
%
% Created    : "2018-11-11 21:38:52 ban"
% Last Update: "2018-11-11 22:03:36 ban"
% check the input variable
if nargin<1, help(mfilename()); return; end
if mod(nargin,2)==0
  % here, %s is required as error can not recoginize cadge return (e.g. \n) unless it has more than 1 input variables.
  error(['the total number of input variables should be\n',...
         '1 (structval) + 2 (name and default value(s)) * N (N=the number of fields to be set to structval).\n',...
         'check the input variables%s'],'.');
end
% loop for the fields with validating the
for ii=1:2:nargin-1
  if isstructmember(structval,varargin{ii})
    if isempty(getfield(structval,varargin{ii}))
      structval=setfield(structval,varargin{ii},varargin{ii+1});
    end
  else
    structval=setfield(structval,varargin{ii},varargin{ii+1});
  end
end
return