function installed_status=isMATLABToolBoxAvailable(toolbox_name,force_check_flg)

% Checks whether the specific MATLAB toolbox is installed in the current MATLAB.
% function installed_status=isMATLABToolBoxAvailable(toolbox_name,:force_check_flg)
% (: is optional)
%
% This function checks whether the target toolbox is installed in the current MATLAB,
% utilizing the outputs of the 'ver' function.
%
% [example]
% if ~isMATLABToolBoxAvailable('Parallel Computing Toolbox')
%   for nn=1:1:size(btidx,2)
%     integration_index_bt(:,nn)=nanmean(integration_index(:,btidx(:,nn)),2);
%     transfer_index_bt(:,nn)=nanmedian(transfer_index(:,btidx(:,nn)),2);
%   end
% else
%   parfor nn=1:size(btidx,2), integration_index_bt(:,nn)=nanmean(integration_index(:,btidx(:,nn)),2); end
%   parfor nn=1:size(btidx,2), transfer_index_bt(:,nn)=nanmedian(transfer_index(:,btidx(:,nn)),2); end
% end
%
% [input]
% toolbox_name     : toolbox name to be checked.
%                    e.g. toolbox_name='Statistics Toolbox'; % case insensitive
% force_check_flg  : (optional) if 1, forcing to check the target toolbox is installed,
%                    ignoring the standard toolbox. Required to check the availability
%                    of the third party toolbox.
%                    0 by default.
%
% [output]
% installed_status : if 1, the target toolbox is installed otherwise it is not.
%
%
% Created    : "2017-01-21 16:35:31 ban"
% Last Update: "2017-02-10 17:49:11 ban"

% check the input variable
if nargin<1 || isempty(toolbox_name), help(mfilename()); installed_status=0; return; end
if nargin<2 || isempty(force_check_flg), force_check_flg=0; end

% check whether the toolbox_name is one of the official toolboxes.
if ~force_check_flg
  featureStr = {'Aerospace Blockset'; ...
                'Aerospace Toolbox'; ...
                'Bioinformatics Toolbox'; ...
                'Communication Blocks'; ...
                'Communication Toolbox'; ...
                'Compiler'; ...
                'Control Toolbox'; ...
                'Curve Fitting Toolbox'; ...
                'Data Acq Toolbox'; ...
                'Database Toolbox'; ...
                'Datafeed Toolbox'; ...
                'Dial and Gauge Blocks'; ...
                'Distrib Computing Toolbox'; ...
                'Econometrics Toolbox'; ...
                'EDA Simulator Link DS'; ...
                'Embedded Target c166'; ...
                'Embedded Target c2000'; ...
                'Embedded Target c6000'; ...
                'Embedded Target MPC555'; ...
                'Excel Link'; ...
                'Filter Design HDL Coder'; ...
                'Filter Design Toolbox'; ...
                'Fin Derivatives Toolbox'; ...
                'Financial Toolbox'; ...
                'Fixed Income Toolbox'; ...
                'Fixed Point Toolbox'; ...
                'Fixed-Point Blocks'; ...
                'Fuzzy Toolbox'; ...
                'GADS Toolbox'; ...
                'IDE Link MU'; ...
                'Identification Toolbox'; ...
                'Image Acquisition Toolbox'; ...
                'Image Toolbox'; ...
                'Image Processing Toolbox'; ...
                'Instr Control Toolbox'; ...
                'Link for Incisive'; ...
                'Link for ModelSim'; ...
                'Link for Tasking'; ...
                'Link for VisualDSP'; ...
                'MAP Toolbox'; ...
                'MATLAB'; ...
                'MATLAB Builder for dot Net'; ...
                'MATLAB Builder for Java'; ...
                'MATLAB Distrib Comp Engine'; ...
                'MATLAB Excel Builder'; ...
                'MATLAB Link for CCS'; ...
                'MATLAB Report Gen'; ...
                'MBC Toolbox'; ...
                'MPC Toolbox'; ...
                'NCD Toolbox'; ...
                'Neural Network Toolbox'; ...
                'OPC Toolbox'; ...
                'Optimization Toolbox'; ...
                'Parallel Computing Toolbox'; ...
                'PDE Toolbox'; ...
                'Power System Blocks'; ...
                'Real-Time Win Target'; ...
                'Real-Time Workshop'; ...
                'RF Blockset'; ...
                'RF Toolbox'; ...
                'Robust Toolbox'; ...
                'RTW Embedded Coder'; ...
                'Signal Blocks'; ...
                'Signal Toolbox'; ...
                'SimBiology'; ...
                'SimDriveline'; ...
                'SimElectronics'; ...
                'SimEvents'; ...
                'SimHydraulics'; ...
                'SimMechanics'; ...
                'Simscape'; ...
                'SIMULINK'; ...
                'Simulink Control Design'; ...
                'Simulink Design Verifier'; ...
                'Simulink HDL Coder'; ...
                'Simulink Param Estimation'; ...
                'SIMULINK Report Gen'; ...
                'SL Verification Validation'; ...
                'Spline Toolbox'; ...
                'Stateflow'; ...
                'Stateflow Coder'; ...
                'Statistics Toolbox'; ...
                'Symbolic Toolbox'; ...
                'SystemTest'; ...
                'Video and Image Blockset'; ...
                'Virtual Reality Toolbox'; ...
                'Wavelet Toolbox'; ...
                'XPC Embedded Option'; ...
                'XPC Target'};

  name_checker=0;
  for ii=1:1:length(featureStr)
    if strcmpi(toolbox_name,featureStr{ii})
      name_checker=1;
      break;
    end
  end
  if ~name_checker, error('toolbox_name to be checked seems to be wrong or not included in the official toolboxes. check the input variable.'); end
end % if force_check_flg

% processing
installed_status=0;
v=ver;
for ii=1:1:numel(v)
  if strcmpi(toolbox_name,v(ii).Name)
    installed_status=1;
    break;
  end
end

return
